### ISSUE TITLE
Fix @Test Timeout to Actually Time Out

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-pioneer/junit-pioneer#10]
#7 created an annotation `@Test` that mirrors JUnit 4's behavior as closely as possible. Regarding `timeout` this ran into limitations of Jupiters extension model: Without the ability to push the test execution onto another thread there is no way to abandon when the timeout is reached. This should be fixed once Jupiter implements the extension point (junit-team/junit5#157).

**Comment by AJNeufeld** [comment]
I expect you mean junit-team/junit5#157

**Comment by nicolaiparlog** [comment]
😆 Yes, I do. Fixed it.

**Comment by smoyer64** [comment]
There's a working example at https://github.com/selesy/junit5/blob/issues/343-document-testrule-compatibility/documentation/src/test/java/example/testrule/TimeoutJupiterDemo.java which might have some useful code.

**Comment by Bukama** [comment]
> I expect you mean junit-team/junit5#157
> 
> 

This has been merged. That‘s why I remove the blocked label. (If i get it done in the app... - no but vis mobile browser)
