### ISSUE TITLE
TempDirectory is not cleaning himself after tests are finished

### ISSUE THREAD

**Issue by JorisPotier** [junit-pioneer/junit-pioneer#100]
Hi,

I try to use the TempDirectory extension in order to work to a clean workspace for each test, and finally delete this workspace. I'm using a custom FS (Jimfs) exactly like in this sample extracted from the docs : 

```
class MyTests {
    private static FileSystem fileSystem;

    @BeforeAll
    static void createFileSystem() {
        fileSystem = Jimfs.newFileSystem();
    }

    @AfterAll
    static void closeFileSystem() throws Exception {
        fileSystem.close();
    }

    @RegisterExtension
    Extension tempDirectory = TempDirectory.createInCustomDirectory(() ->
        Files.createDirectories(fileSystem.getPath("tmp")));

    @Test
    void test(@TempDir Path tempDir) {
        Path file = tempDir.resolve("test.txt");
        writeFile(file);
        assertExpectedFileContent(file);
    }
}
```

My problem is that the output directory is not deleted (and also the files contained in it, because my tests successfully write in it) by himself after the tests are done. Does this operation have to be handled manually in a `@AfterEach`/`@AfterAll` method ?

Thanks for your answers.

**Comment by nicolaiparlog** [comment]
Looking at [the code](https://github.com/junit-pioneer/junit-pioneer/blob/961177d5c4cd99f220870c96658f17a769137807/src/main/java/org/junitpioneer/jupiter/TempDirectory.java#L262-L288) it seems like files and the directory should be deleted once the test using it finishes.

@marcphilipp Any idea what is going on here?

**Comment by marcphilipp** [comment]
Given the following slightly modified version of your test class, both `test.txt` and the parent folder created by the `TempDirectory` extension are deleted.

```java

class MyTests {
    private static FileSystem fileSystem;

    @BeforeAll
    static void createFileSystem() {
        fileSystem = Jimfs.newFileSystem();
    }

    @AfterAll
    static void closeFileSystem() throws Exception {
        assertEquals(0, Files.list(fileSystem.getPath("tmp")).count());
        fileSystem.close();
    }

    @RegisterExtension
    Extension tempDirectory = TempDirectory.createInCustomDirectory(() ->
            Files.createDirectories(fileSystem.getPath("tmp")));

    @Test
    void test(@TempDir Path tempDir) throws IOException {
        Path file = tempDir.resolve("test.txt");
        Files.write(file, List.of("foo"));
        assertIterableEquals(List.of("foo"), Files.readAllLines(file));
    }
}
```

Could you please provide more details or, even better, a test that demonstrates the problem you're experiencing?

**Comment by Frontrider** [comment]
I can confirm, that it does not happen properly, if the test has failed. That is a sure point.

**Comment by marcphilipp** [comment]
@Frontrider I believe you but I cannot reproduce the issue. Could you please provide a minimal reproducible example?

**Comment by Frontrider** [comment]
Upon further scans, It might have to do something with directory permissions being funky. I think that, because those tests started to behave.

**Comment by marcphilipp** [comment]
Hmm, but `Files.delete()` should throw an `IOException` if it was unable to delete a file, shouldn't it?

https://github.com/junit-pioneer/junit-pioneer/blob/4ad92463dec8240bbf5f92d908c7915792fbf0f3/src/main/java/org/junitpioneer/jupiter/TempDirectory.java#L276-L286

**Comment by bes1002t** [comment]
This issue still persists with Junit 5.7.

Both, the directory and the file still exist after the test has finished. Additionally it would be good if @TempDir would not point to the project root, but a "tmp" directory in project root. Otherwhise issues like this could be a mess to cleanup.

`
    @TempDir File tmpDir;

    @Test
    public void testContextCreationSuccess() throws IOException {
        String configPath = "config_dir1";    
        File configDir = new File(tmpDir, configPath);
        configDir.mkdirs();

        File test = new File(tmpDir, "test.txt");
        test.createNewFile();
    }
`

**Comment by beatngu13** [comment]
@bes1002t from the [`TempDirectory` docs](https://junit-pioneer.org/docs/temp-directory):

>Since JUnit Jupiter 5.4, there's a [built-in `@TempDir` extension](https://junit.org/junit5/docs/current/user-guide/#writing-tests-built-in-extensions-TempDirectory). It doesn't support custom file systems, but other than that it's much better than this version, so *we removed the extension in JUnit Pioneer 1.0*. We plan to tackle this problem again in the future - see [issue #348](https://github.com/junit-pioneer/junit-pioneer/issues/348).

Please reach out to the [JUnit 5 team](https://github.com/junit-team/junit5) if you have issues with Jupiter.
