### ISSUE TITLE
Use Thread.interrupt from a Timer for tests which time out

### ISSUE THREAD

**Issue by seanf** [junit-pioneer/junit-pioneer#102]
To me, the most valuable thing about the JUnit 4's `@Test(timeout)` was the ability to stop runaway tests.

The current version of Vintage `@Test` doesn't have any ability to terminate a test, but even with JUnit 5's threading model, this can be done using a background Timer thread which interrupts the main test thread after timeout. This won't stop tests which are busy on the CPU, but should stop most tests which are blocked waiting for something.

Here's a bit of Kotlin code which shows the idea:
```kt
class TimeoutExtension: BeforeEachCallback, AfterEachCallback {
    companion object {
        private val timer = Timer(true)
    }

    private var testThread: Thread? = null
    private var timerTask: TimerTask? = null

    override fun beforeEach(context: ExtensionContext?) {
        testThread = Thread.currentThread()
        // TODO get the timeout (if any) from @Test annotation
        timerTask = timer.schedule(2_000) {
            testThread?.interrupt()
        }
    }

    override fun afterEach(context: ExtensionContext?) {
        testThread = null
        timerTask?.cancel()
        Thread.interrupted() // clear thread interrupt flag
    }
}
```

One potential drawback is that the test will probably fail with `InterruptedException` (unless caught by the test code) instead of the current `AssertionError` "Test '%s' was supposed to run no longer than %d ms but ran %d ms.". Did JUnit 4 make any promises about the type/message of the timeout exception?

If this change in exception for failing tests is a problem, the new interrupt behaviour could be attached to a new annotation, eg `@Timeout`.

**Comment by nicolaiparlog** [comment]
Hi @seanf, thanks for the idea. This looks like it could work! Would you mind adding this as a comment to #10, which already covers the time out.
