### ISSUE TITLE
Setting Default Locale and TimeZone for a test

### ISSUE THREAD

**Issue by britter** [junit-pioneer/junit-pioneer#103]
Hi,

I'm currently migrating the Apache Commons Lang project to JUnit 5. Since we have `Locale` and `TimeZone` dependent tests, we wrote a [custom JUnit 4 rule](https://github.com/apache/commons-lang/blob/master/src/test/java/org/apache/commons/lang3/test/SystemDefaultsSwitch.java) for that. Since I need to migrate this to JUnit 5 some time, I thought about bringing it here. The JUnit 4 API looks like this:

```java
   public class SystemDefaultsDependentTest {
  
        @Rule
       public SystemDefaultsSwitch locale = new SystemDefaultsSwitch();
  
        @Test
       public void testThatWillExecuteWithTheDefaultLocaleAndTimeZone() {
           // nothing to do, just implement the test
       }
  
        @Test
        @SystemDefaults(locale="zh_CN")
       public void testWithSimplifiedChinaDefaultLocale() {
           // Locale.getDefault() will return Locale.CHINA until the end of this test method
       }
  
        @Test
        @SystemDefaults(timezone="America/New_York")
       public void testWithNorthAmericaEasternTimeZone() {
           // TimeZone.getDefault() will equal TimeZone.getTimeZone("America/New_York") until the end of this method
       }
   }
```

Is this something you consider in scope of junit-pioneer? If that's the case I'm happy bring it here ported to JUnit 5.

**Comment by marcphilipp** [comment]
I think that would be very useful!

**Comment by sormuras** [comment]
_PPP_ 

Please Provide PR. ;-)

**Comment by britter** [comment]
okay, going to work on this!

**Comment by nicolaiparlog** [comment]
> Is this something you consider in scope of junit-pioneer?

Yes, absolutely! :1:
