### ISSUE TITLE
Obtain junitpioneer.org domain

### ISSUE THREAD

**Issue by smoyer64** [junit-pioneer/junit-pioneer#105]
As suggested in #24, we should move the also host the JUnit Pioneer project on the junitpioneer.org domain.

**Comment by smoyer64** [comment]
The domain has been purchased and the junitpioneer.org and www.junitpioneer.org records have been put into DNS (A and CNAME records respectively).  The junitpioneer.org host has been pointed to the existing website's IP address - 185.199.108.153. Where should the MX record be pointed?

**Comment by smoyer64** [comment]
Dig says that the new domain and host names are now being served by DNS.

**Comment by smoyer64** [comment]
I'm not so sure it was decided so much as assumed ... I really don't care about the groupId or web-site any more than I did about the package.  In any case, no slight was intended and I've updated #108 to point things "the other direction".

I should however state that I don't think we should be changing things beyond some point where users are relying on our stability - that point may have been reached when we published our first release version.

**Comment by nicolaiparlog** [comment]
Sorry for being testy. :relaxed: Yes, we should be stable, but in this instance that is not my argument. I just _really_ don't like "junitpioneer" and only accepted it as a package name because there was a somewhat technical argument against my preferred solution.

**Comment by smoyer64** [comment]
You're absolutely right to feel that way ... and I caved way too easily ;)  I've stated my preference for the dash (and given up on the package name).  As an aside, I'm copying you on an email for another potential JUnit Pioneer project.
