### ISSUE TITLE
Change project's groupId to org.junitpioneer

### ISSUE THREAD

**Issue by smoyer64** [junit-pioneer/junit-pioneer#106]
As suggested in #24, the JUnit Pioneer projects ``groupId`` should match the selected package name.  This requires the following tasks:

- [ ] Register the groupId with Sonatype
- [ ] Change the groupId in the pioneer project

**Comment by nicolaiparlog** [comment]
I'm opposed to changing the group ID. The package name is a mixture of technical limitations and feebleness - it should not impact other representations of the project.
