### ISSUE TITLE
Update GitHub.io configuration to include new host names

### ISSUE THREAD

**Issue by smoyer64** [junit-pioneer/junit-pioneer#107]
The JUnit Pioneer web-site should be available at the following sites:

- [ ] junit-pioneer.org (existing)
- [ ] www.junit-pioneer.org (existing)
- [ ] junitpioneer.org (new)
- [ ] www.junitpioneer.org (new)

**Comment by smoyer64** [comment]
Do we want that to be the "official" site?  I do that pretty easily but it seems that others think the domain name, groupId and package name should be consistent.  As noted in #108, there is an error in how www.junit-pioneer.org is configured.  I'll change that issue to make junit-pioneer.org the "official" site.

**Comment by smoyer64** [comment]
I should also have noted that GitHub.io seems to have some sort of virtual-hosting going on ... this issue was related to getting a 404 after the above domain names were in fact pointed at https://junit-pioneer.org

**Comment by nicolaiparlog** [comment]
Yes, I want _junit-pioneer_ as URL, group ID, StackOverflow tag, package name, whathaveyou because the project is called _JUnit Pioneer_. :smiley:

Re the 404, I know next to nothing about DNS, but all we need is a forward. The site can not appear as junit-pioneer.org and junitpioneer.org, so the latter needs to point to the former.

**Comment by nicolaiparlog** [comment]
Maybe we don't need guacamole.junit(-)pioneer.org to redirect. As long as the blank URLs and the www prefixes work, I'm happy.

**Comment by smoyer64** [comment]
> Maybe we don't need guacamole.junit(-)pioneer.org to redirect. As long as the blank URLs and the www prefixes work, I'm happy.

Agreed ... I just thought it would be cool ;)

I opened #109 to take care of this via redirects (www is automatic with GitHub pages ... but only for the single domain you can configure in the "Settings").
