### ISSUE TITLE
Fix DNS record for junitpioneer.org and www.junitpioneer.org

### ISSUE THREAD

**Issue by smoyer64** [junit-pioneer/junit-pioneer#108]
With the Google penalties that are incurred for duplicate content, only the "official" web-site location should be available via an A record in DNS.  Assuming the "official" web-site will become junit-pioneer.org, the following host names should be changed to CNAME records that point to the "official" web-site.

- [ ] www.junit-pioneer.org
- [ ] junitpioneer.org
- [ ] www.junitpioneer.org

As an aside, these existing records have a slight error as the www.junit-pioneer.org host name is using an A record in DNS and it points to a different IP address than junit-pioneer.org does.

Related to #105 and #107

**Comment by nicolaiparlog** [comment]
Oops, fixed. Now both junit-pioneer.org as well as *.junit-pioneer.org point to `185.199.108.153`.

**Comment by smoyer64** [comment]
and *.junit-pioneer.org is a CNAME?  (I just wildcarded *.junitpioneer.org too ... when the changes propagate even guacamole.junitpioneer.org will be valid!).  I'm still wondering what to do with the MX record.

**Comment by nicolaiparlog** [comment]
* No, `*` is not a CNAME, it's A. Is that correct? (Did I mention, I don't know anything DNS? :wink:)
* I expected guacamole.junit-pioneer.org to work, but it doesn't.
* I have not added an MX entry - I wouldn't know where to. Let's just hope, nobody send us mail. :wink:

**Comment by smoyer64** [comment]
It turns out that wildcarding CNAMES doesn't include the base domain and my DNS host (Linode) doesn't allow a CNAME for the primary domain ... I've replace it with an A record.

**Comment by smoyer64** [comment]
I think your wildcard should be a CNAME (alias) so that Google doesn't apply the duplicate content penalty.  I would hope that (eventually) we'd show up on the first page when someone searches for JUnit 5.

I'll have to research the MX record a bit ... this would all be much easier under the umbrella of an OSS organization.

**Comment by nicolaiparlog** [comment]
@smoyer64 At the moment, all *.junitpioneer.org and .junitpioneer.org lead to "404 - There isn't a GitHub Pages site here." Can you have a look at that?

**Comment by smoyer64** [comment]
Ugh ... how did I miss this thread?  I'll take a look at it over the weekend!

**Comment by Bukama** [comment]
@smoyer64 Hope you are allright in these current days. Did you have any time to check this? Thanks and greetz from Germany 👋

**Comment by Bukama** [comment]
We decided to move the issues related to the web site to the junit-pioneer.github.io repo. So I moved the issue there. Link is: https://github.com/junit-pioneer/junit-pioneer.github.io/issues/8
