### ISSUE TITLE
Create and host redirect pages for junitpioneer.org and www.junitpioneer.org

### ISSUE THREAD

**Issue by smoyer64** [junit-pioneer/junit-pioneer#109]
Supercedes #107

**Comment by Bukama** [comment]
@smoyer64 Can you provide an update to this issue?

**Comment by Bukama** [comment]
@smoyer64 Hope you are allright in these current days. Did you have any time to check this? Thanks and greetz from Germany 👋

**Comment by Bukama** [comment]
> We decided to move the issues related to the web site to the junit-pioneer.github.io repo. So I moved the issue there. Link is: [junit-pioneer/junit-pioneer.github.io#7](https://github.com/junit-pioneer/junit-pioneer.github.io/issues/7)
