### ISSUE TITLE
Document when to increment version

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-pioneer/junit-pioneer#113]
Every commit to master triggers a release with ShipKit (see #87). That means pull requests may have to increment the version in `version.properties`. Document when and how that has to happen.

First thoughts:

* features increment minor, e.g. `0.1` ~> `0.2`
* bug fixes and other such changes don't
* are there more changes?
* mention to update `version.properties`
* mention `@since`

What have I missed?

**Comment by nicolaiparlog** [comment]
But for the ones that do trigger a release, ShipKit increments the patch version right? (E.g. [26255a8](https://github.com/junit-pioneer/junit-pioneer/commit/26255a875ae7a3b26b97d4de8189b18756382ef4#diff-bc55b3eee52006c2f01f15eacc733517)) How do we tell it to bump minor instead?

**Comment by sormuras** [comment]
Copied from https://github.com/mockito/shipkit/blob/master/docs/features/version-bumps.md

_Every release, the version file is automatically updated with a new version number. The next version after "1.0.0" is "1.0.1", then "1.0.2", etc. If you need to release a specific version, like "1.1.0" or "2.0.0" just update `version.properties` file manually and include that in your pull request._

**Comment by sormuras** [comment]
In short: the value of `version=0.1.3` in `version.properties` is the next version to be published.

Change it to `0.2.0`.
