### ISSUE TITLE
Make DefaultLocale configurable via language tag

### ISSUE THREAD

**Issue by britter** [junit-pioneer/junit-pioneer#114]
As discussed in #104 it would be convenient if `@DefaultLocale` could also be specified using a language tag of the from "en_EN".

**Comment by sdavids** [comment]
My suggestion in #104 was using:

https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#forLanguageTag-java.lang.String-

`@DefaultLocale(languageTag = "en-US")`

Note it is "en-US" instead of "en_US".

```
jshell> Locale.US.equals(new Locale("en_US"))
$1 ==> false

jshell> Locale.US.equals(new Locale(Locale.US.toString()))
$2 ==> false

jshell> Locale.US.equals(Locale.forLanguageTag("en-US"))
$3 ==> true

jshell> Locale.US.equals(Locale.forLanguageTag(Locale.US.toLanguageTag()))
$3 ==> true
```

**Comment by sdavids** [comment]
Things to consider:

`@DefaultLocale(languageTag = "en-US", language = "lkt")` => en-US? lkt-US? Exception?
`@DefaultLocale(languageTag = "zh-Hant", variant = "TW")` => zh-Hant? zh-Hant-TW? Exception?

Once you use _languageTag_:
1. _language_, _country_, and _variant_ are ignored
2. _language_, _country_, and _variant_ overwrite the corresponding part of _languageTag_
3. _language_, _country_, and _variant_ if given throw an Exception

**Comment by sdavids** [comment]
_value_ could be used instead of _languageTag_:

`@DefaultLocale("zh-Hant-TW")`

**Comment by britter** [comment]
Using value for the language tag is a good idea.

I would say that using language tag is exclusive. So one has to choose between the language tag or the other fields. If both are configured a `ExtensionConfigurationException` should be thrown.

**Comment by nicolaiparlog** [comment]
@sdavids @britter I agree with what you two hashed out. :+1:
