### ISSUE TITLE
Build scans are not created by Travis build

### ISSUE THREAD

**Issue by britter** [junit-pioneer/junit-pioneer#118]
The command line for the travis build seems to be incorrect:

```shell
./gradlew --refresh-dependencies --stacktrace -Dscan clean build
```

The build produces:

```shell
Build scan cannot be created because the build scan plugin was not applied.
For more information on how to apply the build scan plugin, please visit https://gradle.com/scans/help/gradle-cli.
```

Accodring to the [Gradle Documentation](https://guides.gradle.org/creating-build-scans/#auto_apply_the_build_scan_plugin) the command line should contain `--scan` instead of `-Dscan`

**Comment by nicolaiparlog** [comment]
A quick local test resulted in Gradle asking my manual permission before continuing the build. I have to admit, I don't even know what the scan thingy does. I'm sure, @sormuras knows. :)

**Comment by sormuras** [comment]
Open https://gradle.com/s/se2dh2thsvtwo and you'll see.

With
```
buildScan {
	licenseAgreementUrl = 'https://gradle.com/terms-of-service'
	licenseAgree = 'yes'
}
```
included, it should work headless.

**Comment by nicolaiparlog** [comment]
Hm. I doubt that we need that, but since it's easy to configure, let's keep it. :wink:

**Comment by marcphilipp** [comment]
It's really convenient when the build fails or when you want to look into its performance. But I'm a bit biased... 😉
