### ISSUE TITLE
Gradle build doesn't work in Visual Studio Code (using Gradle plugin)

### ISSUE THREAD

**Issue by smoyer64** [junit-pioneer/junit-pioneer#127]

**Comment by aepfli** [comment]
okay i tried this, and i had no issues running the tests, are there any special tasks which are not running properly?

**Comment by aepfli** [comment]
![image](https://user-images.githubusercontent.com/9987394/75812935-61c18380-5d8f-11ea-887c-d8b5a5470067.png)

**Comment by aepfli** [comment]
![image](https://user-images.githubusercontent.com/9987394/76885918-4c188780-6880-11ea-9a9a-db9568f8f86c.png)
and a linux screen

**Comment by nicolaiparlog** [comment]
Thanks ton @aepfli for trying this out. Because this seems to be working, I will close the issue. If anybody has problems with Gradle / VS Code integration, let us know here.
