### ISSUE TITLE
Add declarative annotation for test authors to add test metadata for report entries

### ISSUE THREAD

**Issue by mkobit** [junit-pioneer/junit-pioneer#134]
Add in a simple way for test authors to declaratively add test metadata to test containers or methods.

basic example (needs better names in all places)

```java
@ReportEntry(reportKey = "myKey", reportValue = "someValue")
```

**Comment by nicolaiparlog** [comment]
I'm finally having a look at this, but I don't entirely get what this is about, @mkobit. Are you suggesting to publish the entries via [`TestReporter`](https://junit.org/junit5/docs/current/api/org/junit/jupiter/api/TestReporter.html)?

**Comment by Bukama** [comment]
I'm also not totally sure that @mkobit means, but If I then it would be a more general way like for example the #135

**Comment by nicolaiparlog** [comment]
I think I get it now. Just to clarify: Test methods can always declare a parameter of type `TestReporter` and Jupiter will inject an instance that the test can then use to publish messages.

By creating an annotation that essentially does the same thing, we get:

* a little less code (no parameter and no instance to call `publishEntry` on)
* more structured approach to publishing messages (on top of test method as opposed to "somewhere in the test")
* you can use this extension when creating your own annotations by meta-annotating it

I now wonder whether we should allow placeholders like `${methodName}` in the annotation that we then fill with specific values (like the test method's name). Maybe there's something of value to add there.

As I see it, the basic feature (grab key/value from annotation and publish it) is pretty simple and I agree that it can be implemented.

**Comment by Michael1993** [comment]
I could have something but I'd like some guidance:
- What should the annotation/params be called?
- Should it be repeatable (makes sense to me)?

**Comment by Bukama** [comment]
> I could have something but I'd like some guidance:
> 
> * What should the annotation/params be called?

When grab the example of `@ReportEntry` as the annotation name, then a simple `key/value` pair is fine for me as the context is clear enough by the annotation name.

> * Should it be repeatable (makes sense to me)?

Repeatable annotations make sense to me too

**Comment by Michael1993** [comment]
I'll open a pull request shortly, please review.

**Comment by nicolaiparlog** [comment]
I agree with @Bukama, your proposals `@ReportEntry` and repeatable make sense.
