### ISSUE TITLE
Deprecate TempDirectory extension once JUnit 5.4 is released

### ISSUE THREAD

**Issue by marcphilipp** [junit-pioneer/junit-pioneer#136]
By popular demand, the JUnit team has decided to include the `TempDirectory` in the `junit-jupiter-api` artifact in junit-team/junit5#1247. Thus, the `TempDirectory` extension in this project should be deprecated and point to the new location.

**Comment by smoyer64** [comment]
``TempDirectory`` has been released in the ``junit-jupiter-engine`` module ... I'll get a PR ready to take care of this issue.

**Comment by marcphilipp** [comment]
We decided to omit support for custom file systems in the "official" version of `@TempDir`. Thus, I think it's worthwhile to keep it in Pioneer but point users to the "official" one in Javadoc and on the website.

@nicolaiparlog @smoyer64 WDYT?

**Comment by nicolaiparlog** [comment]
Yeah, I think it shouldn't be deprecated. Instead the Javadoc and adoc should clarify where it's additional value lies, so it is clear why both are around.

**Comment by smoyer64** [comment]
Sounds good to me ... this version can become as feature-laden as we want ;)  Should a note be made in the official version's docs to look here if it's under-powered for your use case?

**Comment by marcphilipp** [comment]
> Should a note be made in the official version's docs to look here if it's under-powered for your use case?

I think that's a good idea.

**Comment by nicolaiparlog** [comment]
Yeah, free advertisement! 🥳

**Comment by marcphilipp** [comment]
Who said anything about "free"? 🤪

**Comment by nicolaiparlog** [comment]
@marcphilipp Since you know the limitations of Jupiter's `TempDirectory` best, can you create a PR describing Pioneer's additional features in the extension's Javadoc and the doc site? :blush:
