### ISSUE TITLE
Build on other Java versions

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-pioneer/junit-pioneer#143]
We're building on Oracle JDK 8 and Oracle JDK 9. Instead it should be (at least) OpenJDK 8 and 11 (plus maybe 13 and 14-EA). I assume fetching them from AdoptOpenJDK would be the canonical choice.

@sormuras This is your specialty, right? :yum: 

- [x] Use OpenJDK 8 and 11 on Travis CI (#144)
- [ ] Include 13 and current `-ea` version
- [ ] Update AppVeyor configuration or replace with Travis CI Windows variant

**Comment by sormuras** [comment]
_"Wait for it..."_

**Comment by sormuras** [comment]
Merge me! 🤗
