### ISSUE TITLE
DefaultLocale does not work with @Nested

### ISSUE THREAD

**Issue by almondtools** [junit-pioneer/junit-pioneer#146]
Following UnitTest will faile

```java
@DefaultLocale(language="en")
public class LocaleTest {

    @Test
    public void testUnNested() throws Exception {
        assertEquals(Locale.getDefault().getLanguage(),"en");
    }

    @Nested
    class testNested {

        @Test
        public void testNested() throws Exception {
            assertEquals(Locale.getDefault().getLanguage(),"en");
        }

    }

}
```

I suspect that not all nested classes are scanned for the annotation.

**Comment by nicolaiparlog** [comment]
Thanks, @almondtools for pointing this out. Does the test run and fail or (as it appears when I try to reproduce), do you get an `ExtensionConfigurationException` saying "The extension is active, but the corresponding annotation could not be found."?

@britter I get the mentioned exception and message when `DefaultLocaleExtension::readLocaleFromAnnotation` is called for the nested test method `testNested`. Can you take a look? If so, you can assign the issue to yourself. :)

**Comment by almondtools** [comment]
I confirm that the problem is the exception you mentioned.

**Comment by britter** [comment]
@nicolaiparlog October is pretty packed on my site. I don't see a chance to look at this before November.

**Comment by nicolaiparlog** [comment]
Thanks for letting me know and no problem. I'll see whether I can take a look at it. May be worth checking in in November to see whether I made progress. :wink:

**Comment by simonenkoi** [comment]
@nicolaiparlog are there any updates on this one? I can try to fix it if there are no objections

**Comment by britter** [comment]
I don't see myself doing this, so if you have the time, go ahead!
