### ISSUE TITLE
CSS on notice-blocks are broken/overlapping

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#157]
On the [documentation page](https://junit-pioneer.org/docs/temp-directory/) of the `TempDirectory Extension` you see that the CSS of the noctice-blocks are broken / overlapping

See the page / this screenshot

[![Bild pioneercssbrokenquk9g.png auf abload.de](https://abload.de/thumb/pioneercssbrokenquk9g.png)](https://abload.de/image.php?img=pioneercssbrokenquk9g.png)

**Comment by Bukama** [comment]
Maybe a bit more. The table-col is of class "icon" and is quite small. But the "huge" text (Note) is too large. In my opinion it's strange that the class is called "icon" but there's text in it - maybe there should be an image (like a pencil to visualize a note) and the text "Note"should be the alt-text of it?

**Comment by nicolaiparlog** [comment]
Thanks for reporting, fixed by junit-pioneer/junit-pioneer.github.io@16e0c91.
