### ISSUE TITLE
Show exception stacktrace on the last failed test iteration 

### ISSUE THREAD

**Issue by ggralak** [junit-pioneer/junit-pioneer#160]
Hi All!

First of all thanks for the junit-pioneer! It's a really helpful library for us.

Unfortunately we have a problem with `@RepeatFailedTest` annotation.

In Jenkins when test fails only the last test run iteration's `AssertionError` is being shown. Unfortunately that `AssertionError` doesn't contain exception stacktrace if such happened. So every time a test fails in Jenkins we have to go to full logs to see actual stacktrace.

I can see in `FailedTestRepeater.failed(Throwable exception)` that exception is intentionally not passed to `AssertionError` on the last test run iteration. 

Two questions I have to you guys:
1. Do you know what's the reason for this behaviour?
2. Would it be possible to pass the exception to AssertError for the last test run iteration (`if (allRepetitionsFailed)`)?

Here is the method I'm talking about:
```java
 void failed(Throwable exception) throws Throwable {
            exceptionsSoFar++;

            boolean allRepetitionsFailed = exceptionsSoFar == maxRepetitions;
            if (allRepetitionsFailed)
                throw new AssertionError(
                        format("Test execution #%d (of up to %d) failed ~> test fails", exceptionsSoFar, maxRepetitions));
            else
                throw new TestAbortedException(
                        format("Test execution #%d (of up to %d) failed ~> will retry...", exceptionsSoFar, maxRepetitions),
                        exception);
        }
```

All the best!
Grzegorz

**Comment by nicolaiparlog** [comment]
Seems to be a quite glaring oversight on my part. I opened #166 - maybe someone else can see a reason not to pass on the exception.

**Comment by nicolaiparlog** [comment]
And thank you very much for the kind words, they are highly appreciated.
