### ISSUE TITLE
Require configuration failiure tests?

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-pioneer/junit-pioneer#164]
Some extensions have tests that check whether broken configurations are handled as expected (e.g. `DefaultLocaleTests`). Should all extensions do that? (E.g. `DefaulTimeZoneTests`, which doesn't at the moment.)

**Comment by Bukama** [comment]
I my opinion it's important that a functioniality checks all of its parts. That's why I tried to check the annotation when I was trying to create the `@Issue` annotation. So I vote for _Yes they should do it_

**Comment by Bukama** [comment]
As nobody argues against this I remove the `in-discussion` label and set `up for grabs`.

**Comment by Bukama** [comment]
Note: Aside from the opened PR in #272 I would like to create a list of all extension which lack of such tests, so we have an overview before starting (and maybe doing double work).

As I don't have much time at the moment, feel free to have a look at the code and add such a list here - thank you.

**Comment by Bukama** [comment]
If I have not overseen anything this should be the extensions which as of today (don't) check if the configuration is correct:

Checks config:
* RangeSourceArgumentsProvider
* DefaultLocaleExtension
* EnvironmentVariableExtension
* IssueExtension
* RepeatFailedTestExtension
* ReportEntryExtension
* StdIOExtension
* SystemPropertyExtension
* TempDirectoryExtension

Does not check / do they need to?

* DefaultTimeZoneExtension
* TimeoutExtension


@Michael1993 , @beatngu13 @NPException Did I oversee anything?

**Comment by Bukama** [comment]
> Does not check / do they need to?
> 
> * DefaultTimeZoneExtension
> * TimeoutExtension

For the `DefaultTimeZoneExtension´ @Michael1993 has opened PR #272 .

The other is still up for grabs.

**Comment by nicolaiparlog** [comment]
Closed by #272 and #280.
