### ISSUE TITLE
Should we always use AssertJ assertions?

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-pioneer/junit-pioneer#165]
Some tests use Jupiter's annotations (48 uses at the moment), some use AssertJ (123 uses). Should we always use AssertJ?

My argument in favor:

* more readable assertions and error messages
* uniform code base
* no discussion which one is better in specific cases :blush:

**Comment by sormuras** [comment]
> [...] Pioneer's annotations [...]

Did you mean: "Jupiter assertions"?

> My argument in favor: [...]

+3

**Comment by nicolaiparlog** [comment]
> Did you mean: "Jupiter assertions"?

Yes, totally. Updates the description to prevent confusion.

**Comment by Bukama** [comment]
As written in chat: I vote for using AssertJ everywhere!

**Comment by nicolaiparlog** [comment]
Since everybody who shared their opinion was in favor of AssertJ over Jupiter's assertions, it is hereby decreed that only AssertJ shall be used to assert the code's holiness.
