### ISSUE TITLE
GitHub release provider not triggered

### ISSUE THREAD

**Issue by beatngu13** [junit-pioneer/junit-pioneer#171]
Remeber #151? We introduced this release provider to a) properly mark releases on the release page (which suddenly was managed by Shipkit) and b) to add additional artifacts (JARs) to the release.

The problem is that the GitHub release provider, as we configured it, is [only triggered on tags](https://github.com/junit-pioneer/junit-pioneer/blob/master/.travis.yml#L43), which is typical for releases. But looks like Shipkit does a CI skip (see e.g. [here](https://github.com/junit-pioneer/junit-pioneer/commit/bc8c078204ed1f670fcf2fdd1ad8d3db568bbc1b)), so the corresponding Travis build never triggers the release provider.

What shall we do?

1. Do not skip CI on releases?
2. Remove the release provider?
3. … ?

**Comment by nicolaiparlog** [comment]
This seems complicated and I don't wanna think about it right now. :blush: I will take a look at some other time. Thanks for reporting, though! (No irony, I mean it.)

**Comment by beatngu13** [comment]
Just let me know what you prefer (prevent Shipkit from skipping tagged builds, remove the release provider from the Travis CI config, …) and I will take a look.

**Comment by Bukama** [comment]
I think this ticket will be obsolet as we decided to move to Github actions (see #193 and #199 ).

@aepfli / @nicolaiparlog What do you think?

**Comment by nicolaiparlog** [comment]
Agreed.
