### ISSUE TITLE
Reduce duplication

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-pioneer/junit-pioneer#180]
Once #173, #174, #187 are merged, there's some duplication in the code that we could remove it seems helpful to do that:

* `EnvironmentVariableExtension` and `SystemPropertyExtension` are basically identical
* `findRepeatableAnnotations` should be replaceable by the new method in `Util`

More?

**Comment by beatngu13** [comment]
I can have a look at this once the PRs have been merged.

**Comment by nicolaiparlog** [comment]
I added #187 to the list of things to fix first and assigned the issue to you, @beatngu13, to start working on it afterwards.

**Comment by Bukama** [comment]
blocked by #174

**Comment by nicolaiparlog** [comment]
I just saw this in the `EnvironmentVariableExtension`:

```java
@Override
public void afterEach(ExtensionContext context) {
	boolean present = PioneerAnnotationUtils
			.isAnyAnnotationPresent(context, ClearEnvironmentVariable.class, ClearEnvironmentVariables.class,
				SetEnvironmentVariable.class, SetEnvironmentVariables.class);
	if (present) {
		restoreOriginalEnvironmentVariables(context);
	}
}
```

It seems weird to me to check the presence on the container annotations. Can you check whether this makes sense? (Also present in `SystemEnvironmentExtension`.)

**Comment by Bukama** [comment]
#174 was merged, so I removed the blocked label

**Comment by beatngu13** [comment]
I have two weeks off now, so I will likely soon start working on this.

Is there something else that should be discussed beforehand (we can also arrange a call for this)?

**Comment by Bukama** [comment]
> I have two weeks off now, so I will likely soon start working on this.
> 
> Is there something else that should be discussed beforehand (we can also arrange a call for this)?

Personally I don't see something. As we already have replaced all calls of the `findXXXAnnotations` calls in #187 this issue comes down to check if `EnvironmentVariableExtension` and `SystemPropertyExtension` are identical and merge them into one.

**Comment by beatngu13** [comment]
@Bukama thx for the summary, will take care. ✌️

**Comment by Bukama** [comment]
As I wasn't sure if this bishue still has some use I looked at both extensions and their tests (current master as of 2020-04-26 13:40):

Inside the test there is nothing which can be reduced in my opinion. All overhead was removed / handled by the refactoring while introducing the [Pioneer TestkitEngine](https://github.com/junit-pioneer/junit-pioneer/pull/218).

For the extensions: As we know both extensions are very similiar, one handling `SystemEnvironmentEntries` while the other does the same with `SystemPropertyEntries`. So it's in its nature that they both do the same checks / actions but use specific methods like `System.getenv()` or `System.getProperty(property)`. 

I personally don't see many things we can improve:


* The two methods `preventClearAndSetSameEnvironmentVariables` and `preventClearAndSetSameSystemProperties` are identically except the thrown message. This could be extracted into a more general method inside `PioneerUtils` which compared to collections for same values and then throws a generic (read: provided as a parameter) message.
* Many methods have a `throws Exception`, but do not throw such
* Rename "EnvironmentExtension" (and its utils class) to "SystemEnvironmentExtension" as it handels `SystemEnvironmentEntries` and would be more align with `SystemPropertyExtension`

@beatngu13 Do you spot anything else?

**Comment by beatngu13** [comment]
@Bukama maybe a common base class makes sense, but I have to further investigate this (and personally I prefer KISS over DRY). Anyways, will have a closer look on Thursday and then update the issue accordingly.

**Comment by beatngu13** [comment]
@Bukama just working through this, but regarding:

>Rename "EnvironmentExtension" (and its utils class) to "SystemEnvironmentExtension" as it handels `SystemEnvironmentEntries` and would be more align with `SystemPropertyExtension`

Not sure about the "System" prefix. If we adapt all environment variable classes, it would break public API. If we only change the non-public parts, it would be inconsistent. So, I would rather leave it as it is.

What do you think?

**Comment by Bukama** [comment]
> @Bukama just working through this, but regarding:
> 
> > Rename "EnvironmentExtension" (and its utils class) to "SystemEnvironmentExtension" as it handels `SystemEnvironmentEntries` and would be more align with `SystemPropertyExtension`
> 
> Not sure about the "System" prefix. If we adapt all environment variable classes, it would break public API. If we only change the non-public parts, it would be inconsistent. So, I would rather leave it as it is.
> 
> What do you think?

I know that it's an API change, but as for me it okay in our steps to clean up / align (and the docs would be updated too, so its documented). Don't know what the others think about it.

**Comment by Bukama** [comment]
> we can or should not break public api, we need to deprecate it and provide a timeframe till which version this might be removed. Simply breaking the api is not a good idea.

Good idea. Then I suggest to add a new, proper named annotation. Renaming the extension and the util class is no public API anyway, so there's no problem to rename them anyway.

**Comment by beatngu13** [comment]
> I just saw this in the `EnvironmentVariableExtension`:
> 
> ```java
> @Override
> public void afterEach(ExtensionContext context) {
> 	boolean present = PioneerAnnotationUtils
> 			.isAnyAnnotationPresent(context, ClearEnvironmentVariable.class, ClearEnvironmentVariables.class,
> 				SetEnvironmentVariable.class, SetEnvironmentVariables.class);
> 	if (present) {
> 		restoreOriginalEnvironmentVariables(context);
> 	}
> }
> ```
> 
> It seems weird to me to check the presence on the container annotations. Can you check whether this makes sense? (Also present in `SystemPropertyExtension`.)

@nicolaiparlog this seems to be necessary since `isAnyAnnotationPresent` internally uses `findClosestEnclosingAnnotation` and not `findClosestEnclosingRepeatableAnnotations`. However, I switched to `isAnyRepeatableAnnotationPresent`, now it is possible to omit the containers.

**Comment by Bukama** [comment]
> > I just saw this in the `EnvironmentVariableExtension`:
> > ```java
> > @Override
> > public void afterEach(ExtensionContext context) {
> > 	boolean present = PioneerAnnotationUtils
> > 			.isAnyAnnotationPresent(context, ClearEnvironmentVariable.class, ClearEnvironmentVariables.class,
> > 				SetEnvironmentVariable.class, SetEnvironmentVariables.class);
> > 	if (present) {
> > 		restoreOriginalEnvironmentVariables(context);
> > 	}
> > }
> > ```
> > 
> > 
> > It seems weird to me to check the presence on the container annotations. Can you check whether this makes sense? (Also present in `SystemPropertyExtension`.)
> 
> @nicolaiparlog this seems to be necessary since `isAnyAnnotationPresent` internally uses `findClosestEnclosingAnnotation` and not `findClosestEnclosingRepeatableAnnotations`. However, I switched to `isAnyRepeatableAnnotationPresent`, now it is possible to omit the containers.

May I ask to discuss this in #222 and focus in this PR on the duplication reduction? 🙏
