### ISSUE TITLE
Tests for the Util class

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#186]
On the current stream we are debugging the `Util` class as the method which is described to find an annotation on a test method or on a meta level doesn't finds annotations on class level.

e.g. The `findAnnotation` finds annotations on nested classes, but not above of them. (Current commit should be https://github.com/junit-pioneer/junit-pioneer/commit/595298c73ee23b22b08be835f341c770d089cad2 )

We came to the conclusion that there should be tests for the `Util` class itselfs so the methods do really what the descriptions says and can be used in a save (read: correct) way.

One thing also is needed is testing deeeeeeply nested classes.

**Comment by nicolaiparlog** [comment]
#187 can address this (doesn't yet, though)

**Comment by nicolaiparlog** [comment]
Closed by #187.
