### ISSUE TITLE
Honor behind-the-scenes-contributors

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-pioneer/junit-pioneer#188]
So many have been helping out with JUnitPioneer, some without ever appearing in the commits. @Bukama, @aepfli, @Michael1993 and a few more. This project would not be where it is today (humble as that is) without their support and it's time I publicly recognized that and put their names and contributions somewhere visible.

Do that.

**Comment by nicolaiparlog** [comment]
#226 will turn some recent contributors into maintainers, which is a big part of honoring their contributions. Beyond that, I think they should be mentioned elsewhere, though. Also, beyond these new maintainers there are (and hopefull will be) people who contribute and deserve praise.

Effectively, everybody already gets some exposure because the release notes list everybody who commits, but the thing is that nobody sees those (yet; see #97). And it's not really readable either. Instead I propose to add a section to the README, where "noteworthy" contributions get added. What's noteworthy?

* being a maintainer
* initial contribution of a new feature
* continuous small or occasional large contributions, e.g. to code, documentation, build infrastructure, etc.
* continuous participation in issue/PR/Twitch discussions

I would start a new section for each year where every person with a "noteworthy" contribution is listed once (in lexicographic order) with their two most relevant contribution and possibly an "and more".

In the same section, there would be subsection for maintainers, where each gets a few lines.

**Comment by aepfli** [comment]
Actually every committer is in the pom file generated by shipkit ;) - just as a side note

**Comment by nicolaiparlog** [comment]
Ha, indeed. TIL.

**Comment by aepfli** [comment]
I like the idea of such a list. For me such lists just always provide one issue, the maintaining part. I think we should try this, and put effort into this.

There is also something additional, which we could do, as a thank you. I know from one project which actually sends sometimes chocolate or other sweets and some swag as a thank you. Which might be also something we could think of. ;)

But mentioning in a separate section within the repo is for sure a good idea which we definitely should do

**Comment by nicolaiparlog** [comment]
Sending chocolate is a legal nightmare (addresses, GDPR). 😱 But I like the idea and we can consider it for our 1.0 release.

That aside, with maintainers and contributors listed in README and pom, I consider this done once #238 is merged.

**Comment by nicolaiparlog** [comment]
@beatngu13: A while ago, we created the team @junit-pioneer/pioneer-10 so regular contributors could tag issues, work with PRs, etc. ([triage permissions](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization)). When creating the list of contributions, I noticed that you're up there as well. If you want, I'd happily invite you.

**Comment by beatngu13** [comment]
@nicolaiparlog although I don't have that much time and #180 is still on my to-do list, I'd be super happy to help where I can. So yes, please add me to that team. 🙏

**Comment by Bukama** [comment]
> Actually every committer is in the pom file generated by shipkit ;) - just as a side note

@aepfli  Which pom file? I don't see one. And I don't see where [the list of developers on Maven central](https://mvnrepository.com/artifact/org.junit-pioneer/junit-pioneer/0.5.6) is generated either. The Text "Core developer" is nowhere in the projects file 🤷‍♂️

**Comment by aepfli** [comment]
> > Actually every committer is in the pom file generated by shipkit ;) - just as a side note
> 
> @aepfli Which pom file? I don't see one. And I don't see where [the list of developers on Maven central](https://mvnrepository.com/artifact/org.junit-pioneer/junit-pioneer/0.5.6) is generated either. The Text "Core developer" is nowhere in the projects file

https://dl.bintray.com/junit-pioneer/junit-pioneer/org/junit-pioneer/junit-pioneer/0.5.6/:junit-pioneer-0.5.6.pom

**Comment by nicolaiparlog** [comment]
That's Shipkit's doing - it parses Git authors.

**Comment by nicolaiparlog** [comment]
> @nicolaiparlog although I don't have that much time and #180 is still on my to-do list, I'd be super happy to help where I can. So yes, please add me to that team. pray

Great, just invited you.

Re #180, I'm not sure how much there is to do anymore. At least the entire annotation duplication got removed when we refactored that.

**Comment by nicolaiparlog** [comment]
I think this is done now. If anybody doesn't feel sufficiently honored, let me know. :wink:
