### ISSUE TITLE
Config files are not discovered by tools

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#190]
I just updated IntelliJ to the current Community 2020.1 BETA using the IntelliJ toolbox. When I tried to build pioneer I saw that IntelliJ was installing `Gradle 6.1` and the build failed because the `com.gradle.build-scan` plugins version (`2.4.2`) is not compatible to `Gradle 6.x` (for this version the plugin must be switched to https://docs.gradle.com/enterprise/gradle-plugin/ ).

While analyzing the problem together with @nicolaiparlog  and @aepfli 
 we found out that IntelliJ doesn't recognize the `gradle-wrapper.properties` inside the `.infra/gradle` folder as the following images shows.

![gradlewtf](https://user-images.githubusercontent.com/4354359/77247810-d4a67780-6c34-11ea-8c89-7a509f9383fd.png)

So it used the default `Gradle` installation I installed manually some months ago and which was a `5.x`. With the automatically installed and configured `6.1` version the build broke. To get pioneer build again I had to switch the gradle installation in IntelliJ settings to the specific `5.x` one.

While chatting we remembered a similar issue (#127) with Visual Studio Code.

So we coincided to open an issue to collect further examples and to discuss the current config file locations inside `.infra`. As of now they are in there to keep the root folder of the project clean and gather all infrastructure thigs inside a specific folder. But as shown this is ot the expected default folder for some IDE so the build may get broken if the by default installed tool versions are not fitting to pioneer.

Options we see so far:
* Move config files to expected default positions (and mess up the root folder)
* Update documentation to point contributers to the situation

**Comment by Bukama** [comment]
Just saw #96 in which was also talked about the as-is structure of `.infra`

**Comment by aepfli** [comment]
I add my 2 cents here, as i can understand the decision to clean the root folder, as nobody wants to have a lot of clutter in there. But on the otherside, everyone is expecting that the tools work easily, and with little to none configuration. And that is imho the biggest problem regarding gradle.

Everyone expects the gradle wrapper to be under gradle/wrapper as this is normally the default. Which is so far fine, but not if you want to have a cleaner folder structure. But if the projects wants to get people working on the project, the initial steps should be as small as possible. Contributors will actually not expect this to be a problem, and they will most likely not read or not carefully enough read the documentation at the beginning. Hence that i would suggest to move the gradle wrapper out of the infra folder. I think the rest is totally fine within the infra folder, and it leads to a lot of configuration stored within this folder, to not clutter up the project root. But gradle will be a big issue after all.

**Comment by Bukama** [comment]
Just saw that other projects also don't have the file on root level, e.g. [hibernate-orm](https://github.com/hibernate/hibernate-orm/tree/master/gradle/wrapper)

**Comment by nicolaiparlog** [comment]
@Bukama That's the default place as well (`gradle/wrapper`).

**Comment by nicolaiparlog** [comment]
Ok, through clenched teeth I agree that inconviniencing tools THAT DON'T PROCESS `build.gradle` (:point_down: ; excuse the yelling) is not the best thing to do. Let's move the wrapper into its default place.

```
tasks.wrapper {
    jarFile = file(".infra/gradle/gradle-wrapper.jar")
}
```

The other three tools in `.infra` seem to work fine, though, so I hope we can leave it there. Please? 🥺

**Comment by nicolaiparlog** [comment]
Who's up for playing with the wrapper? :grin:

**Comment by Bukama** [comment]
> Who's up for playing with the wrapper? 😁

I'll try it.
