### ISSUE TITLE
Extend contributor docs about writing 1sentence per line

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#191]
A note should be added to the contributors documentation that there should only be one sentence per line in the ascii docs. Background is to ensure the readbilty of the code to ot wrapping sentences manually.  This pattern should be applied to short sentences as well - even if two or three would fit a line.

(From stream on 2020-03-26)

**Comment by sormuras** [comment]
![image](https://user-images.githubusercontent.com/2319838/77693409-926c9580-6fa8-11ea-92ef-92c9aedae0f9.png)

**Comment by Bukama** [comment]
I'll add one
