### ISSUE TITLE
Move from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-pioneer/junit-pioneer#192]
GitHub Actions seem the be hot new thing and everybody's using it, including JUnit 5 itself, so let's do that, too. (Yes, that's all the reason I need to give it a try. :) )

**Comment by nicolaiparlog** [comment]
@aepfli started working on this is #185.

**Comment by Bukama** [comment]
Just wanted to add: We already discussed that on Discord and in chat. See also comments on #181 and #185

**Comment by aepfli** [comment]
I created #199 and #201 as the next steps for this ticket. We should keep this ticket also for the cleanup, so we can than remove travis.yml when all the others are finished

**Comment by Bukama** [comment]
Don't forget #28 (it was already linked to #50)

**Comment by aepfli** [comment]
uh 28 is done with sonarcloud, when it finally works :)

**Comment by nicolaiparlog** [comment]
As pointed out by #208, we also need to update the badges in the README once we don't build on Travis anymore.

**Comment by nicolaiparlog** [comment]
It looks like there are two more things to do before we can remove Travis entirely:

* trigger ShipKit via GitHub Actions - see #199 (we can ignore the discussion around ShipKit in #192 for now)
* trigger site built via GitHub Actions - see junit-pioneer/junit-pioneer.github.io#5

Since the site built is currently broken anyways, we're not loosing functionality if we move to GitHub Actions without reimplementing it. I.e. once #199 is merged, we can do the necessary clean-up mentioned above and then remove Travis entirely.

**Comment by nicolaiparlog** [comment]
Closed by 80b3e45
