### ISSUE TITLE
Update to recent gradle version

### ISSUE THREAD

**Issue by aepfli** [junit-pioneer/junit-pioneer#197]
As we want to upgrade to java 14 in #196 we need to also upgrade to at least gradle 6.3. As this is the release with official Java 14 support.

This ticket blocks #196

**Comment by sormuras** [comment]
JUnit 5 already is running on [Gradle 6.3](https://github.com/junit-team/junit5/commit/f87314fecbaf0220525c88e762bfe7f9c4af5e0d).

**Comment by aepfli** [comment]
resolved togehter with #196
