### ISSUE TITLE
Github Actions for Deployments

### ISSUE THREAD

**Issue by aepfli** [junit-pioneer/junit-pioneer#199]
JUnit Pioneer currently still relies on travis for the releasing process.

Goal of this ticket is to also migrate this deployment and releaseing process to GitHub Actions

We want to migrate following code to GitHub Actions, maybe in an own build just for master, or as a sub step of the existing  #actions.
https://github.com/junit-pioneer/junit-pioneer/blob/4f3647f88bb3131b19fa77efaac1eb2edf11962c/.travis.yml#L29-L41

This issue is part of #192
and relates to #193

**Comment by nicolaiparlog** [comment]
This effectively removes Shipkit, right? If so, can we discuss this in #193 first?

**Comment by aepfli** [comment]
question is what we favor first. Evaluating shipkit or moving the Build infrastructure to github actions :) - both can be done at the same time. and i see the testing part as the more crucial one, which is taking more time than actually implementing it :)

**Comment by aepfli** [comment]
i opened the Pull Request, for using this with shipkit, and so far i fell in love with Shipkit and how they use releasing. We just had a lot of additional steps in between.

There is just one down side as described in #171 - if we want to add our jars to the release on github releases, we need to put in manual effort. I skipped that for now, because this was never really working so we do not lose functionality, and it seems like this is nothing which shipkit provides as functionality. Neither Shipkit itself, nor PowerMock or Mockito are uploading jars to the release page of github. But they are linking it anyways in the release text.
