### ISSUE TITLE
Generate additional Organization team with some additional rights

### ISSUE THREAD

**Issue by aepfli** [junit-pioneer/junit-pioneer#202]
@Bukama and others are currently creating a lot of issues and pull requests and they are investing time into this project.
There is a lot of information that could actually be supplied - like labels etc. As they are not part of the JUnit Pioneer team, they can not do this. 

Sidenote: i also count me to those "others" who would love to do more.

We do understand that we might not be suitable currently for full maintainer rights, but we would highly appreciate if we could at least do a little bit more issue related work, like labeling, assigning etc. It will help us, and it will also be a support for you @nicolaiparlog with maintaining the issues. 

I created this issue to start a discussion and to get opinions on that. This could be also a way for #188 to be part of the junit-pioneer organization :)

**Comment by nicolaiparlog** [comment]
Great idea and a good way to start working on #188. It wasn't immediately obvious to me how this works, but I created a team and invited you, @aepfli, so we can try out how this works. Once we have, I'll invite others.

**Comment by nicolaiparlog** [comment]
The team has triage rights (let's see how far that gets us) and I just invited @Bukama and @Michael1993. If the permissions don't suffice or other people should be invited, open a new issue.
