### ISSUE TITLE
Document underlying tools and processes for new contributors

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-pioneer/junit-pioneer#205]
Starting to contribute to a new project can appear daunting, particularly if the developer does yet know all used tools and the default processes (e.g. fork ~> clone ~> branch ~> code ~> commit ~> request pull). This becomes apparent when looking at `CONTRIBUTING.md`, which explains project-specifics, but not the underlying technologies.

Can we improve the situation, so new developers have an easier time becoming contributors?

(This issue was spawned to discuss #204.)

**Comment by nicolaiparlog** [comment]
I like the goal of documenting this process, particularly for newbies and think the text in #204 does a good job at it. It's just not the right place.

Years ago, I had the idea to create an article series on contributing to and starting open source project. Maybe we should revive it and, because I'm notoriously unreliable on delivering on my ideas, you could contribute. What do you think?

**Comment by Bukama** [comment]
I understand and part your point. As I like clear and divided structures I wrote the documentation as an appendix. This way the needed knowledge for new contributors is in the place with the project they want to start working on.

I see the "danger" that new contributors stop their try to add value to the project because they don't know how to start and won't google for it. Maybe I'm worrying too much.

**Comment by nicolaiparlog** [comment]
I should have mentioned that once we publish those tutorials somewhere, we should add a very obvious link to `CONTRIBUTING.md` saying something like "IF YOU'RE UNSURE ABOUT WHAT ANY OF THIS MEANS, READ THIS HANDY GIT(HUB) GUIDE WE WROTE FOR YOU" (maybe fewer caps).

**Comment by Michael1993** [comment]
What about [this project](https://github.com/verhas/openregime)?

**Comment by nicolaiparlog** [comment]
Another place to publish such content would be a personal blog or we create on junit-pioneer.org (as we're using Jekyll, that should be fairly simple).

**Comment by Bukama** [comment]
> I should have mentioned that once we publish those tutorials somewhere, we should add a very obvious link to `CONTRIBUTING.md` saying something like "IF YOU'RE UNSURE ABOUT WHAT ANY OF THIS MEANS, READ THIS HANDY GIT(HUB) GUIDE WE WROTE FOR YOU" (maybe fewer caps).

> Another place to publish such content would be a personal blog or we create on junit-pioneer.org (as we're using Jekyll, that should be fairly simple).

@nicolaiparlog Nicolai and I talked about his comment from last week and the whole topic itself and we both agree that it's nice to provide links to the basic stuff. But as we don't want to duplicate external tool documentation and we only want describe project related things (like our explicit branch strategy) those should not be in our docs. 

Therefore I updated #204 and only put a short paragraph with a link to [GitHub help](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks) where all the things I had written are described anyway.
