### ISSUE TITLE
Update Badges in readme

### ISSUE THREAD

**Issue by aepfli** [junit-pioneer/junit-pioneer#208]
as we are now also using SonarCloud.io and GitHub Actions, we might want to update the badges in the head of the ReadMe.

SonarCloud badge for master:
 [![Quality Gate Status](https://sonarcloud.io/api/project_badges/measure?project=junit-pioneer_junit-pioneer&metric=alert_status)](https://sonarcloud.io/dashboard?id=junit-pioneer_junit-pioneer)

GitHub action badge for master:
![JUnit Pioneer Flow](https://github.com/junit-pioneer/junit-pioneer/workflows/JUnit%20Pioneer%20Flow/badge.svg)

Based on the GitHub Action badge, we might also want to rethink our name of the action

**Comment by Bukama** [comment]
I think we should add the sonarcloud build after we have some experience with it and analysed the issues from there.

As said today in voice chat I'll have a look at the sonarcloud analysis when the build errors are fixed and build process is stable again.

For the pioneer thing: Do we even need it? I mean when we release something it was successfully build?

**Comment by nicolaiparlog** [comment]
I'm a little lost in this rush of build/CI related issues/changes that are happening right now. Note: Next time, we need a rough overview over the goals and possible steps, so we have a simple way to track where we're at and where we're going.

On to the topic: It seems to me we need to replace the Travis badge in the issue/PR that replaces the rest of Travis with GitHub Actions. Is there an issue for that? If yes, this should be added as a note there; if not, we need to create one and then add this as a note there. :wink: 

Once that's done, let's close this issue.

**Comment by nicolaiparlog** [comment]
Oh, found it, it's #192.

**Comment by aepfli** [comment]
sorry i am a little of a jira guy, and i love to create more granular tasks, which normally reference other issues. yes, this is not working good with github, at least it seems so.
