### ISSUE TITLE
Upgrade JUnit version to 5.4.2

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#209]
We still use `JUnit Jupiter 5.3.x`. Some days ago `5.6.1` was released.

To be able to resolve #6 we need to upgrade to at least `5.4.2`, but I suggest to upgrade to the lastest available version.

`Jupiter 5.6.1 | Vintage 5.6.1 | Platform | 1.6.1 ` (as of 2020-03-29 16:20 CEST)

**Comment by nicolaiparlog** [comment]
Unless there's a specific need for 5.6.1, we should go with 5.4.2. As [the README says](https://github.com/junit-pioneer/junit-pioneer/blob/master/README.md#dependencies):

> Pioneer always depends on the lowest JUnit 5 version that supports its feature set

The intention is not to force users into a higher version than we require.
