### ISSUE TITLE
Switch from Continuous Deployment to Continuous Delivery

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#211]
At the moment we create releases every time we merge. This can be stoped by adding `ci skip-release` to the merge message.

But it already happend, that this was forgotten and a release was made unitended (e.g. the release of `0.5.5` about one hour ago).

So we should think about change from Continuous Deployment (push to PROD automatically) to Continuous Delivery (push to prod manually). Maybe by turn around the functionality that you have to add something like `ci do-release` to a commit message.

@aepfli noticed that this is an shitkit issue, therefore connected to #193

**Comment by nicolaiparlog** [comment]
I don't this can be discussed separately of the ShipKit evaluation in #193 and should hence be a part of it. You bring up a good point, though, and I added it to the list of grievances.
