### ISSUE TITLE
Should SystemPropertyExtension use closest or enclosing annotations

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#222]
In stream and while discussing (the already merged) #187 we were thinking about following thing:

At the moment the `SystemPropertyExtension` only looks for the `closest` annotation. When @nicolaiparlog was doing #187 he kept it that way to keep the tests passing, but we both asked ourself if that's the correct way the extension should work or if it should also take the `enclosing` annotations into account.

Note: The current [docs](https://junit-pioneer.org/docs/system-properties/) say to only use `closest`, but of course they "only" fit to current implementation.

**Comment by Hancho2009** [comment]
This also effects `EnvironmentVariableExtension` because both extensions should probably operate equally in that regards #180

**Comment by Bukama** [comment]
I think we should improve those extensions so they also take the outer configuration to allow less redundance, but also adding a `@IgnoreSetOrClearSystemProperty` annotation if one test should not be affected by that, e.g.

```
@SetSystemProperty(key = "needByAll", value = "new value")
class MyTestClass {

  @Test
  void needsProperty() {
    // 
  }
  
  @Test
  void alsoNeedsProperty() {
    // 
  }  
  
  @Test
  @IgnoreSetOrClearSystemProperty(key = "needByAll")
  void doesNotNeedProperty() {
    // 
  }   
} 

```

**Comment by Bukama** [comment]
Linked to #248 (PR for #180)

**Comment by Bukama** [comment]
> Linked to #248 (PR for #180)

Just to note: In #248 it still uses `findClosestEnclosingRepeatableAnnotations`, So discussion still open.

**Comment by beatngu13** [comment]
`AbstractEntryBasedExtension` probably should serve as a central place to control the annotation processing, like I said [here](https://github.com/junit-pioneer/junit-pioneer/pull/248#issuecomment-623609796):

>Note that subclasses of `AbstractEntryBasedExtension` are currently responsible for discovering their own annotations. In a second step, we might move additional code into `AbstractEntryBasedExtension`. However, for now I think the way it is implemented is already a good improvement.

This way, we get consistent behavior for all subclasses such as `SystemPropertyExtension` and `EnvironmentVariableExtension`.

I am not sure if I would go for stuff like `@IgnoreSetOrClearSystemProperty`. This can make things really complicated, both from a maintainer and a user perspective. And one can easily achieve the desired behavior with what we already have.

I would suggest to look into similar extensions in Jupiter and—if applicable—try to copy their behavior, such that users get consistent behavior across the JUnit universe.

Thoughts?

**Comment by Bukama** [comment]
@beatngu13 It's more about how deep the extension should look inside class hierarchie to look for annotations to apply. I think the way it is implemented now is fine and especially clear for the users - so no magic surprised in such a "dangerous zone".

So I think we are fine the way it is done now (and still with the reduce duplication PR).

@Michael1993 @aepfli What are you thoughts on this? Shall we leave it as it is and close this issue or are there things I don't see at the moment?

**Comment by Bukama** [comment]
> @Michael1993 @aepfli What are you thoughts on this? Shall we leave it as it is and close this issue or are there things I don't see at the moment?

@NPException What do you think? (sorry forgot to add you to the list above)

**Comment by aepfli** [comment]
I think `@Ignore...` annotations are an overkill, and might polute the API with unnecesary interfaces. Furthermore the user is not really blocked by this, as their are multiple solutions to it. yes they most likely end up in duplication (either with annotations, or with testclasses) but it is not unsolveable and not a nutcracker. Where as having a lot of annoations which serve just a minor edge case can be really tricky and complicate things.

I am also a big fan of @beatngu13 suggestion to unify this handling of annotations at one place. it will maintenance easier, and reduces sideeffects, due to customization for different extensions.

**Comment by Bukama** [comment]
As most of us stated out that we are fine with the way it is (reading: the work of @beatngu13 in #180 ) I close this discussion with result: No change needed.
