### ISSUE TITLE
AppVeyor's caching mechanism throws error

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#234]
The caching mechanism of our build seems to have problems in every builld, e.g. [on of many example logs](https://ci.appveyor.com/project/nicolaiparlog/junit-pioneer/builds/32317746)

```
Build started
git clone -q https://github.com/junit-pioneer/junit-pioneer.git C:\projects\junit-pioneer
git fetch -q origin +refs/pull/221/merge:
git checkout -qf FETCH_HEAD
Restoring build cache
Cache 'C:\Users\appveyor\.gradle\wrapper' - Calculating dependencies checksum...Error calculating dependencies CRC: Error calculating CRC32 for C:\projects\junit-pioneer\.infra\gradle\gradle-wrapper.properties: The system cannot find the path specified
gradlew.bat assemble --info --no-daemon
Downloading https://services.gradle.org/distributions/gradle-6.3-bin.zip
.........10%..........20%..........30%.........40%..........50%..........60%.........70%..........80%..........90%..........100%
Initialized native services in: C:\Users\appveyor\.gradle\native
```

**Comment by MarkRKar** [comment]
Is this blocking the 0.5.7 release on maven central?

**Comment by aepfli** [comment]
actually currently releasing is still done on travis.yml and appveyor has actually no usage, as far as @nicolaiparlog told me ones.

So we can remove the appveyor file and not use appveyor anymore. 

Is there also an issue with release 0.5.7 ?

**Comment by MarkRKar** [comment]
I was just wondering when version 0.5.7 will appear on maven central not sure if there is a problem.

The [GitHub Release](https://github.com/junit-pioneer/junit-pioneer/releases/tag/v0.5.6) for version 0.5.6 was created on Mar 31, 2020 and that is also the date from [Maven Central](https://mvnrepository.com/artifact/org.junit-pioneer/junit-pioneer/0.5.6).
The [GitHub Release](https://github.com/junit-pioneer/junit-pioneer/releases/tag/v0.5.7) for version 0.5.7 was created Apr 07, 2020 but is still not on [Maven Central](https://mvnrepository.com/artifact/org.junit-pioneer/junit-pioneer).

I am not sure how the release on maven central works but I saw the Travis build status error and thought that this is maybe related.

**Comment by aepfli** [comment]
actually there is no release 0.5.7 currently. We skipped that release, but this might be related to https://github.com/mockito/shipkit and how it works. The release notes also state that we did an CI skip, and it is not marked as an current release. Therefore i assume that this is related to shipkit and how this is handled. But i will take a closer look if i find time, to undermine my assumption.

Travis is failing due to junit-pioneer/junit-pioneer.github.io#5 - we are aware and in the meantime i created #235 to make travis happy again. Anyways we are currently in the transition from Travis to Github Actions so this might not be needed in the near future #192

**Comment by Bukama** [comment]
> actually currently releasing is still done on travis.yml and appveyor has actually no usage, as far as @nicolaiparlog told me ones.
> 
> So we can remove the appveyor file and not use appveyor anymore.

What's the task of `appveyor` in general? Just a travis thing?

**Comment by aepfli** [comment]
appveyor offers builds on windows machines, so the same thing as travis or githubactions just dedicated to windows

**Comment by Bukama** [comment]
> appveyor offers builds on windows machines, so the same thing as travis or githubactions just dedicated to windows

And as Github actions can build on windows anyway it's redudant now?

**Comment by aepfli** [comment]
excatly

**Comment by Bukama** [comment]
Then we should consider of removing it as part of the steps taken to migrate to Github Actions. We don't need redundant builds which only increase build response.

**Comment by Bukama** [comment]
#213 removed _AppVeyor_ so this issue can be closed.
