### ISSUE TITLE
EnvironmentVariable annotations/extension documentation problems

### ISSUE THREAD

**Issue by Hancho2009** [junit-pioneer/junit-pioneer#237]
@nicolaiparlog  I noticed during watching a past recording of your stream that during the work on #174 the warnings went into the wrong file.

https://github.com/junit-pioneer/junit-pioneer/blob/master/src/main/java/org/junitpioneer/jupiter/ClearSystemProperty.java#L33

Should be in https://github.com/junit-pioneer/junit-pioneer/blob/master/src/main/java/org/junitpioneer/jupiter/ClearEnvironmentVariable.java

Same for 
https://github.com/junit-pioneer/junit-pioneer/blob/master/src/main/java/org/junitpioneer/jupiter/SetSystemProperty.java#L34

Should be in https://github.com/junit-pioneer/junit-pioneer/blob/master/src/main/java/org/junitpioneer/jupiter/SetEnvironmentVariable.java

Check also the `@since` from SystemProperty Extensions

Also https://github.com/junit-pioneer/junit-pioneer/blob/master/build.gradle.kts#L106 should reference the EnvironmentVariableExtension instead of the SystemPropertyExtension

https://github.com/junit-pioneer/junit-pioneer/blob/master/docs/enviroment-variables.adoc
`class MySystemPropertyTest {` should proably also be changed to `class MyEnvironmentVariableTest {`

**Comment by Bukama** [comment]
Good spot! Thank you!

(Just to mentioned it: Due  #180 the two extensions may become one)

**Comment by Hancho2009** [comment]
As fare as I understand #180 this is a behind the scenes change and the exposed annotations and other places I mentioned will continue to exists after the issue is resolved.

**Comment by nicolaiparlog** [comment]
Stupid me for putting the docs in the wring places. :see_no_evil:

Re #180, yes, that will most likely be just a refactoring that remains invisible to the user.
