### ISSUE TITLE
Deprecated Gradle features used in project version 0.5.6

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#246]
When building the project (version 0.5.6 which uses Gradle 6.3) there is a deprecation warning by Gradle. We should have a look at it:

> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0. Use '--warning-mode all' to show the individual deprecation warnings. See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by aepfli** [comment]
as we right now do not have plans to migrate to gradle 7 (which is not a thing currently) i would not invest to much time into this, also there is the travis site build trigger, which might get removed quiet soon, which also might be the cause of a lot of those warnings

**Comment by Bukama** [comment]
At the moment we use Gradle 6.3 which is the most current version (yesterday 6.4. RC3 was released), so there's no option to migrate. But anyway we should have a look at the warning and evaluate whats deprecated and want to to to migrate it to wanted way as long as we have no pressure on that.

**Comment by aepfli** [comment]
as we do not have pressure on that, i will remove the milestone, as it will also not block a release

**Comment by Bukama** [comment]
At the moment we have two warnings. 

> The AbstractArchiveTask.baseName property has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the archiveBaseName property instead. See https://docs.gradle.org/6.3/dsl/org.gradle.api.tasks.bundling.Abstrac
tArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:baseName for more details.

I think this comes from the `jar` task, but I don't get it removed, as I don't know where the `baseName` is used (and never worked with gradle before):

What did **not** help:

* Upgrade plugins to newest version
* Remove travis task
* setting the property inside the `jar` task (regardless to what value)


> The CheckstyleExtension.setConfigDir() method has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the CheckstyleExtension.getConfigDirectory().set() method instead. See https://docs.gradle.org/6.3/dsl/org.
gradle.api.plugins.quality.CheckstyleExtension.html#org.gradle.api.plugins.quality.CheckstyleExtension:configDir for more details.
        at Build_gradle$5.execute(build.gradle.kts:77)

The second one comes from checkstyle. Here the cause was shown in stacktrace and I could fix it (see #246).

**Comment by nicolaiparlog** [comment]
Oh, didn't see that @aepfli removed the milestone on purpose - thought it was just missing. Let's not start seeing Cleaner Pioneers as the release milestone, though. We don't necessarily have to clear up all the things in there for 1.0. Let's continue chipping away at it and consider the remaining issues some time in summer.

**Comment by nicolaiparlog** [comment]
This issue is marked as blocked because, currently, there seems to be no way to get rid of the warning. We'll have to check again in a few months.

**Comment by Bukama** [comment]
> This issue is marked as blocked because, currently, there seems to be no way to get rid of the warning. We'll have to check again in a few months.

I don't want to sign this. Only because a _never have use gradle-guy_ (read "I / me") can't figure out where we you the command, we somewhere use it. And there is already a non-deprecated method we should use instead.

**Comment by aepfli** [comment]
well we do use a lot of plugins, and it might easily an issue from another plugin.

eg when starting everything in debug mode you will see those lines
```
020-05-02T16:31:05.487+0200 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Apply plugin org.shipkit.internal.gradle.bintray.ShipkitBintrayPlugin to root project 'junit-pioneer'' completed
2020-05-02T16:31:05.488+0200 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Apply plugin org.shipkit.internal.gradle.java.ComparePublicationsPlugin to root project 'junit-pioneer'' started
2020-05-02T16:31:05.488+0200 [WARN] [org.gradle.internal.featurelifecycle.LoggingDeprecatedFeatureHandler] The AbstractArchiveTask.baseName property has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the archiveBaseName property instead. See https://docs.gradle.org/6.3/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:baseName for more details.
2020-05-02T16:31:05.488+0200 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Realize task :createDependencyInfoFile' started
```

which show that this happens when we apply shipkit to our project, they use the basename in some places for comparison as it seems like.

**Comment by Bukama** [comment]
Thanks for the hint that its shipkit. And there is already an [issue about that there](https://github.com/mockito/shipkit/issues/848). So we have to upgrade shitkit after that has been solved.

As of this the blocked label is needed.

**Comment by Bukama** [comment]
Hm. The shipkit repo ist archieved and we have to move the plugin (see #442) so we should then have an eye ont he warnings.

**Comment by beatngu13** [comment]
@Bukama #419 introduced the new Shipkit plugins. When looking at the current build logs:

* [Ubuntu / Java 8](https://github.com/junit-pioneer/junit-pioneer/runs/2128293379)
* [Ubuntu / Java 15](https://github.com/junit-pioneer/junit-pioneer/runs/2128293449)

I wasn't able to find the above deprecation warnings anymore. Warnings that are (still?) there:

```text
(node:2302) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[...]
Note: Some input files use or override a deprecated API.
[...]
Note: Some input files use or override a deprecated API.
```

The first one seems to stem from here:

https://github.com/eskatos/gradle-command-action/issues/22

The other two, I guess, are caused by our deprecated `org.junitpioneer.vintage.Test` annotation:

https://github.com/junit-pioneer/junit-pioneer/blob/main/src/main/java/org/junitpioneer/vintage/Test.java

**Comment by Bukama** [comment]
I'm totally with you. As commented above the warnings came from the (old) shipkit plugin and were related to Gradle not to Java (like the two from the vintage error). So I'll close this issue
