### ISSUE TITLE
Convert to a multi-project Gradle build

### ISSUE THREAD

**Issue by smoyer64** [junit-pioneer/junit-pioneer#25]
A mulit-project Gradle build is required so that extensions and engines that require additional dependencies can be separated from the core junit-pioneer project (which like junit5 itself, will not require dependencies).  Something like:

-   junit-pioneer-parent
    -   junit-pioneer
    -   junit-pioneer-suite
    -   junit-pioneer-uprest
    -   junit-pioneer-weld

Note that the alternative is to create a repository per project which requires the entire project infrastructure to be duplicated.  This might make sense for larger projects but won't for projects that include dependencies but offer a relatively small amount of code.

**Comment by nicolaiparlog** [comment]
I'm thinking about taking this issue off [the infrastructure milestone](https://github.com/junit-pioneer/junit-pioneer/milestone/2) because it doesn't seem very urgent. Or did you plan to work on it soon?

Did we even settle on whether we want things like _uprest_ and _weld_ to be submodules (as opposed to stand-alone projects)?

**Comment by smoyer64** [comment]
I think your argument was that maintaining one multi-module Gradle project was easier than maintaining one for each project.  I don't know much about Gradle - in Maven I'd make an organizational POM and inherit from that project.

I do expect to get some more work done on upREST after my son's wedding at the end of July but I don't feel an urgency to get it moved right now.  I would like to move it before it has a lot of users so that they find it at junit-pioneer instead of selesy.

**Comment by nicolaiparlog** [comment]
> I think your argument was that maintaining one multi-module Gradle project was easier than maintaining one for each project.

Makes sense but is of course not the only consideration but let's cross this bridge when we come to it.

> I don't feel an urgency to get it moved right now.

Ok, then I'll remove the issue from the milestone.

**Comment by Bukama** [comment]
@aepfli @sormuras @marcphilipp As you three know gradle better: What's your tought about this?

> Makes sense but is of course not the only consideration but let's cross this bridge when we come to it.

@nicolaiparlog What other concerns do you have?

**Comment by nicolaiparlog** [comment]
I think this issue doesn't fit the current structure. This here project is technically identified as "JUnit Pioneer Expansion Pack (junit-pioneer-xp)" and other projects like junit-pioneer-uprest or junit-pioneer-weld would be created next to it under the same organization. They are independent of one another (with the exception of the website that needs to be built whenever one of them gets released).

Of course, some configurations may be easier to handle if we a parent project, but doing that across different repos or having several projects in the same repo would probably suffer from bad tool support (e.g. builds and releases).

I'll close this.
