### ISSUE TITLE
Documentation about SystemEnvironment not available

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#258]
The [documentation about SystemEnvironmentExtension](https://junit-pioneer.org/docs/environment-variables/) is not available and throws 404 error, when acces via navigation.

When accessed via [overview page](https://junit-pioneer.org/docs/) page is loaded

**Comment by Michael1993** [comment]
The problem was a typo in the name of the file (enviroment-variables.adoc instead of enviro _n_ ment-variables.adoc)
