### ISSUE TITLE
Create a junit-pioneer logo

### ISSUE THREAD

**Issue by smoyer64** [junit-pioneer/junit-pioneer#26]
For the web-site, Github organization, etc.

**Comment by nicolaiparlog** [comment]
This is an "artist's conception of the _Pioneer 10_ spacecraft":

![](https://upload.wikimedia.org/wikipedia/commons/4/46/Pioneer10-11.jpg)

The image is in the public domain. I think it is a good candidate to be turned into a logo by someone with at least moderate artistic skills. What do you think?

**Comment by smoyer64** [comment]
I like it!

I don't have a need for it (yet) but I think maybe we need an extension bench-marking tool that we can call the "planetary probe".

**Comment by smoyer64** [comment]
It turns out there are a lot of stamps commemorating the Pioneer missions ... I've temporarily added the $0.33 stamp celebrating Pioneer 10 as the logo (because it's square) so I can stop trying to remember which project is which.

**Comment by nicolaiparlog** [comment]
I'm tempted to close this. I included the stamp in [the README](https://github.com/junit-pioneer/junit-pioneer#junit-pioneer) and as favicon on the project site and I think it's fine. If someone with more artistic talent comes along to create something more stylish, that would be great but it's hardly a priority at this point.

**Comment by smoyer64** [comment]
My artistic skills were eliminated by my Engineering Graphics classes - now I'm all straight lines and right angles.  Let's close it now and anyone with the desire to update the graphics can put in PRs for it.

**Comment by nicolaiparlog** [comment]
:+1:

Note for posterity: PR #59 added `project-logo.jpg` to [the `docs` folder](docs), from which it is pulled into the site.
