### ISSUE TITLE
Typo in documentation: assertThat().isEqual_s_To()

### ISSUE THREAD

**Issue by Bananeweizen** [junit-pioneer/junit-pioneer#263]
The website examples all say
`assertThat(...).isEqualsTo(...)`
That's probably a typo, since the correct method in AssertJ is
`assertThat(...).isEqualTo(...)`
(without the additional 's').

**Comment by aepfli** [comment]
hi, thank you for your issue.

I would kindly ask you to put all context into the ticket, regarding what files do you specifically are talking about, or where do you see the error. Addtionally it would be highly appreciated to add links to the methods you are referencing in AssertJ. It seems like you did already some research and it  would be good, and easier for us, if you could share all the knowledge you gathered regarding this issue.

I am doing wildguesses now, and i assume we only have typos in our documentation/website? or are there also additional issues somewhere? Based on AssertJ documentation there is also the possibility for `isEqualsTo` or there is also a indifference here. 

As said, some examples would be highly appreciated.


Thank you
Simon

**Comment by Bananeweizen** [comment]
![grafik](https://user-images.githubusercontent.com/406876/82785468-edb0ec00-9e62-11ea-87b2-f2a6340b2d8a.png)

The same error is contained in _every_ extension example. I.e. if you select any other of the yellowish extension names in the upper left of the screenshot, the code blocks there contain the same issue.

**Comment by aepfli** [comment]
Thank you @Bananeweizen
