### ISSUE TITLE
Shall the issue number be mentioned in commit title?

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#264]
In #229 IDE specific configuration files / support for specific IDE features are discussed.
One of them are clickable issue/PR links inside IDEAs git history. As long as there is no build-in functionality for that provided by IDEA itself, we decided to provide an intermediate solution (see discussion in #229 and PR in #262).

To make use of this feature, we would have to decide to mention the issue and or PR number inside the header line of commits, so they show up in history.
This was done sometimes in Pioneer history, but in the later time it was not done by purpose. 

_@nicolaiparlog Can you write down why? I remember that you phrases this out some months ago on stream, but I can't remember the cause - I think it was something about less space for title message due the needed characters for the issue_

Regardless of the outcome of this discussion it should be placed inside the `CONTRIBUTING.md` file. There is already a section in it about writing the "final" commit, but there are not information about the title of those commits.

**Comment by Bukama** [comment]
My opinion: I vote for writing the issue number inside the title. I'm open for putting the PR number also into it, but this costs further space in the titles ~70 chars.

**Comment by aepfli** [comment]
although it seems to be useful, the interesting part to mention is, that the issue link navigation not only applies to the header, but everywhere the git commit message is parsed:

- in the git log
![image](https://user-images.githubusercontent.com/9987394/82820597-d2fe6780-9ea2-11ea-9eed-94be6fed69ba.png)
- in the annotate 
![image](https://user-images.githubusercontent.com/9987394/82820666-e6113780-9ea2-11ea-853c-cbcd96ba6e68.png)

and so on. So the git commit title is definitely useful, and makes it easier to navigate.

**Comment by nicolaiparlog** [comment]
This is essentially a reversal of #79 and I agree very much with it. I think removing issue and PR numbers from the commit message's "title" wasn't a good decision. I'd like to reinstate the old rule. I'll open a PR.

**Comment by nicolaiparlog** [comment]
See #273.

**Comment by Bukama** [comment]
#273 was merged, so closing this issue
