### ISSUE TITLE
Documentation: Personal or formal style

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#265]
@aepfli brought up this documentation topic inside a PR, which I cut out into this issue, as we have to decide, have to update the `CONTRIBUTING.md` file and maybe several documentation files.

> i just want to raise a discussion here, about our documentation style, or more about unifying it - and maybe find a guideline on how to write docs. Currently it seems like we have two different approaches:
> 
> 1. the personal/informal one, in which we address the developer and his work directly with you and your tests (like here)
> 2. the formal one, in which it seems like we try to avoid such constructs (eg. RangeSource)
> 
> For a good comprehensive documentation i think we should agree on one style to use. As it makes reading the docs easier to grasp and shows some kind of consistency. The questions are
> 
> * is this something which only bothers me? than lets continue, as i did not say anything :)
> * what would be the general preference. I tend to use the formal one, simply because it feels more 'technical' to me.
> 
> What is the general take on this?

**Comment by Bukama** [comment]
I always thought that I'm the only one that tries to write formal style, but nice to see that I'm not alone.

The formal one has several advantages in my point of view:
* More serious
* Better focus on technical description, which brings up "better" text (with personal one you easily fall into a more conversational style)
* No one feels "touched personally"

This said I vote for keeping our documentation the formal style.

**Comment by Michael1993** [comment]
This is probably a non-issue because it seems I'm the only one who wrote informal style documentation so far - in [the report entries documentation](../tree/master/docs/report-entries.adoc) and in #227.

If @nicolaiparlog agrees that formal documentation everywhere is the way to go, I'll fix these.

**Comment by aepfli** [comment]
i do not have a dedicated opinion on that, i just prefer consistency :D but as it seems like we do have an agreemet, we should at least use this ticket to persist it some how in the documentation and in the end close this topic

**Comment by Bukama** [comment]
I had a short talk about this with @nicolaiparlog and he will write his opinion down when he finds the time. But he mentioned that there are other things to consider, e.g. Mannings (the publisher of his book) wants the authors to address their readers directly.

**Comment by nicolaiparlog** [comment]
While I tend to write somewhat formal (judging by the amount of passive voice that is used (see what I did there?)), I was told by my publisher that an active voice and addressing the reader with "you" is preferred. If you read carefully, you may see that this style is indeed more engaging and thus better to transport information.

I tend to go with the more active, less variant form, here. That does not mean, we need to constantly address the reader or never use passive voice, but too much of the latter and "we" should be avoided. I also think the documentation on the website can be more on the informal side whereas the Javadoc should only talk about code (i.e. no "you", "we", etc.).

Does that mean we have to rewrite all our docs? Or are we too :chicken: for that?

**Comment by Bukama** [comment]
After reading the documentation page several times again and checking your comment too, I think we are fine the state we are, as long as we don't you the personal form in Javadoc. Websites documentation is fine I think.

Would say we check that, maybe remove it and then close this issue.

**Comment by Bukama** [comment]
Could not found any personal form in the Javadoc. So closing this bishue.
