### ISSUE TITLE
SonarCloud update to Java 11

### ISSUE THREAD

**Issue by Michael1993** [junit-pioneer/junit-pioneer#267]
[SonarCloud will stop supporting Java 8 by October 2020.](sonarcloud.io/documentation/upcoming)
Note that this link points to upcoming changes, not this specific issue.

GitHub actions should be updated.

**Comment by Michael1993** [comment]
@aepfli I assigned this to you because it seemed you already know how to do this.

**Comment by aepfli** [comment]
https://github.com/junit-pioneer/junit-pioneer/blob/1121f77446595061f1fc32050f0eb31d5584d191/.github/workflows/actions.yml#L41 is the line where we need to swap from 8 to 11 - everyone can take this

**Comment by beatngu13** [comment]
Thanks for the hint @Michael1993. Unfortunately, the link is dead. I assume you meant:

https://sonarcloud.io/documentation/upcoming/

>The version of Java installed in the scanner environment should be upgraded to at least Java 11 by October 2020. Pre-11 versions of Java are already deprecated and scanners using them will stop functioning after October 2020. This refers specifically to the JDK or JRE installed and used in the context where your SonarCloud scanner analysis tool is running. This may be your local build environment or your CI service.
