### ISSUE TITLE
Improvements to StdIOExtension

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-pioneer/junit-pioneer#274]
I had a look at the `StdIOExtension` and I think it's pretty neat. Some details that could be improved:

# Class Name

We never settled this anywhere, but I consider abbreviations as a single word, when it comes to capitalization, so I'd rename `StdIOExtension` to `StdIoExtension` (lower case "o"). For comparison: `DVDReader` vs `DvdReader` and `ASMRMic` vs `AsmrMic`.

# Reset standard reader/writer

The extension should reset the `System.in` and `System.out` after each test.

# `@ExtendWith`

I consider `@ExtendWith` to be a low-level annotation that I'd rather avoid for users. Why not apply it to the already existing `@StdInSource` and then create a new `@StdOut` annotation.

# Unexpected behavior

The documentation says:

> Some readers read all lines from `@StdInSource` eagerly (e.g.: `BufferedReader`) which can lead to unexpected behavior.

Can you go into a little more detail on that and provide an example?

# Small things

There are also a few small things that I already edited. I will put them on a branch.

**Comment by nicolaiparlog** [comment]
The branch is [274-improve-std-io](https://github.com/junit-pioneer/junit-pioneer/tree/issue/274-improve-std-io).

**Comment by Michael1993** [comment]
# Class name
Class renamed to `StdIoExtension`.

# `@ExtendWith`
I renamed `@StdInSource` to `@StdIo` and the extension now requires methods taking either `StdIn` or `StdOut` as parameters to be annotated with it.

# Unexpected behaviour
Documentation updated with an example.

**Comment by Michael1993** [comment]
# Reset standard in/out
Extension now properly resets `System.in` and `System.out`

**Comment by nicolaiparlog** [comment]
Once #253 is merged, we need to look into making this extension thread-safe.

**Comment by nicolaiparlog** [comment]
More thoughts on the matter of thread-safety: We should probably wrap the original `System.out` and forward everything to it (so that parallel tests' output doesn't disappear) and only keep output that comes from the same thread that created the wrapper (so that parallel tests don't pollute the captured output).

**Comment by Michael1993** [comment]
As mentioned on stream, wrapping `System.out` doesn't take non-Pioneer extensions into account which could be a problem.

**Comment by nicolaiparlog** [comment]
I added this to the milestone because I assume it changes the behavior quite a lot and so it shouldn't be done after 1.0 if we can avoid that.
