### ISSUE TITLE
Evaluate and possible improve `TempDir`

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-pioneer/junit-pioneer#277]
The `TempDir` extension may or may not be thread-safe - it's hard to say because its tests definitely aren't (many static fields). The tests need to be made thread-safe, so we can then evaluate the extension itself. Right now, I see no reason why it shouldn't be possible to make it thread-safe (if it isn't already).

Also, can we change the name to `TemporaryDirectory` or something else that doesn't sound like letters cost actual money?

**Comment by Bukama** [comment]
Nicolai is working on it in current stream

**Comment by nicolaiparlog** [comment]
Internet dropped out and we called it a day, but I did make a bit of progress towards more thread-safe tests (extension seems to be fine) and opened (draft) PR #327.

Feature ideas:

I also had some ideas for new features. I want to at least keep them in mind during a potential refactoring and either implement them or put them into separate issues:

* remove need of `@ExtendWith` with a new annotation
* `@TempDir` takes class token parameter, an instance of which is used as strategy to create new dirs
* `@TempDir` takes Boolean parameter that activates creation of new directory for each test
* `@TempDir` stores `TempDirGenerator` in store for other extensions (c.f. junit-team/junit5#1786)

**Comment by Bukama** [comment]
We were thinking about the single/shared-directory functionality.
What about making `@TemporaryDirectory` always single directory (meaning for exactly one test case), while introducing `@SharedTemporaryDirectory` at class level for all tests within this class (including nested).

That would allow the user to single annotate a class to only create a directory once, if all his test just need a place to write and its clear if a directory should be removed after each test or only after all tests are run.

Would need checking for misconfiguration of course, but I can imagine that it will make the functionality more clearer

**Comment by Bukama** [comment]
TempDir extension Issues / Feature request in Junit5 repo


* [Multiple declarations of `@TempDir` in same parameter list or class declaration should fail](https://github.com/junit-team/junit5/issues/2219)
* [Support disabling cleanup for @TempDir](https://github.com/junit-team/junit5/issues/2159)
* [Provide support for setting a custom parent directory for @TempDir](https://github.com/junit-team/junit5/issues/2088)
* [Multiple @TempDirs should result in multiple directories](https://github.com/junit-team/junit5/issues/1967)
* [Introduce cleanup mode in @TempDir](https://github.com/junit-team/junit5/issues/1814)
* [Support @TempDir on constructor parameters](https://github.com/junit-team/junit5/issues/1754)

**Comment by nicolaiparlog** [comment]
The JUnit 5 team has clearly moved this extension forward and it looks like a few more improvements are in the pipeline. In light of that, I propose to remove `@TempDir` from JUnit Pioneer. To make up for it, we could spend some time improving Jupiter's version.

**Comment by Bukama** [comment]
As I suggest to remove the TempDir months ago because of this, my answer is of course: Yes remove it.

**Comment by Michael1993** [comment]
I vote we remove it. It's probably confusing to users as well.

**Comment by nicolaiparlog** [comment]
I just opened junit-team/junit5#2400, so we can get custom file system support into Jupiter's `@TempDir`.

**Comment by nicolaiparlog** [comment]
[The verdict is in](https://github.com/junit-team/junit5/issues/2400#issuecomment-691102300), Jupiter's `@TempDir` will not get custom FS support. To recapitulate:

* Jupiter and Pioneer both have a `@TempDir` extension
* both work in essentially the same way (for the user)
* custom file systems is the only thing Pioneer has that Jupiter's hasn't
* there are quite a few features that Jupiter has that Pioneer doesn't
* there are a number of open requests to Jupiter's feature (see [Bish's list](https://github.com/junit-pioneer/junit-pioneer/issues/277#issuecomment-689062119))

Nota bene: @sormuras tried a different approach to the same topic ([link](https://github.com/sormuras/brahms#temporary-directory-as-resource), [link](https://github.com/sormuras/brahms/blob/master/src/test/java/integration/resource/ChickenAndEggTests.java))

In light of that, here's my proposal:

* we move forward with the deletion of `@TempDir` as currently proposed by #327 and close this issue
* we release 1.0
* we create a new one that aims at a larger-picture reevaluation of this feature set, including a closer look at Jupiter's `@TempDir` and Christian's experiments
* we focus on working through currently open PRs, but put that topic on the top of the list right after that

**Comment by Bukama** [comment]
I‘m fine with this, but we should then add a / change the PR’s note  to give an indormation. that we plan to reimplement it (with more features) in the future. (In the docfile I mean)
