### ISSUE TITLE
Measure code coverage

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-pioneer/junit-pioneer#28]
It might be interesting to measure code coverage. Possible services:

* [codecov.io](https://codecov.io/)

**Comment by nicolaiparlog** [comment]
From #13, which set up the CI pipeline comes this comment of mine:

> Regarding Coveralls: According to junit-team/junit5#240 only Clover properly evaluates test coverage. Unfortunately it is not free. Apparently, it is activated on Cloudbees but for now I am trying to avoid setting up a third build server.
>
> TLDR: No test coverage for now.

**Comment by jbduncan** [comment]
@nicolaiparlog Clover is now open source (http://openclover.org/)!

**Comment by aepfli** [comment]
also sonarqube can handle codecoverage ;)

**Comment by nicolaiparlog** [comment]
Since you mention sonar here and in #50, we should look at both issues at the same time.

**Comment by Bukama** [comment]
> Edit: Let's discuss in #50.

I agree as code coverage is a part of doing SCA. And sonar is already doing CC yet (see sonarbot messages on PRs). So I'll close this 😇
