### ISSUE TITLE
Release action for releasing version 0.7 failed

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#284]
Yesterday @nicolaiparlog wanted to release a new version by pushing the `releaseTrigger` to master branch. Th action started but failed:
The [1st try to release](https://github.com/junit-pioneer/junit-pioneer/runs/791016462?check_suite_focus=true) failed due not been able to checkout master

> [ciReleasePrepare] FAILURE: Build failed with an exception.
[ciReleasePrepare] 
[ciReleasePrepare] * What went wrong:
[ciReleasePrepare] Execution failed for task ':gitCheckout'.
[ciReleasePrepare] > Execution of command failed (exit code 1):
[ciReleasePrepare]     git checkout master
[ciReleasePrepare]     Captured command output:
[ciReleasePrepare]   error: pathspec 'master' did not match any file(s) known to git

The [retry](https://github.com/junit-pioneer/junit-pioneer/runs/791029616?check_suite_focus=true) then failed while the preconditions.

**Comment by Bukama** [comment]
@aepfli May you have a look please

**Comment by aepfli** [comment]
okay my bad. looks like i should have done some better testing. For the action itself to test it, i used master if it works, and i seperatly checked the behaviour with the tag. but never together. so it is actually quiet logical, that if you check out at tag, you are not really on the master ref, but on the tag ref.

Hence that a change in 
https://github.com/junit-pioneer/junit-pioneer/blob/master/.github/workflows/releaseTrigger.yml#L22
to
```
- uses: actions/checkout@v2
  ref: 'master'
```

but before i generate a pr for this, i will do some testing in my fork, just to be save. Sorry for any inconviniences.

**Comment by nicolaiparlog** [comment]
No inconveniences, I'm glad you're taking the time to look at it, thank you!
