### ISSUE TITLE
Update PR-Template

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#286]
In the last weeks / months we updated our contribution guidelines several times to document several "style guide rules".

But as we are all human we do forget to implement some of them or check for them in PR, like:

* One line per sentence in `.adoc` files
* Updating `docs-nav.yml`
* Updating package-info.java
* Use informal style in Javadoc (#265) 
* Check for naming conventions
* Add contributor in `Contributing.md`
* Check if tests for misconfiguration were added (#164)

We should update the `PULL_REQUEST_TEMPLATE.MD` with a task list for those as a help for both - the PR author and the reviewer. This should also be included in the Cleaner Pioneer Milestone.

_Request feedback_

**Comment by nicolaiparlog** [comment]
Good idea! We should definitely do that. You listed a few details, but I'm sure there are larger issued to address as well, right? Tests come to mind... having documentation in the first place.... more?

I recommend to create a hierarchical list with check boxes:

Documentation

- [ ] there is documentation
- [ ] one sentence per line

**Comment by Bukama** [comment]
Up to now all responses are positive, so I'll put the "up for grabs" on it.
