### ISSUE TITLE
@SetEnvironmentVariable corrupts JDK-internal structures in some cases

### ISSUE THREAD

**Issue by hovinen** [junit-pioneer/junit-pioneer#287]
The method `EnvironmentVariableUtils.modifyEnvironmentVariables` tries first a method which works on Windows and then a method which works on Linux and OS X. The former accesses the field `java.lang.ProcessEnvironment.theEnvironment` by reflection, assumes it to be a `Map<String, String>`, and modifies it. On at least some platforms, `java.lang.ProcessEnvironment.theEnvironment` exists but is a `Map<Variable, Value>`, so the map is corrupted after being modified. Subsequent calls to fetch data out of `System.getenv()` result in a `ClassCastException`.

I can see this issue in version 0.6.0.

**Comment by Bukama** [comment]
Hey @hovinen,
thank your for this very detailed bug report and for the PR (this is why I assigned you to this issue)!
We'll have a look!

**Comment by nicolaiparlog** [comment]
Just saw this - very interesting. Good observation @hovinen and thank you for the fix as well. :+1: 

Took me a while to understand why the change is _actually_ a fix and I think that we should add a comment that gives a quick explanation and links back to this ticket to prevent careless inlining from resurrecting the bug.

**Comment by Bukama** [comment]
> Just saw this - very interesting. Good observation @hovinen and thank you for the fix as well. 👍
> 
> Took me a while to understand why the change is _actually_ a fix and I think that we should add a comment that gives a quick explanation and links back to this ticket to prevent careless inlining from resurrecting the bug.

Documentation update is needed

**Comment by hovinen** [comment]
Sorry for taking so long on this; I've been under water.

I've sent a PR which adds an explanatory comment.
