### ISSUE TITLE
Builds brake due caching problems

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#290]
Since a few days all builds break due caching problems, like this [build of the Pioneer assertions](https://github.com/junit-pioneer/junit-pioneer/pull/245/checks?check_run_id=808150118)

It seems that there are issues with the GithubAction for caching. @Michael1993 found this [issue about the Gradle / GithubActions caching](https://github.com/eskatos/gradle-command-action/issues/7).

**Comment by beatngu13** [comment]
Haven't had time to read through the linked issue with Gradle/GHA, but I can easily remove the caching for now? Probably better to have a slower but working build.

**Comment by Bukama** [comment]
> Haven't had time to read through the linked issue with Gradle/GHA, but I can easily remove the caching for now? Probably better to have a slower but working build.

Yes. Make it run, then make it fast.

**Comment by beatngu13** [comment]
Had to close #292 because it looks like the caching issue stems from the Gradle command action:

https://github.com/eskatos/gradle-command-action/issues/24

Will try out if [disabling the wrapper cache](https://github.com/eskatos/gradle-command-action#caching) helps.

**Comment by beatngu13** [comment]
Seems like #292 fixes the build problems. However, I would keep this issue open until the Gradle command action is fixed, then we can revert the PR and re-activate the Gradle wrapper caching.

**Comment by Bukama** [comment]
Thank you @beatngu13 ! As @aepfli approved the PR, I just merged it. Let's hope that we get back on track until this here gets fixed (-> blocked)

**Comment by Bukama** [comment]
Maybe related to #325
