### ISSUE TITLE
Improvements to Pioneers assertions

### ISSUE THREAD

**Issue by Michael1993** [junit-pioneer/junit-pioneer#298]
We decided on stream that the current state of #245 is good enough to merge but there is room for improvement.
Some starting ideas: 
- separating `ExecutionResultAssert` into test case assertions, report entry assertions and test suite assertions.
- reconsider the names of the interfaces, e.g.: `ExecutionResultAssert` could be `SingleTestAssert`, `TestCaseAssert` could be `StartedTestAssert`, etc.

**Comment by nicolaiparlog** [comment]
Please remember to add your contribution of the assertions to the README. :)

**Comment by Bukama** [comment]
I'm open for improvements

**Comment by Michael1993** [comment]
Probably should expose published report entries and thrown exceptions to miscellaneous assertions.

**Comment by Michael1993** [comment]
After working on the concurrency PR, I realised that adding thrown exceptions from indirectly executed tests makes debugging failing assertions a lot easier, so I added that too
