### ISSUE TITLE
Add Nexus credentials to Repository settings

### ISSUE THREAD

**Issue by aepfli** [junit-pioneer/junit-pioneer#299]
Our release build needs some credentials to be working correctly. It seems like they are not set up correctly, so we need to add them, or update them.

We do need 4 Properties: https://github.com/junit-pioneer/junit-pioneer/blob/master/.github/workflows/releaseTrigger.yml#L38-L41
- NEXUS_TOKEN_PASSWORD
- NEXUS_TOKEN_USERNAME

and they need to be added here:
![image](https://user-images.githubusercontent.com/9987394/87514758-0b3c4e00-c67b-11ea-9d2b-587f09b41208.png)

**Comment by aepfli** [comment]
this links to #213

**Comment by nicolaiparlog** [comment]
I didn't quite understand why this is needed: I thought Shipkit pushes to Bintray, which then pushes to Maven Central. That's not quite correct, though, as indicated by `shipkit.gradle`, which contains these lines:

```gradle
bintray {
    user = System.getenv('BINTRAY_USER_NAME')
    key = System.getenv('BINTRAY_API_KEY')

    pkg {
        userOrg = 'junit-pioneer' // https://bintray.com/junit-pioneer
        repo = 'junit-pioneer'    // https://bintray.com/junit-pioneer/junit-pioneer
        name = 'junit-pioneer'    // https://bintray.com/junit-pioneer/junit-pioneer/junit-pioneer
        licenses = ['EPL-2.0']
        vcsUrl = 'https://github.com/junit-pioneer/junit-pioneer.git'
        labels = ['testing', 'junit', 'extensions']

        version {
            mavenCentralSync {
                sync = true
                user = System.getenv('NEXUS_TOKEN_USERNAME')
                password = System.getenv('NEXUS_TOKEN_PASSWORD')
            }
        }
    }
}
```

**Comment by nicolaiparlog** [comment]
This is akward...

![image](https://user-images.githubusercontent.com/6537432/88910647-112a5580-d25d-11ea-907d-83f2cf9584c6.png)

**Comment by nicolaiparlog** [comment]
Ok, got it. Release build of 0.9.0 was successful, [including the sync to Nexus](https://github.com/junit-pioneer/junit-pioneer/runs/952443946?check_suite_focus=true#step:7:323) and the version indeed [shows up on Maven Central](https://repo.maven.apache.org/maven2/org/junit-pioneer/junit-pioneer/0.9.0/).
