### ISSUE TITLE
Pick branch strategy

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-pioneer/junit-pioneer#30]
I guess as most projects _JUnit Pioneer_ will favor developing on branches. Should this be made mandatory even for seemingly small fixes?

How should branches be merged? Should regular merges, resulting in merge commits, be favored or rebases? Related to that should commits be cleaned up or even squashed or is a more chaotic commit history ok?

- [x] decide on how to branch and merge
- [x] document in [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)

**Comment by nicolaiparlog** [comment]
My personal opinion is:

* Branches for everything unless work on master is _required_ (for whatever reason)
* _Always_ create merge commits
* Branches should be reasonably clean before being merged. Ideally, every commit builds but that is not required - every commit should compile, though. The number of commits should be reasonable as well and some squashing might be necessary to get there.

Alternatively, I can be convinced of the following:

* Branches for everything unless work on master is _required_ (for whatever reason)
* _Always_ squash and rebase

**Comment by jbduncan** [comment]
I personally favour rebase and squash over branch merging, but I can't give a particular reason why I prefer one over the other. 

Maybe because I enjoy trekking through a git repo history on GitHub linearly and find the occasional merge commit distracting? 

But I admit that's not a very good reason to not go for branch merging if it would make using history-related git commands easier, for example. So in terms of the big picture, I don't mind either way. :)

**Comment by nicolaiparlog** [comment]
@smoyer64 Do you have any opinion on this? I would like to discuss this and #31 before working on the code.

**Comment by smoyer64** [comment]
I was looking at this this morning and noticed that even when you were working as a sole developer, you were using PRs to merge into master.  I think we should continue that behavior and protect master.  The CI system will need to be able to write to master (for tagging and automatically changing the versioning).  As owners, I think you and I will continue to be able to commit directly to master but we should only use that function to fix problems with the CI system.

**Comment by nicolaiparlog** [comment]
Ok, branches it is (except for special cases like CI). What about merging? Merge commit or rebase-and-squah? It looks like the JUnit team actually does neither but instead does rebase-and-fast-forward.

**Comment by nicolaiparlog** [comment]
Oops...

**Comment by nicolaiparlog** [comment]
I've thought long and hard about this and settled on proposing _squash and merge_. At first this was my least favorite merging strategy because it looses the detail of how the code evolved before being merged. Here's why I'd still like to use it:

* it results in a succinct history
* the average commit message quality can be much higher
* it allows referencing issues and PRs in commit messages without creating noise
* it decouples the repo's commit history from individual contributor's commit styles

It was actually the last point that convinced me to go this way. I'm a perfectionist and structuralist and can't stand having wildly varying commit styles and quality in the same project. If one contributor solves an issue in five reasonable steps but each commit has the message "Worked on MangoJuicer" and another uses 50 commits, each recounting the Silmarillion, I will either start haggling with contributors over their commit messages or go bonkers. In that sense, squash and merge is a matter of mental health. :wink:

With that in mind have a look at the second point. I plan to make the final commit message part of the discussion of the PR, so contributor and maintainers can collaborate on having a single good message for the entire PR.

Regarding the loss of history: I think this is acceptable. First of all, a decent portion of the changes will be due to the dialog that happens in the pull request, which is usually not reflected in commit messages. In that sense relevant context will be missing from the history anyways, only available on GitHub. But while you're there, why not study the entire PR backstory?

Then, and maybe it should shame me to admit that, I rarely go through the history to see how a piece of code evolved. Much more often I want to see why a specific line is present and I think that can be achieved just as well with a single commit per PR. Throw in the higher quality of commit messages and it might actually be easier to deduce context.

**Comment by jbduncan** [comment]
Very reasonable explanation @nicolaiparlog. I struggle to fault this decision, so I approve of it. :+1:

**Comment by smoyer64** [comment]
Sounds good to me ... I guess this also brings up the question of how we should document project policies/conventions.

**Comment by nicolaiparlog** [comment]
Ok, here's the thing... While trying to get the project to build, I realize that our strong dependency on upstream details (currently most prominently visible in our dependency on snapshot artifacts - something that might be worth a discussion) will require us to often make or rather mimic changes that were made there. I would prefer not to go through the issue-PR-discussion loop every single time.

I propose to add two new "change modes" for our little project:

* For very simple and straight forward changes (e.g. [this one](https://github.com/junit-team/junit5/issues/793#issuecomment-294377755)), I would allow maintainers to commit directly to master (with sensible commit messages, though).
* For other changes that are not quite that simple but still don't require a discussion of the background, a PR should be opened.

This means that only upstream changes that require us to discuss whether or how to follow up on them or ones we want to put off would get an issue.

If this is supported, I'll edit `CONTRIBUTING.md` accordingly.

**Comment by smoyer64** [comment]
This seems reasonable to me ... I think the difference between use case #2 above and the "normal" use case it whether you leave the PR open long enough for comments to occur.  If you open a PR and immediately merge it, you end up with the documentation but it's clear you didn't expect anyone to issue a code review.  Even in this case, if someone chooses to provide comments on an already merged PR, it can go through another iteration.
