### ISSUE TITLE
Align documentation headers and ToC entries

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-pioneer/junit-pioneer#311]
In [the documentation](https://junit-pioneer.org/docs/), some extensions use their annotations as titles and ToC entries (e.g. "@DisableIfDisplayName"), others use natural language in different capitalization (e.g. "Report entries" and "Range Sources"). This should be aligned when possible (and then documented). But what naming strategy works best?

* annotations or natural language?
* should ToC entries and page titles be identical?
* important to keep in mind that page title and description play a role for search engines

**Comment by nicolaiparlog** [comment]
Here are my thoughts...

While I appreciate the ease of use of using the annotation names when possible, this has several downsides:

* naming all annotations of an extension can be ugly (e.g. "@ClearEnvironmentVariable and @SetEnvironmentVariable")
* naming all annotations of an extension may be impossible (e.g. "Range Sources")
* naming annotations if possible, but reverting to natural language otherwise in inconsistent (who said "eye sore"?)

So this is my favorite approach (currently):

* use (short) natural language for ToC entries and page titles (i.e. keep them aligned)
* mention all involved annotations in the page description (failing that, mention the most important ones)

**Comment by Michael1993** [comment]
In #265 we agreed that [the documentation should use active voice and can be less formal](https://github.com/junit-pioneer/junit-pioneer/issues/265#issuecomment-641445070). I think renaming the documents to use natural language is in line with that decision. I support it.

I think the documentation could be considered "incomplete" if not all involved annotations (that are in Pioneer) are mentioned. Then again, you could say that if you know one `RangeSource` you know them all, so... 🤷

**Comment by nicolaiparlog** [comment]
> I think the documentation could be considered "incomplete" if not all involved annotations (that are in Pioneer) are mentioned

All should be mentioned, but not necessarily in the docs landing page or in the ToC: :grin: Thanks for the PR!

**Comment by nicolaiparlog** [comment]
Since we seem to agree on natural language, the next question is capitalization of titles. :grin: I prefer to capitalize most words with a few exceptions like "a", "on", etc. [This tool](https://capitalizemytitle.com/) helps with that.
