### ISSUE TITLE
Explore use of InvocationInterceptor to disable (parameterized) tests

### ISSUE THREAD

**Issue by nipafx** [junit-pioneer/junit-pioneer#313]
In #163, I wrote:

> We just updated to Jupiter 5.5 (#278) to use the new [`InvocationInterceptor`](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/InvocationInterceptor.html) API. _If_ that API gets called for individual parameterized test invocations, it would be a very powerful way to implement disabling parameterized tests. The provided [`Invocation`](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/InvocationInterceptor.Invocation.html) allows skipping tests and the [`ReflectiveInvocationContext`](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/ReflectiveInvocationContext.html) seems to give access to the actual arguments. Someone should look into that and possibly create an issue if the approach seems promising. 😊

Yes, someone should.

**Comment by Bukama** [comment]
Maybe related to #1 and #71

**Comment by Michael1993** [comment]
I did a bit of investigation and created `@DisableIfParameter` - it behaves exactly the same way as `@DisableIfDisplayName` except it works on parameters (using `Object::toString`) instead of the display name.

I'm still considering how the annotation should interact with parameters:
`DisableIfDisplayName`
1 input (DisplayName) => against many inputs (annotation values)
vs.
`DisableIfParameter`
many input (test parameters) => against many inputs (annotation values)

**Comment by nipafx** [comment]
As we found out on stream when reviewing #368, the any/all semantic as well addressing individual parameters need to be discussed. Here's a potential solution we came up with:

```java
@ParameterizedTest
@...

// disables if at least one param contains at least one of the values - "or"
@DisableIfAnyParameter(contains = { "foo", "bar" })
// disables if each param contains at least one of the values - "and"
@DisableIfAllParameters(contain = { "foo", "bar" })

// disables if the specified parameter contains at least one of the values
// (the phrasing implies that one parameter containing a value is enough to disable the test - "or")
@DisableIfParameter(name = "firstName", contains = { "foo", "fu" })
@DisableIfParameter(name = "lastName", contains = { "bar", "baz" })

// a deeper structure that allows specifying any/all semantics:
@DisableIf(
	any = {
		@Parameter(name = "firstName", contains = { "foo", "fu" })
		@Parameter(name = "lastName", contains = { "bar", "baz" })
	},
	all = {
		@Parameter(name = "firstName", contains = { "foo", "fu" })
		@Parameter(name = "lastName", contains = { "bar", "baz" })
	}
)
void test(String firstName, String lastName)
```

While the last variant seems to be the most powerful, it's also "wasteful" - it requires more understanding from the user and blocks very general annotation names like `@DisableIf` and `@Parameter`. Not sure which way to go with, but I lean towards `@DisableIfAnyParameter`, `@DisableIfAllParameters`, and `@DisableIfParameter`.

**Comment by Michael1993** [comment]
To further clarify:

```java
// disable test if parameter contains "foo" or "bar" *OR* if parameter matches the RegEx
@DisableIfParameter(name = "lastName", contains = { "foo", "bar" })
@DisableIfParameter(name = "lastName", matches = { "[A-Z]+@.*" })

// disable test if parameter contains "foo" or "bar" *AND* if parameter matches the RegEx
@DisableIfParameter(name = "lastName", contains = { "foo", "bar" }, matches = { "[A-Z]+@.*" })
```

Does this make sense or is this unnecessary?

**Comment by Michael1993** [comment]
After wasting about an hour, I learned that while we _could_ use [Parameter#getName](https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/Parameter.html#getName--), it only works if the information was included during compilation (which can be checked with [Parameter#isNamePresent](https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/Parameter.html#isNamePresent--)).

I've created an alternate approach that's index based. That's always available, at least.

**Comment by nipafx** [comment]
Re parameter names:

* We need to document that for names to work, the compiler needs to be configured accordingly.
* If parameter names are used and they aren't present, the error message must clearly express what the problem is and how it can be solved.

(Btw, I would've been stuck on exactly the same thing. 😆 )

Did we also discuss whether order of `@Disable...` annotations could be used to target parameters? E.g. there are two parameters and two `@Disable...` annotations, so we assume the first annotation applies to the first parameter and second to second. Hm... scratch that, that's a terrible idea.

Re `contains` and `matches`: Should we even allow both in the same annotation? I understand the appeal of being able to express _and_ (same annotation) and _or_ (two annotations), but other than that it doesn't seem to be that enticing.

* not clear from just looking at it whether it has _and_ or _or_ semantic
* both can be expressed by properly formed regular expressions

I just looked up `@DisableIfDisplayName` and unfortunately, it allows `contains` and `matches`, but uses _or_ semantic. I wonder whether we should change that...

**Comment by nipafx** [comment]
I was told I need to make an executive decision - here it is:

* parameter names: use where possible, otherwise exception with good explanation
* and/or for several annotations: or, i.e. as soon as one `@DisableIf`-check passes, the test is disabled
* `contains` and `matches`: disallow use of both for now - we can then revisit the decision later
