### ISSUE TITLE
Add dependabot where it's convenient?

### ISSUE THREAD

**Issue by Michael1993** [junit-pioneer/junit-pioneer#315]
Basically the title. @aepfli mentioned this in Discord and I think it warrants a proper discussion.

**Comment by aepfli** [comment]
maybe also for gradle build dependencies and for github action updates?

**Comment by Bukama** [comment]
I'm strongly voting **against** Dependabot. We decided to choose our dependencies manually and by purpose we don't use the least versions.

So a spamming tools who creates countless of spamming issues or pull requests, which we all auto-close because we don't want to upgrade is non-sense and only bloats tons of shit.

**Comment by beatngu13** [comment]
@Bukama I think one have to differentiate between critical / production code dependencies such as JUnit—where we indeed want to hand-crafted updates—and non-critical / test code dependencies like AssertJ. For the latter, I find tools like dependabot very useful for two main reasons:

* One doesn't have to manually trigger tooling such as the [Gradle Versions Plugin](https://github.com/ben-manes/gradle-versions-plugin) (or is there a sensible workflow to automate this?)

* One also gets infrastructure updates for e.g. GitHub Actions

Plus: it is super easy to have a [whitelist](https://dependabot.com/docs/config-file/#allowed_updates) or a [blacklist](https://dependabot.com/docs/config-file/#ignored_updates). Therefore, there is no spamming unless you fuck up the configuration. 😉

So when it comes to updating non-critical dependencies, what is more comfortable than getting notified via a PR that is (most of the time) ready to be merged?

**Comment by Bukama** [comment]
Assigned to @nicolaiparlog to judge as founder

**Comment by signed** [comment]
There already is a PR to [add dependabot to convert-junit4-to-junit5](https://github.com/junit-pioneer/convert-junit4-to-junit5/pull/18).

**Comment by beatngu13** [comment]
@signed thx for the link, I wasn't aware of that one.

As pointed out by @Bukama, there is no common POV so far. So I guess we shouldn't merge anything Dependabot-related in any Pioneer repo until we / @nicolaiparlog decided how to proceed.

**Comment by nicolaiparlog** [comment]
As I see it, dependabot comes with a cost and a benefit:

* cost: adds issues/PRs that must be dealt with (who said "annoying"?!)
* benefit: prevents outdated dependencies

For a project that is as loosely maintained as ours, I consider the cost to be non-negligible. The benefits, otoh, seem somewhat negligible:

* only one run-time dependency that we keep purposely "outdated" (the smallest minor version that supports our feature set)
* build-time dependencies are mostly test-related
* JUnit Pioneer is used during testing, so I assume it is removed from the app's attack surface

**Comment by nicolaiparlog** [comment]
I was told, that dependabot also updates Gradle and GitHub Actions. They have access to our secrets here on GitHub, so keeping them up-to-date is relevant for us.

A teensy bit of research unearthed two nice features:

* accept/block lists, so we could exclude JUnit 5 dependencies
* non-live updates (e.g. weekly/monthly) to reduce number of PRs

This convinced me to give dependabot a try if we configure it as described above. I vote for monthly PRs, so we can work through all of them at once.

**Comment by nicolaiparlog** [comment]
Since I need to act as a tiebreaker, I'm voting for a dependabot trial. :)

**Comment by aepfli** [comment]
i am not sure, that this is closed based on https://github.com/dependabot/dependabot-core/issues/2280 :D not gradle kotlin dsl support

**Comment by beatngu13** [comment]
Yeah, currently GHA updates only. 🤷‍♂️
