### ISSUE TITLE
Evaluate to rename master branch to main

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#331]
We want to evaluate to rename the master branch to main branch.
Is there support on Github or do we have to do it locally and push it.

Github Actions would need to be updated (also in site repo)

**Comment by nicolaiparlog** [comment]
Thanks for creating this, Bish. I checked with GitHub and [they say](https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-):

> By the end of the year, we'll make it seamless for existing repositories to rename their default branch.

Let's wait for that.

**Comment by nipafx** [comment]
I just renamed `master` to `main` and (as promised) GitHub does all the required things on this site. I also changed all references to the branch in  dba26da. All that's left to do is [updating your local clones](https://docs.github.com/en/github/administering-a-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes).
