### ISSUE TITLE
Move Rerunner-Jupiter/improve RetryingTest?

### ISSUE THREAD

**Issue by Michael1993** [junit-pioneer/junit-pioneer#355]
Here is a really nice extension of JUnit: [rerunner-jupiter](https://github.com/artsok/rerunner-jupiter).

Has not been updated in ~9 months. _**If the author agrees**_ I think we should take on this extension.
I think the extension itself fits in nicely with our other extensions but I'm not sure what the proper etiquette is when merging open-source projects. Is that even a thing? Is it rude to even consider it? Someone help me out here. :sob:

@nipafx , @Bukama , @aepfli Please give feedback.

Edit: Looking at the commit history it seems the author works on the extension in bursts. For example there is a bit of a gap between 2019-07-02 and 2020-01-10.

**Comment by Michael1993** [comment]
It is really similar to `@RetryingTest`, but in some ways it offers more, in other ways much less. Maybe not move it Pioneer but extend `RetryingTest`? 🤔

**Comment by beatngu13** [comment]
@Michael1993 would you mind summarizing the pros and cons compared to `@RetryingTest` from your POV?

**Comment by Michael1993** [comment]
I'll compare the two properly this evening and get back to you.

**Comment by Michael1993** [comment]
Comparison (I'll edit this as I explore the feature):

1.) `rerunner-jupiter` allows more fine-grained control than `@RepeatedTest`, by allowing you to retry only for specific exceptions. [Strangely enough it does not seem to work with `Error`, however.](https://github.com/artsok/rerunner-jupiter/issues/56)

This always works, even though I only wanted the test to try again if it found a `FileNotFoundException`
```
static int counter = 0;

@RepeatedTest(3)
void test() {
  if (counter == 0) {
    counter = 1;
    throw new ExportException("I expected a FileNotFoundException. 😭 ");
  }
}
```

In `rerunner-jupiter` this test would look like:
```
static int counter = 0;

@RepeatedIfExceptionsTest(repeats = 3, exceptions = FileNotFoundException.class)
void test() {
  if (counter == 0) {
    counter = 1;
    throw new ExportException("I expected a FileNotFoundException. 😭 ");
  }
}
```

This fails! Hooray?

**Comment by Bukama** [comment]
I think we can improve our extension, but I don't see that we move the `rerunner-jupiter`. To comment your points

1) I don't like the fact that the `rerunner-jupiter` does not work with `AssertJ`. `AssertJ` is the best assertion framework in my opinion. Not supporting it is a no go.

2) I like the possibility that `rerunner-jupiter` works with parameterized tests. We should have a look to evolve our extension.

3) I like the `suspend()` functionality, but it should be an opt-in feature, to keep runs fast.

4) I really like the functionality to add a number the tests has to passed, so you can make flaky tests at least somehow more stable. Also as an opt-in.

5) We should keep an eye on the runs, meaning we should avoid runs that are skipped, but stop the tests when it passed.

At the end: Before doing any implementation we should reach out for the maintainer to ask if it's okay for him (didn't check what Apache v2 licences means for usage).

**Comment by Michael1993** [comment]
Sidenote for improving `RetryingTest`:
We should (probably) migrate to [`AssertionFailedError`](https://ota4j-team.github.io/opentest4j/docs/1.0.0/api/org/opentest4j/AssertionFailedError.html) from [`AssertionError`](https://docs.oracle.com/javase/7/docs/api/java/lang/AssertionError.html).

**Comment by Bukama** [comment]
As @Michael1993 and me like to improve this extension I'll updated the labels

**Comment by nipafx** [comment]
Good points by @Michael1993 and I 100% agree with @Bukama. Let's do it!

I think it would be a good idea to create a new issue for each of the following changes:

* improve interaction with [other test templates](https://junit-pioneer.org/docs/retrying-test/#combining-retryingtest-with-test-et-al) 
* allow defining exceptions for which to retry
* offer `suspend`-like attribute to configure pauses between reruns
* offer `minSuccess`-like attribute to configure how often a test has to pass in total (could this or another attribute be in percentages, i.e. "run the test `n` times and stop once `p`% of them pass"?)

The last three could be _good first issues_, but `@RetryingTest` is not the most trivial extension. 😉 

I propose to close this issue as soon as the other four were created.

**Comment by Michael1993** [comment]
New issues created, closing this.
