### ISSUE TITLE
Extend CartesianProductTest$Sets#add

### ISSUE THREAD

**Issue by beatngu13** [junit-pioneer/junit-pioneer#358]
Consider the case where one wants reuse a method inside several Cartesian product factory methods:

```java
static CartesianProductTest.Sets someFactoryMethod() {
    return new CartesianProductTest.Sets()
        .add(reusedMethod())
        .add(false, true);
}

static CartesianProductTest.Sets anotherFactoryMethod() {
    return new CartesianProductTest.Sets()
        .add(reusedMethod())
        .add("foo", "bar");
}

static Object[] reusedMethod() {
    return new Object[]{new Object(), null};
}
```

Since `CartesianProductTest$Sets#add` currently only accepts `Object...`, `reusedMethod` must return an array.

I think it would be helpful to have more ways to `add` to a Cartesian set, e.g.:

```java
public Sets add(Object... entries) {
    sets.add(toDistinctList(Arrays.stream(entries)));
    return this;
}
 
public Sets add(Collection<Object> entries) {
    sets.add(toDistinctList(entries.stream()));
    return this;
}

private static List<Object> toDistinctList(Stream<Object> stream) {
    return stream.distinct().collect(toList());
}
```

I have already created a branch in my fork for this, but beforehand I would like hear what's your say on this? And/or do you have other `add` signatures in mind?

**Comment by Bukama** [comment]
We should support the possibility to reduce / avoid code duplication.

**Comment by Michael1993** [comment]
I agree, it looks good. I'd say go ahead with a PR for it.
