### ISSUE TITLE
Upgrade to Gradle 6.7 and add Java 15 to build workflow

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#359]
Gradle 6.7 is out and now supports Java 15, so we could use Java 15 in our latest main build, like @beatngu13 tried in #339

https://docs.gradle.org/6.7/release-notes.html

I assign this to @beatngu13 to revive this PR if he want :)

**Comment by aepfli** [comment]
Furthermore, we can use the tool chain feature to test with unreleased java
versions easily.
