### ISSUE TITLE
Create @DisabledUntil

### ISSUE THREAD

**Issue by nipafx** [junit-pioneer/junit-pioneer#366]
Disable tests until a certain date/time - see [comment in #219](https://github.com/junit-team/junit5/issues/219#issuecomment-226761964)).

(Spawned from #1.)

**Comment by vlsi** [comment]
+100500

I believe, `untilDate` must be a required parameter so developers don't accidentally forget about disabled tests.

Real-life case:
1) A fix introduces a regression, so one of the property-based tests was disabled: https://issues.apache.org/jira/browse/CALCITE-3457?focusedCommentId=16972437&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16972437
2) It was fine then since it looked like a small corner case. Unfortunately, everybody missed to analyze the root cause, so the bug is present for more than a year
3) As a consequence, the property-based test has been disabled for the full year, so it missed to identify regressions.

I believe we could have prevented the regressions if the initial `@Disabled` was like `@Disabled(until = "2019-11-26")`

**Comment by Bukama** [comment]
I also see use cases for this and it's obvious for me, that the parameter is a required parameter.
 For the parameter itself I would like to see, that it must be an [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) string , therefore: `yyyy-MM-dd` (like @vlsi wrote). This saves everyone from mixing the metric systems of US/non-US etc.

I also think we should add a maximum, so that it's not possible to set something to literally disable a test until forever. I think one, three or six months (six would match the Java release cycle) as an absolute maximum should be enough to enforce the user to investigate. I think I would go with a maximum of three, one may be too short, whereas six is quite long.

**Comment by Michael1993** [comment]
Imagine the following scenario:
```java
@Test
@DisableUntil(date = "1999-12-31")
void test() {
  // passing test
}
```

The test *should* pass - but there is an outdated annotation on it, so maybe it should fail with the message: "Please remove or update the `@DisableUntil` annotation."?

**Comment by Bukama** [comment]
Can we someone "watchable" print warnings?

**Comment by Michael1993** [comment]
We could do one of the following:
* publish a report entry
* print on `System.out`
* take an optional `Class<? extends Writer>` parameter we instantiate and call `write()` there?

**Comment by Bukama** [comment]
> We could do one of the following:
> 
> * publish a report entry

Gets lost in nowhere as long as the user does not uses an TEL which reports / logs the published `ReportEntries` to somewhere, where the user sees it

> * print on `System.out`

Better than nothing. 🤷‍♂️

**Comment by beatngu13** [comment]
> 
> 
> > We could do one of the following:
> > 
> > * publish a report entry
> 
> Gets lost in nowhere as long as the user does not uses an TEL which reports / logs the published `ReportEntries` to somewhere, where the user sees it

This is what we do for warnings in [`EnvironmentVariableExtension`](https://github.com/junit-pioneer/junit-pioneer/blob/master/src/main/java/org/junitpioneer/jupiter/EnvironmentVariableExtension.java#L51).

If we consider this as not effective, I suggest to change it there (and elsewhere) too.

**Comment by Michael1993** [comment]
I know IntelliJ "listens" to report entries. I think that's a good enough solution, considering the only downside is a single line of dead code - probably not worth failing the test.

Another thing to consider: How do you test such an extension? You can test that it disables tests in the future (e.g.: 2999-12-31) and that it does not disable tests in the past (e.g.: 1984-12-31), is that good enough?

**Comment by Bukama** [comment]
> I know IntelliJ "listens" to report entries. I think that's a good enough solution, considering the only downside is a single line of dead code - probably not worth failing the test.

So you want to force every user of Pioneer to use IntelliJ?

**Comment by Michael1993** [comment]
Yes. 😈

But that's not the point - the point is that it does not matter if the info gets lost because it's just a mild warning *at worst*. IntelliJ was just an example.

**Comment by Bukama** [comment]
If nobody can read the warning...

**Comment by nipafx** [comment]
> I also see use cases for this and it's obvious for me, that the parameter is a required parameter.

Not sure whether it should be required (although I lean that way), but in any case, we should consider adding this parameter to all our disabling extensions.

> For the parameter itself I would like to see, that it must be an [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) string , therefore: `yyyy-MM-dd` (like @vlsi wrote). This saves everyone from mixing the metric systems of US/non-US etc.

👍🏾 

> I also think we should add a maximum, so that it's not possible to set something to literally disable a test until forever. I think one, three or six months (six would match the Java release cycle) as an absolute maximum should be enough to enforce the user to investigate. I think I would go with a maximum of three, one may be too short, whereas six is quite long.

I'm not so sure about putting a hard limit on this, particularly such a short one. I understand the sentiment, but I'm not sure it does more than annoy users to no end. What we could do, though, would be to write to `System.err` - that may get their attention.

**Comment by nipafx** [comment]
As I see it, these are open questions:

General behavior:

1. Is there a limit on how far into the future the date can be?
2. If yes, what do we do if the date is beyond that?
3. What do we do if a test's disabled date is in the past?
    * fail the test?
    * emit a warning on `System.out`, `System.err`, or as report entry?

Re extensions:

1. Do we create `@DisabledUntil`?
2. Do we add this parameter to all our disabling extensions?
3. Will it be required?

**Comment by nipafx** [comment]
My current opinion (still young, so may change:

General:

1. I'm torn
2. Failing seems to be the only valid response. Or does it?
3. Definitely a report entry - not sure about anything else.

Extensions:

1. Yes
2. Yes
3. Possibly

**Comment by nipafx** [comment]
After a few months of not thinking about this, I settled on the following:

General:

1. Don't limit how far in the future the date can be. Nobody's forced to use `@DisabledUntil`, so if the limit bothers them, they'll just use `@Disabled` and nobody wins.
2. n.a.
3. Emit a warning as a report entry. (We can always make this stricter.)

Extensions:

1. Create an extension `@DisabledUntil`, where the `value` attribute takes an ISO 8601 date string.
2. Add an `until` attribute to other disabling extensions where it makes sense.
3. No. (for now; related, see [this Twitter poll](https://twitter.com/nipafx/status/1389266334333251584))

Since a few annotations will share the same logic, some time should be invested into how to best reuse and test that, so it's not duplicated across various extensions.

**Comment by gdiegel** [comment]
Hi @nipafx,

I'd love to contribute this feature. I have the implementation basically ready to go, all that's missing is the documentation in AsciiDoc. What do I need in order to be able to push my feature branch?

Thanks and best regards,
Gabriel

**Comment by nipafx** [comment]
Hi @gdiegel, thanks for taking this on! 👍🏾 And sorry for not getting back to you sooner. I'll check the PR in a minute. Just one request: Please don't include the issue number in every commit as it will create a lot of noise here (see above). Thanks! :)
