### ISSUE TITLE
Wrap @SetEnvironmentVariable in a JUnit Extension

### ISSUE THREAD

**Issue by spartanhooah** [junit-pioneer/junit-pioneer#373]
We have a few JUnit test classes that need to bring up the Spring context, and due to some Kafka libraries, we need to set an environment variable in order for the context to successfully load. Would it be possible to wrap the annotation in a JUnit Extension so we only need to put the particular code for the environment variable setting in one place? That way we can just add our custom extension to `@ExtendWith` wherever it's needed.

**Comment by beatngu13** [comment]
I'm not that familiar with Spring, but what kind of Spring application do you have and how do you set up the context in your tests (e.g. via `@SpringBootTest`)?

In general, the environment variable extension also implements [`BeforeAllCallback`](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/BeforeAllCallback.html) and can be applied at the class level as well. So you could, for instance, create an abstract base class for your the aforementioned tests and put the corresponding `@ClearEnvironmentVariable`/`@SetEnvironmentVariable` there:

```java
@ClearEnvironmentVariable(/* ... */)
@SetEnvironmentVariable(/* ... */)
abstract class MySpecialSpringKafkaTest { }
```

Does this help?

**Comment by Bukama** [comment]
You could also create a [TestExecutionListener](https://junit.org/junit5/docs/current/api/org.junit.platform.launcher/org/junit/platform/launcher/TestExecutionListener.html) and use it's `executionStarted​` (called before a test container / method is executed) or the `testPlanExecutionStarted` (called before the `TestPlan` is executed) callback to set the values there.

**Comment by spartanhooah** [comment]
It's a Spring Boot application, so the test classes in question have the `@SpringBootTest` annotation. We thought about doing an inheritance thing, but decided against it. I'll look into @Bukama's suggestion of a TestExecutionListener and see what comes of it.

**Comment by spartanhooah** [comment]
Hmm, not sure what I'm doing wrong with the `TestExecutionListener`. Here's the implementation of that interface:
```
package com.company.thing;

import org.junit.platform.launcher.TestExecutionListener;
import org.junit.platform.launcher.TestPlan;
import org.junitpioneer.jupiter.SetEnvironmentVariable;

public class TestEnvironmentSetter implements TestExecutionListener {
    @Override
    @SetEnvironmentVariable(key = "KAFKA_RUNTIME_ENV", value = "dev")
    public void testPlanExecutionStarted(TestPlan testPlan) {}
}
```

Is the `@SetEnvironmentVariable` annotation supposed to work here? I've tried it on the method and on the class, but I keep getting the same Gradle error, `No tests found for given includes: [fully-qualified test method]`.

**Comment by Bukama** [comment]
@spartanhooah I don't know if the extension works here, I don't think so.

But I mean something like this. I've created something similar like this in a scenario where I wanted to set some "global" properties at the begin of the general execution (not of the tests of a single class), much like passing it via `-D...`, but I didn't want to pass them all via CLI.

```
package configuration;

// Imports


public class ConfigTEL implements TestExecutionListener {

  @Override
  public void testPlanExecutionStarted(TestPlan testPlan) {
    System.setProperty("key", "value");

  }
```

To activte it, just must register it by creating a file `org.junit.platform.launcher.TestExecutionListener` under `src/main/resources/META-INF/services` and put the full name of the implementing class in in (here `configuration.ConfigTEL`).

**Comment by spartanhooah** [comment]
@Bukama Properties are different than environment variables though, aren't they? I don't have `System.setEnv()`.

**Comment by beatngu13** [comment]
>We thought about doing an inheritance thing, but decided against it.

@spartanhooah is there a particular reason why you decided against it? Sure, in general inheritance in test code should be avoided (e.g. to keep tests simple), but there are exceptions where it can be sensible. Also, from the top of my head, I cannot think of another way to address your use case with Pioneer's environment variable extension.

>You could also create a TestExecutionListener […]

@Bukama hmmm, I also don't how `TestExecutionListener` could help here? The environment variable extension is only applicable to test classes and methods, and there is no `System#setenv`; even if there would be, this way one cannot leverage the extension's backup mechanism (save and restore the state before the test).

**Comment by spartanhooah** [comment]
@beatngu13 Mostly just a distaste of inheritance in test classes. I'll run it by the rest of the team; it was just me and one other team member making the decision.

**Comment by Bukama** [comment]
> > You could also create a TestExecutionListener […]
> 
> @Bukama hmmm, I also don't how `TestExecutionListener` could help here? The environment variable extension is only applicable to test classes and methods, and there is no `System#setenv`; even if there would be, this way one cannot leverage the extension's backup mechanism (save and restore the state before the test).

I mixed up system env and system props...

@nipafx and I were talking about this issue some hours ago and we were thinking about providing some way to be able to set default values for all of our extensions, when those values are needed for the whole test plan (and not only a single class), but we were not quite sure if there a useful use cases (oh man I'm too tired)

**Comment by Michael1993** [comment]
JUnit Pioneer also works with meta-annotations, so I think this *should* (not tested it myself, yet) work:

```java
@SetEnvironmentVariable(/*...*/)
class MyCustomJUnitExtensionForKafkaAndSpring {
  // implement your additional logic here
}
```

Then, in your test class:
```java

@Test
@ExtendWith(MyCustomJUnitExtensionForKafkaAndSpring.class)
void testSomeLogicHere() {
  // environment variable should be set (I think)
}
```

If you are not particularly in a hurry to implement these tests, give me a day or two and I'll check if this actually works.

**Comment by Michael1993** [comment]
Okay, so, I tested it. It kind of works but not as I originally wrote. Here is what you need to do:
1. Create your extension:
```java
public class MyKafkaExtension implements BeforeEachCallback {
    // extension logic here
}
```
2. Create a composed annotation:
```java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
@ExtendWith(MyKafkaExtension.class)
@SetEnvironmentVariable(key = "foobar", value = "barfoo") // you reference SetEnvironmentVariable here!!!
public @interface KafkaExtension {
}
```
3. Use the composed annotation in your test classes:
```java
@Test
@KafkaExtension
void testUsingKafkaEnvVar() {
  // Invokes both MyKafkaExtension and the EnvironmentVariableExtension
}
```

This is a bit unfortunate, because you *have to* use `@ExtendWith` indirectly, but (in my opinion) it also looks somewhat nicer?

@spartanhooah Let us know if this solution works for you.

**Comment by beatngu13** [comment]
@Michael1993 thx for this, extensions FTW!

If no additional logic is needed, one can also omit `MyKafkaExtension`.

Composed annotation:

```java
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@SetEnvironmentVariable(key = "FOO", value = "bar")
public @interface KafkaTest { }
```

Actual test:

```java
@KafkaTest
class MyKafkaExtensionTest {

	@Test
	void test() {
		assertThat(System.getenv("FOO")).isEqualTo("bar");
	}

}
```

**Comment by spartanhooah** [comment]
Thanks, that works great! I can use @beatngu13's suggestion since I don't have any other logic I need to inject.
