### ISSUE TITLE
Create integration test for @Issue extensions

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#375]
While trying to write an integration test for the `IssueExtension` it seems to turn out that the `TestKitEngine` does not pick up the globally registered `TestExecutionListener` and delegates published `ReportEntries` to it.

Maybe useful links:
https://github.com/junit-team/junit5/pull/2006/files

**Comment by nipafx** [comment]
From the comment in code:

It would be nice to run the nested test class with the `PioneerTestKit` (as usual), then get the created `IssueTestSuite`s and assert the expected results. Unfortunately, we couldn't make the launched engine use our `TestExecutionListener` (not even adapted as `EngineExecutionListener`) and so it wouldn't gather the report entries nor get called when the test kit run finished. Hence, we're not able to write a proper integration test for this extensions. Instead we have to rely on the occasional visual verification that it works - the `StoringIssueProcessor` prints the gathered information to `System.out`.

**Comment by nipafx** [comment]
Blocked by junit-team/junit5#2480.

**Comment by nipafx** [comment]
[Marc Philipp replied](https://github.com/junit-team/junit5/issues/2480#issuecomment-734793391) - TL;DR: No changes to existing APIs will be made, but we may be able to use the `Launcher` API to get what we need.
