### ISSUE TITLE
Untangle `CartesianProductTestNameFormatter` from `ParameterizedTest`

### ISSUE THREAD

**Issue by Michael1993** [junit-pioneer/junit-pioneer#382]
`CartesianProductTestNameFormatter` uses things that belong to `ParameterizedTest`:
 - `DISPLAY_NAME_PLACEHOLDER`
 - `INDEX_PLACEHOLDER`
 - `ARGUMENTS_PLACEHOLDER`

Perhaps it should not, even if it is unlikely these will change in the future.

**Comment by Bukama** [comment]
Could you describe this a bit more? Does it use JUnit internals?

**Comment by Michael1993** [comment]
> Does it use JUnit internals?

Kind of?

It uses the placeholder constants declared by `ParameterizedTest` - since that's a public (annotation) interface its members are also public. That does not mean they are stable at all.

**Comment by Bukama** [comment]
Ah I see.
Yeah let's move it into the class itself, so it does not depend on it.
