### ISSUE TITLE
Handle duplication of PioneerAnnotationUtils

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#389]
_by @Michael1993 _

PioneerAnnotationUtils is currently not public, but is used by
multiple classes in different packages. Previously, we created
a copy of the class with reflection magic, which is a fragile
approach. This PR introduces a test, that checks (and copies) the
PioneerAnnotationUtils in different packages. The test fails if
the classes don't match.

**Comment by nipafx** [comment]
Let's start with the requirements for `PioneerUtils` and `PioneerAnnotationUtils`:

* reachable within Pioneer from different packages
* as unreachable as possible for Pioneer users

1. For users who use the module system, the obvious approach would be to put the classes into their own non-exported package and make them public. Users without modules will then be able to use the class, so it still needs to loudly inform them that they're not supposed to do that.
2. The current approach is to have one original version of the class and one duplicate with the same method signatures, but without the bodies - instead reflection is used to execute the method from the original. Feels like an eldritch horror to some.
3. PR #388 "proposes" (in jest, I hear) a single original that is copied into another package during tests (of all phases). While I appreciate the ingenuity 😁, it doesn't convince me as a long-term solution.

So... number 1, then? Create a package `org.junitpioneer.internal`, put them and a bunch of warnings in there?

**Comment by nipafx** [comment]
I created #403, which implements 1. - let me know what you think.
