### ISSUE TITLE
Move TemporaryFolderExtension to pioneer

### ISSUE THREAD

**Issue by smoyer64** [junit-pioneer/junit-pioneer#39]

**Comment by jbduncan** [comment]
Am I right to think that TemporaryFolderExtension writes and reads files/directories to and from the physical filesystem?

If so, should we encourage people to use things like jimfs (which does stuff in-memory) instead?

**Comment by jbduncan** [comment]
I'd understand if it's not practical because people need to migrate existing humongous JUnit 4 tests suites to JUnit 5. :)

**Comment by mkobit** [comment]
Would love to see this one - I constantly finding myself copy and meeting that into my repositories

**Comment by nicolaiparlog** [comment]
I'm slowly inching towards having all the infrastructure set up, so we can finally start making some releases. Once that's done we can all try to hustle @smoyer64 into working on this. :wink:

**Comment by mkobit** [comment]
Awesome @nicolaiparlog ! Haven't had a chance yet to really contribute anything here (yet). Let me know if there are any issues you are looking to get help with!

**Comment by finsterwalder** [comment]
There is already a working TemporaryFolderExtension to start from:
https://github.com/junit-team/junit5/blob/master/platform-tests/src/test/java/org/junit/jupiter/extensions/TempDirectory.java
It might need some brushing up or could probably need some tests, in particular with corner cases.
How could we integrate that into junit-pioneer?

**Comment by marcphilipp** [comment]
@smoyer64 If it's okay with you, I'd like to start working on this one.

**Comment by smoyer64** [comment]
SGTM

**Comment by marcphilipp** [comment]
> Somewhere around here I have a copy of the JUnit 4.12 ''TemporaryFolder'' rule that I adapted to an extension then I realized there was already one used within the tests.

I actually rewrote it and submitted a PR. Looking forward to your feedback on #69. 🙂 

> Will junit-pioneer become a test dependency in JUnit (seems a bit too circular but I have an AsciidocExtension you might find compelling too).

Not sure about that one, yet. It would work, but we probably don't need it. 😉

**Comment by nicolaiparlog** [comment]
For the record: Great that this is making progress, thanks @marcphilipp! :+1:
