### ISSUE TITLE
Dependabot triggers sonarqube on forks, commenting on closed issues

### ISSUE THREAD

**Issue by aepfli** [junit-pioneer/junit-pioneer#396]
Our current sonarqube implementation/usage is a little bit flacky.

There are two issues:
1. we can not share secrets with forks, thats why we checked in the sonar token within the code (this is still bad, and we need to address this as pointed out by @beatngu13 )
2. due to this, and the configuration forks will also do sonar analysis and upload the result to the same project. This is bad as it leads to comments on already closed tickets like #5 

We do have multiple options regarding this.

1. we could change the sonar project key to be determined by the Repository name, instead of a hardcoded value. This would allow projects to still analyse the project, if they first create it. But we would not have those comments (i see this as a win). We would need to use the environment variable from GitHub Action (if present), transform it into a valid project key (replace `/` with `_`) and we should be good to go.
   - https://github.com/junit-pioneer/junit-pioneer/blob/master/build.gradle.kts#L102 
   - https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables
2. The secret part is more tricky. As this is not supported by GitHub Action. We could change  the process of the sonarqube analysis. so we trigger the analysis by a different user - and just the analysis. As this seems to be a not so trivial task, we might create an own issue to start thinking about a solution. Still this infromation is relevant in here.

This relates to 
https://github.com/dependabot/dependabot-core/issues/2804 as dependabot and forks, are still a problem, because all of them will receive pull requests if default configuration is applied, and nobody took care about the security

**Comment by Bukama** [comment]
> But we would not have those comments (i see this as a win). 

As stated in Discord, they are redundant anyway, as the check is listed beneath the "checks" section. So less spam - welcome!

As of dependabot: I'm still against using this spambot, which creates conflicting PR and own labels (but maybe we can disable / change that).

**Comment by beatngu13** [comment]
SonarCloud's comments can be [disabled via the UI](https://community.sonarsource.com/t/disable-github-merge-request-comments/18520/23). @aepfli would you mind checking this out?

Regarding SonarCloud and forks, I'd go with the default way, i. e. no code analysis in that case. I know this is not ideal, but (i) IMHO less problematic than our current setup and (ii) there is already a [feature request](https://jira.sonarsource.com/browse/MMF-1371) for this.

When it comes to Dependabot, I really don't consider monthly dependency updates as spam. It surely is annoying that fork handling is not good at the moment, but again, there is also an issue for this as pointed out by Simon.

**HOWEVER** @Bukama, I saw your heavy swearing in Discord. If you dislike Dependabot that much, I'm OK with disabling it until the aforementioned issue has been addressed. ✌️

**Comment by Bukama** [comment]
_ #400 shows the configuration for using our own labels is working_

**Comment by beatngu13** [comment]
> SonarCloud's comments can be [disabled via the UI](https://community.sonarsource.com/t/disable-github-merge-request-comments/18520/23). @aepfli would you mind checking this out?

Friendly reminder @aepfli ... 😉 (This can't be done via the REST API, otherwise I would try doing it myself.)

**Comment by beatngu13** [comment]
https://github.com/junit-pioneer/junit-pioneer/commit/535539651870e1e2e4d9c3878ab9a87748130c4e removed Dependabot, so this issue is obsolete.

(@aepfli I still think we should [disable SonarCloud comments](https://community.sonarsource.com/t/disable-github-merge-request-comments/18520/23) since we have a corresponding status check.)

**Comment by aepfli** [comment]
@beatngu13 done! disabled comments on Sonarcloud
