### ISSUE TITLE
Change mockito-core dependency when updating to Java 16+

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#397]
From [Twitter](https://twitter.com/MockitoJava/status/1345281603174543361):

> Please be aware of future JDK releases that can break your test if you are using `mockito-core`. Mockito is ready for the future with the `mockito-inline` artifact, which enables the future-proof inline mockmaker. We recommend switching the artifact if you run into these issues.

Related [mockito issue](mockito/mockito#2164)

**Comment by beatngu13** [comment]
We can already switch to `mockito-inline`, PR incoming … however, let's bear in mind:

>Be aware that this artifact may be abolished when the inline mock making feature is integrated into the default mock maker.

https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#mockito-inline

>Note that this artifact is likely to be discontinued once mocking of final classes and methods gets integrated into the default mock maker.

https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#Mocking_Final

**Comment by nipafx** [comment]
From what I gather from your comments and the few bits of documentation I read, I don't think we need this. We don't mock final classes, etc. and I'm not planning to. Also, using the instrumentation API to attach to "yourself" is iffy. Finally, "this artifact may be abolished" sounds like more hassle down the line. I'll close this issue and the PR. We can reopen if/when we actually need this functionality.
