### ISSUE TITLE
Improve `@RetryingTest`: interaction with other test templates

### ISSUE THREAD

**Issue by Michael1993** [junit-pioneer/junit-pioneer#405]
Related to: #355 

`@RetryingTest` should support parameters.

**Comment by Josheek1** [comment]
Is there a way to utilize Junit's @BeforeEach and @AfterEach annotations with Pioneer's RetryingTest?
As a workaround, we are currently calling those methods from within the tests.

**Comment by nipafx** [comment]
JUnit's Jupiter engine executes lifecycle methods for tests that use the test template extension point. Jupiter's own parameterized tests use that and so do Pioneer's retrying tests. That means `@BeforeEach` and `@AfterEach` work out of the box.

That means, this...

```java
class RetryingTestLifecycleTests {

	private int executionCount;

	@BeforeEach
	void printsHello() {
		System.out.print("Hello, ");
	}

	@RetryingTest(3)
	void failsOnlyOnFirstInvocation() {
		System.out.println("World!");
		executionCount++;
		if (executionCount == 1) {
			throw new IllegalArgumentException();
		}
	}

}
```

... prints "Hello, World!" twice - once for each test execution.

**Comment by marcphilipp** [comment]
Hey, sorry for the delay in answering the summons. 🙂 

Unfortunately, I also don't see how we can make this work with the current extension points.

**Comment by nipafx** [comment]
Thank you, @marcphilipp! In light of your reply, I'll close this issue but if new ideas come up, they can be added here of course.

**Comment by nipafx** [comment]
This vote requires a proposal for how to implement it. 😉

**Comment by nipafx** [comment]
@gredwhite This vote requires a proposal for how to implement it. 😉
