### ISSUE TITLE
Improve `@RetryingTest`: allow defining exceptions for which to retry

### ISSUE THREAD

**Issue by Michael1993** [junit-pioneer/junit-pioneer#406]
Related to #355 

User should be able to specify to `@RetryingTest` what exceptions are acceptable to retry the test for. E.g.:
```java
@RetryingTest(value = 3, exceptions = IOException.class)
void failingTest() {
  throw new IOException(""); // should run 3 times
}

@RetryingTest(value = 3, exceptions = IOException.class)
void failingTest() {
  throw new IllegalArgumentException(""); // should run once
}
```

**Comment by nipafx** [comment]
Instead of `exception`, please name the attribute `retryFor`. This gives us the opportunity to later define something like `failFor` (i.e. retry for all exceptions except the named ones).
