### ISSUE TITLE
Allow CartesianProductTest factory method to be placed outside of test class

### ISSUE THREAD

**Issue by rpost** [junit-pioneer/junit-pioneer#412]
When using junit 5 `@MethodSource` it is possible to define factory method as "my.package.Class#factoryMethod".

The same factory method definition used with `@CartesianProductTest` makes it complaining about missing method.

It would be great to have possibility to use method from different than test case class, as it is supported within `@MethodSource`.

**Comment by Michael1993** [comment]
Sounds good. I'll investigate sometime before next Tuesday.
