### ISSUE TITLE
Improvements for @CartesianEnumSource

### ISSUE THREAD

**Issue by Michael1993** [junit-pioneer/junit-pioneer#414]
JUnit introduced a new feature to `@EnumSource` - it does not require you to specify your enum class if it can be intuited from the type of the test method parameter. For example:

```java
@ParameterizedTest
@EnumSource
void test(ChronoUnit unit) {
    // some passing test code
}
```

Investigate if the same behaviour could be implemented with `@CartesianEnumSource` (once #409 is merged).

**Comment by scordio** [comment]
Supporting a single `@CartesianEnumSource` might be straightforward with small adjustments of the latest JUnit `EnumArgumentsProvider` code. The challenge I see is when there are many `@CartesianEnumSource`, e.g.:

```java
@CartesianProductTest
@CartesianValueSource(ints = { 1, 2, 3 })
@CartesianEnumSource
@CartesianValueSource(ints = { 4, 5, 6 })
@CartesianEnumSource
void moreParams(int i, ChronoUnit cUnit, int j, MyEnum myEnum) {
  // some test code
}
```

How I would expect this to work is that the first `@CartesianEnumSource` provides all the values of `ChronoUnit`, while the second provides all the values of `MyEnum`.

To do that, the `CartesianEnumArgumentsProvider` would need to understand the relative index of the current annotation instance and fetch the type of the corresponding `Enum` parameter. I think this can be done with some reflection and I will look into it, but please let me know if you have any other ideas.
