### ISSUE TITLE
Prepare hack.commit.push

### ISSUE THREAD

**Issue by nipafx** [junit-pioneer/junit-pioneer#431]
Things we need to do before [hack.commit.push](https://hack-commit-pu.sh/):

* [ ] short video introduction of the project
* [x] link to a guide on how to create JUnit 5 extensions
* [x] make sure the _good first issue_ and _up for grabs_ labels are properly applied

Things we could do:

* [x] rename `master` to `main` ~> #331
* [x] update dependency on JUnit to prevent problems if updating becomes necessary during the event
* [x] add existing extension ideas (e.g. from [JUnit 5's issues](https://github.com/junit-team/junit5/issues?q=label%3A%223rd-party%3A+Pioneer%22)) as issues

**Comment by nipafx** [comment]
Regarding the JUnit 5 version we depend on:

We usually want to depend on the lowest minor version (newest patch of that) that supports our feature set. Generally speaking, that's still the case, but the upcoming hack.commit.push event required an exception. Updating from Jupiter 5.6 to 5.7 requires some changes to our test code, which means it's a bit disruptive. In case some contributors need to update during the event, they would also need to make these changes in our test code, which would be an unnecessary burden. To preempt that, I decided to update to 5.7 now.

**Comment by Bukama** [comment]
Just to note it: We discussed the update in team call and we all were fine to update it.

**Comment by nipafx** [comment]
We should probably discuss how to best provide support during the event. I'll definitely be live-streaming my side of it, so coming to Twitch is one way to get in touch. Then there are the issues and pull requests here on GitHub that we can monitor and reply to. The question is, do we need more?

* We could offer a Jitsi room for people to come into and have a high-fidelity conversation with a maintainer.
* We could activate [GitHub discussions](https://docs.github.com/en/discussions/quickstart) for this project.

It might also be helpful to define one place where we expect contributors to check in occasionally in case we need to broadcast to all of them. Not sure why we'd want to do that, but it may be a good idea to at least have the option.

Other ideas or concerns regarding this?

**Comment by fbiville** [comment]
FYI, we're going to use https://workadventu.re/ for the event (it may change if we face any unexpected difficulties but that's the current plan). Every group is of course free to use its own tooling.

**Comment by nipafx** [comment]
I think that will be fine, thanks @fbiville!

**Comment by nipafx** [comment]
HCP is over now, so we've obviously done everything. 😊
