### ISSUE TITLE
SetEnvironmentVariable and SetSystemProperty interfere

### ISSUE THREAD

**Issue by Azquelt** [junit-pioneer/junit-pioneer#432]
When `@SetEnvironmentVariable` and `@SetSystemProperty` are used on the same test, only one set of properties is restored at the end of the test.

It looks like they both use `AbstractEntryBasedExtension` and that will overwrite the `EntriesBackup` for the first annotation when the second annotation is processed since it's stored in the same place in the context.

I think either the namespace or the key used to store the backup in the context needs to be derived from the implementing class.

**Comment by beatngu13** [comment]
Good catch! Will look into this.

**Comment by beatngu13** [comment]
@Azquelt feel free to comment on #433. ✌️

**Comment by nipafx** [comment]
@Azquelt Thanks for reporting this. We just released a new version that contains the fix. (Somewhat surprisingly, Shipkit picked version 1.3.8 instead of 1.3.1, so make sure to use that one.)
