### ISSUE TITLE
Move away from Bintray

### ISSUE THREAD

**Issue by nipafx** [junit-pioneer/junit-pioneer#435]
[Bintray gets shut down on May 1st](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), so we need to move away from it. I think it would be a good idea to see what other Shipkit-based projects do.

**Comment by aepfli** [comment]
https://github.com/gradle-nexus/publish-plugin/ might be a good solution, as this seems to do all the necessary steps. i will investigate further into this

**Comment by aepfli** [comment]
based on @nipafx link in discord (https://github.com/rwinch/gradle-publish-ossrh-sample) - we should evaluate if we need signing, yes it is a security feature and surely nice to have, but is it needed.

We could start with this as our first iteration and add signing at a later stage

**Comment by nipafx** [comment]
NB: The credentials for the Nexus token and the PGP key are now organization secrets, so other projects can access them as well **if** they're added to the list of projects that they're shared with.
