### ISSUE TITLE
Remove dependabot

### ISSUE THREAD

**Issue by nipafx** [junit-pioneer/junit-pioneer#443]
As dependabot is configured now, it opens a PR per update (which practically means "per dependency") per month, each of which results in a commit if merged. This means dependabot opens more PRs and makes more commits than all contributors put together. I dislike the noise in commit/PR lists and search results that come from that and want to remove it.

I really like the regular nudges towards updates, though, and think a tool that integrates with Discord or another messaging system (email?) would be nice. Letting us know there are updates, so we can create them manually.

**Comment by nipafx** [comment]
For reference, dependabot was introduced in #315.

**Comment by beatngu13** [comment]
[Dependabot is gone](https://github.com/junit-pioneer/junit-pioneer/commit/535539651870e1e2e4d9c3878ab9a87748130c4e), so I assume this can be closed?! If not, feel free to re-open.
