### ISSUE TITLE
Add @Inherited to annotations targeting ElementType.TYPE

### ISSUE THREAD

**Issue by beatngu13** [junit-pioneer/junit-pioneer#456]
See [this comment](https://github.com/junit-pioneer/junit-pioneer/issues/448#issuecomment-808577525):

> As pointed out by @Michael1993 in #449, there are more annotations – besides the environment variable and system property extensions – we should consider making `@Inherited`.
> 
> I believe this only makes sense for annotations targeting `ElementType.TYPE`, since we are dealing with test base classes. Searching for `ElementType.TYPE` yields:
> 
>     * `@DefaultLocale`
> 
>     * `@DefaultTimeZone`
> 
>     * `@Issue`
> 
>     * `@Stopwatch`
> 
> 
> Plus all the `@Reads*`/`@Writes*` annotations.
> 
> So, I tend to reopen this issue until we make the above `@Inherited`, too. What do you guys think?

As suggested by @nipafx, "one PR per extension" is preferred.

Example PR/changes for entry-based annotations (i.e. environment variable and system property extensions): #449

**Comment by beatngu13** [comment]
Side note: In contrast to #448, I labeled this issue as "enhancement" rather than "bug". IMHO the annotations/extensions basically work as expected, adding `@Inherited` is new functionality. However, in case somebody disagrees, feel free to adjust the corresponding label.

**Comment by Bukama** [comment]
I also see this as  new functionality. We need to  keep in mind that nothing gets broken, esp. `@Issue` should be carefully watched as the search for the annotation not only happens in one place.
