### ISSUE TITLE
Investigate usage of findClosestEnclosingRepeatableAnnotations in EnvironmentVariableExtension and SystemPropertyExtension

### ISSUE THREAD

**Issue by beatngu13** [junit-pioneer/junit-pioneer#460]
During a discussion on `findClosestEnclosingRepeatableAnnotations` vs. `findAllEnclosingRepeatableAnnotations` (`PioneerAnnotationUtils`) in Discord, the question came up why `EnvironmentVariableExtension` and `SystemPropertyExtension` are using `findClosestEnclosingRepeatableAnnotations` instead of `findAllEnclosingRepeatableAnnotations`.

In contrast to e.g. `DefaultLocalExtension` or `DefaultTimezoneExtension` (where #307 removed `BeforeAllCallback` and `AfterAllCallback`, which is still implemented by the extensions in question), `EnvironmentVariableExtension` and `SystemPropertyExtension` must not stop on the closest annotation:

```java
@ClearSystemProperty(key = "foo")
class MyTest {

  @ClearSystemProperty(key = "bar")
  void test() {
    assertThat(System.getProperty("foo")).isNull();
    assertThat(System.getProperty("bar")).isNull();
  }

}
```

Otherwise, the assert on "foo" would fail (suppose the original value is not `null`).

Therefore, we should investigate (i) why the extensions are using `findClosestEnclosingRepeatableAnnotations` instead of `findAllEnclosingRepeatableAnnotations`, (ii) and why the given tests – which are covering the above example – are actually passing.

**Comment by beatngu13** [comment]
Consider the following test:

```java
@ClearSystemProperty(key = "foo")
@SetSystemProperty(key = "bar", value = "spam")
class MyTest {

  void testA() {
    assertThat(System.getProperty("foo")).isNull();
    assertThat(System.getProperty("bar")).isEqualTo("spam");
  }

  @SetSystemProperty(key = "foo", value = "eggs")
  @ClearSystemProperty(key = "bar")
  void testB() {
    assertThat(System.getProperty("foo")).isEqualTo("eggs");
    assertThat(System.getProperty("bar")).isNull();
  }

}
```

A setup like this perfectly reasonable, i.e. to have class-level defaults but method-level configurations that overwrite these defaults.

In order to address this with `findAllEnclosingRepeatableAnnotations` (and `BeforeEachCallback`/`AfterEachCallback` exclusively), we would have to preserve order during annotation discovery and when creating the collections of entries to clear and set:

- `testA()`: Clear "foo" and set "bar" to "spam".
- `testB()`: First clear "foo" and set "bar" to "spam", then set "foo" to "eggs" and clear "bar".

I guess this is possible, but not necessarily straightforward. To circumvent this, we currently leverage the JUnit lifecycle by implementing both `BeforeEachCallback`/`AfterEachCallback` as well as `BeforeAllCallback`/`AfterAllCallback`.

While this works, it can also be confusing:

```java
@SetSystemProperty(key = "foo", value = "spam")
class MyTest {

  @Nested
  @SetSystemProperty(key = "bar", value = "eggs")
  class NestedClass {

    @Test
    void test() {
      assertThat(System.getProperty("foo")).isEqualTo("spam");
      assertThat(System.getProperty("bar")).isEqualTo("eggs");
    }

  }

}
```

One would expect two invocations of `AbstractEntryBasedExtension`, one for "foo" and one for "bar". But:

1. Set "foo" to "spam".
2. Set "bar" to "eggs".
3. Set "bar" to "eggs."

1 and 2 stem from `BeforeEachCallback`/`AfterEachCallback`, 3 from `BeforeAllCallback`/`AfterAllCallback`.

---

Overall, I think it is good to let the JUnit lifecycle handle the annotation order – even if this can result in "unnecessary" executions – but I suggest to ["Comment That &*☠# Code"](https://slides.nipafx.dev/comment-your-code/2018-10-02-softwerkskammer-karlsruhe/). 😉

**Comment by Michael1993** [comment]
@beatngu13 It's not really clear what the desired outcome of this ticket would be. If you'd like, we can refactor the extensions so they do not need to implement both endpoints.

Somewhat related, what happens here:
```java
@SetSystemProperty(key = "foo", value = "bar")
public class NotTestClass {
    public void method() {
        // is foo => bar here?
    }
}
```

**Comment by beatngu13** [comment]
> @beatngu13 It's not really clear what the desired outcome of this ticket would be. If you'd like, we can refactor the extensions so they do not need to implement both endpoints.

In a first step, I would to add an (internal) implementation note (similar like [here](https://github.com/junit-pioneer/junit-pioneer/blob/main/src/main/java/org/junitpioneer/internal/PioneerAnnotationUtils.java#L179)) that summarizes this issues and then close it. I just want to make sure we aren't confused about the implementation a second time.

If at some point we want to refactor our annotation utils, so that these extensions don't need to implement both callbacks anymore, we should open another issue. Personally, I do not see any urgent reasons to do so at this time.

> Somewhat related, what happens here:
> 
> ```java
> @SetSystemProperty(key = "foo", value = "bar")
> public class NotTestClass {
>     public void method() {
>         // is foo => bar here?
>     }
> }
> ```

Hmmm, you mean if the annotation should work outside of tests? I don't think so.

**Comment by Michael1993** [comment]
Okay, let me present another case I'm unsure about:
```java
@SetSystemProperty(key = "foo" value = "bar")
public class ExampleTests {

    @BeforeAll
    public static setupAll() {
        // is foo => bar here?
    }

}
```

**Comment by beatngu13** [comment]
> Okay, let me present another case I'm unsure about:
> 
> ```java
> @SetSystemProperty(key = "foo" value = "bar")
> public class ExampleTests {
> 
>     @BeforeAll
>     public static setupAll() {
>         // is foo => bar here?
>     }
> 
> }
> ```

Sorry for the late reply! If the extensions are meant to implement `BeforeAllCallback`, I would say yes. If we switch to `BeforeEachCallback` only, this is no longer the case.

Apparently, this is unspecified behavior at the moment. 🤷‍♂️ [Docs](https://junit-pioneer.org/docs/system-properties/) don't say anything about this, and the [Javadoc of `@SetSystemProperty`](https://github.com/junit-pioneer/junit-pioneer/blob/main/src/main/java/org/junitpioneer/jupiter/SetSystemProperty.java#L31-L32) for example states:

>If a class is annotated, the configured property will be set for all tests inside that class.
