### ISSUE TITLE
Create team email and accounts

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#464]
At the moment the Pioneer artefacts are published with @nipafx accounts.
We want to create our own account for it (for the team), but this requires a new (team) email account.

**Comment by nipafx** [comment]
Started on the team mail account, but it doesn't receive mails yet, possibly because of the A Record pointing at GitHub. I opened a support ticket with my hoster, but it's low priority and on a weekend, so I don't expect a fast turnaround time.

**Comment by nipafx** [comment]
Once the email address works, these accounts need to be transferred/created:

* Sonatype
* SonarQube

**Comment by beatngu13** [comment]
>SonarQube doesn't allow email/password logins 😔 - what now?

I assume we all have to login with our GitHub account (see ["Connection with SonarCloud"](https://github.com/settings/connections/applications/Iv1.dc610988574d1724)) and then make everyone an owner?

https://docs.sonarcloud.io/organizations/managing-members/#permissions

**Comment by nipafx** [comment]
Everybody except for @Bukama is an owner now. (Note for future me: I configured that [here](https://sonarcloud.io/organizations/junit-pioneer-xp/members).)

@Bish: You don't show up in the list of members. Did you ever go to https://sonarcloud.io and log in with your GitHub to link the accounts? If not, you probably need to do that before I can make you an owner. If you want to be one and have logged in, shoot me a message in Discord and I will make you owner.
