### ISSUE TITLE
Disable tests if other tests failed

### ISSUE THREAD

**Issue by nipafx** [junit-pioneer/junit-pioneer#467]
Imagine having a suite of integration-y tests that use some service that's fickle and may be down occasionally. If one test contacting that service fails with a `FickleServiceDownAgain_rollEyesEmojy_Exception`, then all others will likely as well. And if they don't, it doesn't matter much because the test suite failed already anyway. Maybe you want to save yourself some time and not run the other tests?

Enter `DisabledIfTestFailedWith` extension!

```java
@DisabledIfTestFailedWith(FickleServiceDownAgain_rollEyesEmojy_Exception.class)
class FickleServiceRelatedTests {

	void testA() {
		// something with the service
	}

	void testB() {
		// something else with the service
	}

	void testB() {
		// something else else with the service
	}

}
```

The extension will observe each test's execution and as soon as the first fails will disable the ones that didn't start yet.

I've started playing with this idea a few years ago and have just put the code I wrote into [this gist](https://gist.github.com/nipafx/2ef1be62a824eb0911f9ac05607aab5e) (which should be seen as experimental and not up to our quality standards).

**Comment by nipafx** [comment]
So what do you think about this potential extension? Let's discuss and, if we agree that this idea has legs, label it _up for grabs_ and/or _good first issue_.

**Comment by Bukama** [comment]
This would mean you also have to executed the depending first and then you mix up orderthings with test result things

**Comment by beatngu13** [comment]
I like the idea. Some thoughts: I contrast to e.g. JUnit's [`@EnabledOnOs`](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/condition/EnabledOnOs.html) or [`@DisabledOnOs`](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/condition/DisabledOnOs.html), I wonder if such an annotation is a bit different in its nature.

If, for example, `testB()` fails with the aforementioned exception, should `testA()` and `testB()` be disabled or _aborted_? (@Bukama I think what @nipafx means is: if any test of the suite fails with the given exception, don't start the others, regardless of the execution order.) That is, are we speaking of [conditions](https://junit.org/junit5/docs/current/user-guide/#writing-tests-conditional-execution) or [assumptions](https://junit.org/junit5/docs/current/user-guide/#writing-tests-assumptions)?

**Comment by nipafx** [comment]
@Bukama: I did not imply any order. As soon as one of the tests fails, the remaining ones should not run, no matter their order.

@beatngu13: Can we prematurely abort tests? Isn't that a thing that only happens during/after test execution?

**Comment by beatngu13** [comment]
@nipafx what I've found so far:

* [`TestSkippedException`](https://ota4j-team.github.io/opentest4j/docs/1.2.0/api/org/opentest4j/TestSkippedException.html): "[…] used to indicate that a test was skipped _prior_ to execution (e.g., _disabled_ or _ignored_)." 
* [`TestAbortedException`](https://ota4j-team.github.io/opentest4j/docs/1.2.0/api/org/opentest4j/TestAbortedException.html): "[…] used to indicate that a test was aborted _during_ execution (e.g., due to a failed _assumption_)."

So, I guess you are right that is uncommon to abort a test prior to its execution. However, I'm not sure if disable has the right semantics for the described use case, since it's literally an exceptional situation.

What do you think?

**Comment by nipafx** [comment]
I'm not even sure where we would throw those exceptions. During _condition evaluation_? That seems to go against the grain of that extension point. Or in _before each_?

**Comment by Michael1993** [comment]
My best guess is that it would be a combination of a [`TestWatcher`](https://junit.org/junit5/docs/5.5.1/api/org/junit/jupiter/api/extension/TestWatcher.html) and an [`ExecutionCondition`](https://junit.org/junit5/docs/5.5.1/api/org/junit/jupiter/api/extension/ExecutionCondition.html).

**Comment by nipafx** [comment]
@Michael1993 If we want to disable, then yes. But if we want to abort (as @beatngu13 proposees), I wouldn't know where to throw said exceptions.

Since a few people looked at this and no serious concerns were brought up, I'll go ahead and mark this as good to go.

**Comment by beatngu13** [comment]
What could work: Let an extension implement [`TextExecutionExceptionHandler`](https://junit.org/junit5/docs/5.5.0-RC2/api/org/junit/jupiter/api/extension/TestExecutionExceptionHandler.html) to keep track of thrown exceptions. If the given exception is present, use [`BeforeTestExecutionCallback`](https://junit.org/junit5/docs/5.5.0-RC2/api/org/junit/jupiter/api/extension/BeforeTestExecutionCallback.html) to throw the `TestAbortedException`.

Not sure if this is discouraged or doesn't count as "during [test] execution", but as already pointed out by @nipafx [here](https://github.com/junit-pioneer/junit-pioneer/issues/468#issuecomment-831387527), I also can't draw a clear boundary when it comes to assumptions vs. conditions.
