### ISSUE TITLE
Clean up after release changes

### ISSUE THREAD

**Issue by nipafx** [junit-pioneer/junit-pioneer#469]
* [x] `CONTRIBUTING.md` gives the wrong name and URL for the release action - should be `[_Release build_ GitHub Action](https://github.com/junit-pioneer/junit-pioneer/actions/workflows/release-build.yml?query=workflow%3ARelease)`.
* [x] we need a proper version in `version.properties` after all (otherwise release notes are borked), which means the documentation needs to (once again) explain how to update it
* [x] the build badge in the README always says the build is failing (even when it isn't)

**Comment by beatngu13** [comment]
>we need a proper version in `version.properties` after all (otherwise release notes are borked), which means the documentation needs to (once again) explain how to update it

You mean the version passed via the GitHub Action workflow must be written to `version.properties`?

**Comment by nipafx** [comment]
Not precisely. What I'm pretty sure would work would be `1.4.*`, so only minor increments need to be written there. But since pretty much every feature changes that, that still sucks. Maybe `1.*.*` can work as well? Need to try that.

Alternatively, we could try to remove the auto-version-plugin together with the file. As I understood, since we set the future version explicitly, the only thing it still does for us is determining the current version (via tag) and set a variable that the release-plugin will then read. If we can set that variable directly, we can avoid auto-version-plugin entirely. Maybe the release-plugin docs even describes how that could work?

Anyway, this requires some research.

**Comment by nipafx** [comment]
It Idea worked! :) #475

**Comment by nipafx** [comment]
Fixed by the three PRs cross-linked above.
