### ISSUE TITLE
CleanUp GitHub Actions

### ISSUE THREAD

**Issue by aepfli** [junit-pioneer/junit-pioneer#494]
Our Github actions are a mess, we started and improved them over time, we renamed them etc. But now we do have some old Actions in there, which we do not need anymore.
Sadly there is no GUI way of deleting them, but we can delete them via api.

We should delete all GitHub Actions which are deactivated:
- [JUnit build](https://github.com/junit-pioneer/junit-pioneer/actions/workflows/actions.yml)
- [Experimental Build](https://github.com/junit-pioneer/junit-pioneer/actions/workflows/experimental-build.yml)
- [Release Trigger](https://github.com/junit-pioneer/junit-pioneer/actions/workflows/releaseTrigger.yml)

within [this GitHub support question answer](https://github.community/t/is-there-a-way-to-delete-or-hide-old-renamed-workflows/16281/29?u=aepfli), we do have all the script paths we need. The executor needs to have `jq` and `gh` installed.

1. Fetching the workflow IDs with
```shell
OWNER=<your user/org name>
REPO=<repo name>

# list workflows
gh api -X GET /repos/$OWNER/$REPO/actions/workflows | jq '.workflows[] | .name,.id'
```

2. Deleting all workflow runs with
```shell

OWNER=<your user/org name>
REPO=<repo name>
# copy the ID of the workflow you want to clear and set it
WORKFLOW_ID=<workflow id>

# list runs
gh api -X GET /repos/$OWNER/$REPO/actions/workflows/$WORKFLOW_ID/runs | jq '.workflow_runs[] | .id'

# delete all runs
gh api -X GET /repos/$OWNER/$REPO/actions/workflows/$WORKFLOW_ID/runs | jq '.workflow_runs[] | .id' | xargs -I{} gh api -X DELETE /repos/$OWNER/$REPO/actions/runs/{}
```

**Comment by aepfli** [comment]
if this topic is agreed upon, i can execute it :)

**Comment by Bukama** [comment]
Throw away your television 🎶 aehm your github actions :D

**Comment by nipafx** [comment]
Yes, please!

**Comment by aepfli** [comment]
links to !474

**Comment by nipafx** [comment]
[This comment](https://github.com/junit-pioneer/junit-pioneer/pull/492#pullrequestreview-677080985) made me think that, if #502 decides to pull in optional dependencies, modular builds should be part of the basic builds.

**Comment by nipafx** [comment]
@aepfli I've cleaned out two of them manually but have capitulated for the third, which must have hundreds and hundreds of builds. Can you delete them automatically? 🥺

**Comment by nipafx** [comment]
Works almost as described, I just had to add a `--silent` to the delete command because my bash would open less (or something like that?) to display the 0 byte return. 😬 So (minus line breaks):

```
gh api -X GET /repos/$OWNER/$REPO/actions/workflows/$WORKFLOW_ID/runs
 | jq '.workflow_runs[] | .id'
 | xargs -I{} gh api -X DELETE /repos/$OWNER/$REPO/actions/runs/{}
```

**Comment by nipafx** [comment]
![gone gif](https://user-images.githubusercontent.com/6537432/190172739-55b4d0fc-3955-4ec6-8c4f-c775f6f050d1.gif)
