### ISSUE TITLE
Discuss approach to optional dependencies

### ISSUE THREAD

**Issue by nipafx** [junit-pioneer/junit-pioneer#502]
One of Pioneer's cornerstones is not to add to user's dependency hell and so we don't want to require any run-time dependencies beyond JUnit (and its dependencies). But we've recently encountered two situations that don't work without at least compile dependencies. We need to discuss how to handle such situations.

### For Integration

#426 aims at making Pioneer support Playwright, i.e. Pioneer would integrate with another (testing) libraries or framework to ease their use within JUnit Jupiter.

Side note: Whether that makes sense in the specific instance of Playwright doesn't matter for the sake of this conversation. Generally speaking, it's not unreasonable for Pioneer to integrate in that manner, so let's assume it makes sense for Playwright to have a concrete example.

### For Ease of Use

#101 wants to enable users to provide parameterized test arguments via JSON. This is obviously easiest if we just use an existing JSON library as a dependency.

Side note: In this specific case, one could see integration with JSON as a kind of framework integration as we probably want to use the same library that the user already depends on. For the sake of this aspect of the conversation, let's ignore that (we can discuss that in the _For Integration_ aspect if that makes sense.

## What To Do?

We're not gonna take on run-time dependencies on projects like Playwright and JSON parsers, so we need to find other options.

Proposals?

**Comment by Bukama** [comment]
> An option not yet listed here is to create a new repository under the Pioneer umbrella, either for each 'project' (that takes new dependencies) or a collector repository far all ideas.

Yeah I want to follow this. We should stay with our strict rule of no additional dependencies. If we want to have new features with additional dependencies we can have more projects under umbrella.

**Comment by beatngu13** [comment]
Build tool approaches, as brought up [here](https://github.com/junit-pioneer/junit-pioneer/issues/426#issuecomment-771996825):

* Maven: [optional dependencies](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html)
* Gradle: [feature variants](https://docs.gradle.org/current/userguide/feature_variants.html)

Personally, I like @Michael1993's suggestion to have one or more separate projects, similar to e.g. JUnit Jupiter (API, engine, params, etc.). And there's already Pioneer test reports.

However, an approach like this introduces some overhead and may quickly grow in terms of complexity…

**Comment by nipafx** [comment]
As I can see, we have five options:

* **EACH**: create a new project for each integration / ease of use
* **ALL**: create a single project for all integrations / ease of use cases
* **ALL_OPTIONAL**: same as **ALL** but add each dependency as optional
* **ADD**: add a dependency for each feature - out of the question by project cornerstone
* **ADD_OPTIONAL**: add optional dependencies / feature variants to the existing project

# Lenses

There are different lenses through which to view these proposals...

## Dependency hell

We don't want to burden users with dependencies they don't strictly need.

* **EACH**: Works great, no single unused dependency.
* **ALL**: Not good - as soon as a project needs one integration / ease of use, it pulls in dependencies for all of them.
* **ALL_OPTIONAL**: Not easy to judge - should technically work, but optional dependencies still have a higher impact on build tools than no dependencies.
	* **ADD**: same as **ALL_OPTIONAL**

## Discoverability

How hard is it to discover and understand which features Pioneer has, where issues / PRs need to go, which tasks to work on (that's one for us maintainers)?

* **EACH**: Ugh!
* **ALL**: Works fine.
* **ALL_OPTIONAL**: same as **ALL**
* **ADD**: Works great!

## Barrier to entry

Creating projects requires a decent amount of work (setting up the build, website integration, GitHub permissions, etc.), which will always reduce the enthusiasm of creating a new project for a new feature, particularly if it's small and experimental.

* **EACH**: Ugh!
* **ALL**: Works great.
* **ALL_OPTIONAL**: same as **ALL**
* **ADD**: same as **ALL**

## Combinatorial Explosion

What happens if the Playwright integration wants to enable ease of use with JSON? Does that go into one of the two projects or should there be another project? What if there's a new project under the same roof because it covers its own domain logic - same explosion again?

* **EACH**: We'd essentially need a new project per combination (would not go well) or end up with some projects supporting more than one integration / use case (would be confusing)
* **ALL**: Works great.
* **ALL_OPTIONAL**: same as **ALL**
* **ADD**: same as **ALL**

**Comment by nipafx** [comment]
My option:

* **EACH** Looks really bad. All we get is purity, but we give up ease of use and maintainability and invite a combinatorial explosion in the future. I think it's out!
* **EACH_INTEGRATION**: Better. Feels like classic middle ground.
* **ALL**: I don't see the point in this. As soon as a user needs one of these cases, they're in the same situation as **ADD** (which we abandoned early!) but we still have less discoverability and more overhead.
* **ALL_OPTIONAL**: If optional dependencies work as we hope they do, this is really nice - then again, it's essentially **ADD_OPTIONAL** but simpler.
* **ADD_OPTIONAL**: As long as optional dependencies work as we hope they do, this seems to me to be the best option.

I vote for **ADD_OPTIONAL**.

**Comment by nipafx** [comment]
Side note: If we add optional dependencies, we need to add at least one modular build to the base set to verify the correctness of the module declaration.

**Comment by Bukama** [comment]
Which means that all of the dependencies must be modular too. In the test reports the CSV dependencies is non-modualr so I cant setupo a modular build.

**Comment by filiphr** [comment]
I know that my vote does not count, but I'd like to add my 2 cents. I think that *ADD_OPTIONAL* is the best approach. It makes it easy from a maintenance point of view, since everything is part of one module. 

In the scope of #492 the Json parsers which is available (currently there is only support for Jackson) will be used, this means that we are meeting the users where they are. They will also most likely have that dependency in their production code anyways.

In the scope of #462 the user will already add the Playwright dependency as they need it for their other tests anyways. Once they add Pioneer, they will have more goodies for Playwright as well.

As for the modular, I don't think that all dependencies need to be modular, if a dependency is not modular then the Pioneer will not add that in its module-info.java and it can be exlcuded from the modular build.
