### ISSUE TITLE
Create code style for Optional vs null

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-pioneer/junit-pioneer#51]
How should the project handle `null` references and which ones should be replaced by `Optional`? Possible distinctions are:

* method return values
* method parameters
* fields

Possible variants could be decided for:

* `public` vs `default` vs `private`
* `static` vs instance
* ... ?

**Comment by jbduncan** [comment]
@nicolaiparlog I think Stephen Colebourne's [blog post](http://blog.joda.org/2015/08/java-se-8-optional-pragmatic-approach.html) on this provides a good, practical compromise between `Optional` and `null`. The main points of the blog are:

1. Use `null`s for method and constructor parameters and fields.
(We'd annotate these with JSR-305's `@Nullable` to have more explicit documentation, and perhaps make migration to the [Checker Framework](https://checkerframework.org/) easier if we decide to go down that route.)

2. Use `Optional`s for method return values.

Although, I do realise that [your (past?) opinions on this differ](https://blog.codefx.org/java/stephen-colebourne-optional-a-strict-approach/). :smile:

**Comment by smoyer64** [comment]
@jbduncan I think you've summed up my opinion.  Both the blog posts use a pretty simple POJO/DTO/Bean.  I'm definitely not a fan of:

```
private final Optional<String> postcode;
```

If you have a class that actually has business logic, this will generally result in more code than simply dealing with a ```null``` field;

**Comment by nicolaiparlog** [comment]
I have been using my proposed strict approach in small code bases for a while ([example](https://github.com/CodeFX-org/jdeps-wall-of-shame/tree/master/src/main/java/org/codefx/jwos)) and have not observed any averse effects. (Note: Avoiding optionality is still much better than using `Optional` and should always be the first attempt.)

Optional fields and optional parameters usually beget optional logic and `Optional` is much better at that than `null`. This is particularly true when it comes to the results because the type system will tell you whether you are in the right lane and correctly made the switch to non-optional - no way to make a mistake; no heuristic that can fail. Furthermore: `null` is never legal so any `null` is immediately a bug.

Regarding boilerplate: It is mostly incurred when going from `Optional<T>` to `T` or the other way, which in my experience usually happens when you have an `Optional` but are not allowed to pass it along because "there must not be optional fields/arguments".

I would _love_ to try my strict approach in a larger project and see how other people adapt/react to it. What do you think about this: We go with "`Optional` everywhere" (i.e. `null` is _never_ legal) and in the run-up to the first stable release, we look at the code and see how it worked out. If we decide it wasn't a good idea, I'll personally rip out `Optional` fields and parameters. Can we do that? Please?

![](https://cloud.githubusercontent.com/assets/6537432/26371039/d51ad4b4-3ff9-11e7-9237-6b38ddf32ce7.gif)

**Comment by smoyer64** [comment]
Since you included a begging cat ... I'll think about it (but isn't a $ in the package name enough non-conformity for this week?).  I'd also like to point out that using Optional doesn't eliminate the need for the static code analysis annotations/checking described in #50.  There's nothing that keeps you from returning null from a method who's return type is ```Optional<T>```.

**Comment by nicolaiparlog** [comment]
> but isn't a $ in the package name enough non-conformity for this week?

Damn, I knew that would come back to bite me!

> I'd also like to point out that using Optional doesn't eliminate the need for the static code analysis annotations/checking described in #50

True. As I see it, we can then indeed put `@NonNullable` (or however that is called exactly) on the root package and have the tool make sure, everything's correct.

**Comment by smoyer64** [comment]
>   Damn, I knew that would come back to bite me!

Fortunately this week will be last week by next week.
