### ISSUE TITLE
Missing public key on keyservers

### ISSUE THREAD

**Issue by slawekjaranowski** [junit-pioneer/junit-pioneer#510]
From version `1.4.0` new pgp key is used to sign released artifacts with id: `0x6746229D0F629EDB`

Public key is not published to any public key servers, so verification of artifacts is impossible.

To reproduce please run maven plugin (in any directory):

    mvn org.simplify4u.plugins:pgpverify-maven-plugin:show -Dartifact=org.junit-pioneer:junit-pioneer:1.4.2

**Comment by Bukama** [comment]
Thank you for you information. I assigned @nipafx as he's the key holder.

**Comment by nipafx** [comment]
Just [uploaded it to Ubuntu's key server](https://keyserver.ubuntu.com/pks/lookup?search=junit-pioneer.org&fingerprint=on&op=index) (took me quite some time to find a still-working server 🙈 ) and it's checked by Maven, so it already works:

```
[INFO] --- pgpverify-maven-plugin:1.14.1:show (default-cli) @ standalone-pom ---
[INFO] Key server(s) - fallback list: [{https://keyserver.ubuntu.com}, {https://keys.openpgp.org}, {https://pgp.mit.edu}]
[INFO] 

Artifact:
        groupId:     org.junit-pioneer
        artifactId:  junit-pioneer
        type:        jar
        version:     1.4.2

PGP signature:
        version:     4
        algorithm:   SHA512withRSA
        keyId:       0x6746229D0F629EDB
        create date: Sat May 29 13:44:59 CEST 2021
        status:      valid

PGP key:
        version:     4
        algorithm:   RSA (Encrypt or Sign)
        bits:        4096
        fingerprint: 0x110688FBA8BA3992DD2F2F1B6746229D0F629EDB
        create date: Tue Apr 20 21:12:42 CEST 2021
        uids:        [JUnit Pioneer Team <team@junit-pioneer.org>]
```

For other tools using other key servers, it may take a while before they pick up the key.
