### ISSUE TITLE
CartesianTest clean-up

### ISSUE THREAD

**Issue by beatngu13** [junit-pioneer/junit-pioneer#517]
After merging #487, code duplication went over 3%, which was part of [Pioneer's quality gate](https://sonarcloud.io/organizations/junit-pioneer-xp/quality_gates/show/39036). In order to get back a successful build on `main` (and elsewhere), we increased that metric to 7%.

What's left to do:

* Remove duplication
* Reset quality gate
* Publish Pioneer v2.0

We aim to do that in December 2021.

**Comment by Bukama** [comment]
Will clean this up as the docs say version 1 will be removed in 2.0

**Comment by Bukama** [comment]
Merge Blocked until 2.0

**Comment by beatngu13** [comment]
Closed via #635.
