### ISSUE TITLE
Add JDK 17 to the build matrix

### ISSUE THREAD

**Issue by Thihup** [junit-pioneer/junit-pioneer#521]
Currently it is blocked because Gradle doesn't support Java 17 yet.

**Comment by beatngu13** [comment]
Corresponding Gradle issue: https://github.com/gradle/gradle/issues/16857

**Comment by Bukama** [comment]
five days ago Gradle 7.3 RC5 was released, so I think we are getting close to a Java 17 compliant Gradle release

**Comment by Thihup** [comment]
https://docs.gradle.org/7.3/release-notes.html
