### ISSUE TITLE
Generate Javadoc using JDK 17

### ISSUE THREAD

**Issue by Thihup** [junit-pioneer/junit-pioneer#522]
~It allows to have the Javadoc from JDK 17.~

~Blocked by #521~

Advantages: https://github.com/junit-pioneer/junit-pioneer/issues/522#issuecomment-985885702

**Comment by Bukama** [comment]
Closed through #536

**Comment by beatngu13** [comment]
Hey @Thihup,

@Bukama already closed this issue, but I wonder what exactly was your intention behind it, especially compared to #521? Did you mean moving the entire project to 17? Only for Javadoc generation? … ?

**Comment by Thihup** [comment]
@beatngu13 In the most part it was because of Javadoc, but still targeting JDK 8. So it would be able to use the search box in the Javadoc and still be compatible with all clients 😄 
And with JDK 18, maybe use the @snippet tag to improve the docs 🤓

**Comment by beatngu13** [comment]
@Thihup thanks for clarification, I have adapted the issue title accordingly.

Advantages of using JDK 17 for Javadoc include [JEP 224 (HTML5 Javadoc)](https://openjdk.java.net/jeps/224) and [JEP 225 (Javadoc Search)](https://openjdk.java.net/jeps/225) (and the aforementioned `@snippet` tag from [JEP 413](https://openjdk.java.net/jeps/413) once Java 18 is GA).

**Comment by Bukama** [comment]
Can't assign @Marcono1234 - ask Github why the user doesn't show up in the assign list...

**Comment by scordio** [comment]
> Can't assign @Marcono1234 - ask Github why the user doesn't show up in the assign list...

@Marcono1234 needs to comment on this issue to appear as a possible assignee.

**Comment by Marcono1234** [comment]
> @Marcono1234 needs to comment on this issue to appear as a possible assignee.

Hello
