### ISSUE TITLE
@CartesianTest not working with array arguments

### ISSUE THREAD

**Issue by filiphr** [junit-pioneer/junit-pioneer#523]
If I implement my own `CartesianArgumentsProvider` which returns arrays as arguments. Then the arguments are flattened.

e.g. with the following custom `CartesianArgumentsProvider`

```java
	@Retention(RetentionPolicy.RUNTIME)
	@Target({ ElementType.PARAMETER, ElementType.ANNOTATION_TYPE })
	@ArgumentsSource(StringArrayArgumentsProvider.class)
	@interface StringArrayArguments {

	}

	static class StringArrayArgumentsProvider implements CartesianArgumentsProvider {

		@Override
		public void accept(Parameter parameter) {

		}

		@Override
		public Stream<? extends Arguments> provideArguments(ExtensionContext context) throws Exception {
			return Stream.of(
					Arguments.of((Object[]) new String[] { "1", "2"}),
					Arguments.of((Object[]) new String[] { "3", "4"})
			);
		}
	}
```

In the following test

```java
static class ArrayArgumentsTestCases {

		@CartesianTest
		void singleArrayArgument(@StringArrayArguments String[] source) {
			assertThat(source).hasSize(2);
		}
	}
```

There will be 4 tests. However, there should be only 2. The reason for this happening is flat mapping of the provided argument in [this line](https://github.com/junit-pioneer/junit-pioneer/blob/bd6d99478cf2c53caef592ba3c42b4abbfe47165/src/main/java/org/junitpioneer/jupiter/cartesian/CartesianTestExtension.java#L120) in the `CartesianTestExtension`.

I can easily provide a fix for this once PR #519 is resolved. Since there are already changes in that PR that will clash with a fix for this. In addition to fixing the line I mentioned the `CartesianValueArgumentsProvider` needs to be fixed as well. In PR #519 the `CartesianValueArgumentsProvider` correctly returns a stream containing each element, instead of a Stream of one element with the array.

**Comment by nipafx** [comment]
That's indeed not correct. When fixing this, please make sure that we don't accidentally break something else (there must be a reason for that `flatMap` - probably).
