### ISSUE TITLE
Automate release

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-pioneer/junit-pioneer#53]
As a follow-up to #17, automate some or all of the following checks/steps that need to be made for a release:

* release comes from clean `master`
* no dependency on snapshot versions
* change version by removing `-SNAPSHOT`
* tag that commit as release and later upload all artifacts to GitHub
* go to the next snapshot version and commit the change
* close and release on Sonatype

**Comment by nicolaiparlog** [comment]
Assuming we use ShipKit as proposed in #87, what else needs to be done for a proper release?

* We got [the site](https://junit-pioneer.org) up and running.
* It includes [high-level documentation](https://junit-pioneer.org/docs/) and [JavaDoc](https://junit-pioneer.org/api/) - I wonder whether we have to version these?

Did I miss anything?

**Comment by sormuras** [comment]
I'll compare the assets I configured/installed for bartholdy to find out what's missing.

Note: using javadoc.io ( like https://javadoc.io/doc/de.sormuras/bartholdy ) offers users versioned API docs for granted. Thus, showing only the latest API at https://junit-pioneer.org/api/ is fine with me.

**Comment by nicolaiparlog** [comment]
Neat and as far as I see it, we don't need to do anything, right? I will include a link to it somewhere... see #92.

**Comment by sormuras** [comment]
> [...] we don't need to do anything, right?

Just release to "central.maven.org". The javadoc jars are picked up from there. For details see: https://javadoc.io

**Comment by sormuras** [comment]
Looks `Closeable` now, as #87 is integrated.

**Comment by nicolaiparlog** [comment]
:+1:
