### ISSUE TITLE
DisableIfDisplayName javadoc incorrect as of 1.5.0

### ISSUE THREAD

**Issue by sleberknight** [junit-pioneer/junit-pioneer#547]
As of 1.5.0, the online docs for `DisableIfDisplayName` have this [note](https://junit-pioneer.org/docs/disable-parameterized-tests/#disableifdisplayname):

> Since JUnit Pioneer 1.5.0, using both matches and contains in a single annotation is no longer permitted.

And it then goes on to provide additional background information.

But the javadoc in `DisableIfDisplayName` still says that both can be configured:

> If neither contains nor matches is configured, the extension will throw an exception. It is possible to configure both, in which case the test gets disabled if at least one substring was found or at least one regular expression matched.

I only found this when I updated a project to 1.5.0 and it had a test that was using _both_ `contains` and `matches` and the test failed with the message:

> @DisableIfDisplayName requires that either `contains` or `matches` is specified, but both are present.

**Comment by sleberknight** [comment]
Suggested javadoc update:

```
If neither contains nor matches is configured, or if both are present, the extension will throw an exception.
```

**Comment by sleberknight** [comment]
If this makes sense I'd be happy to submit a PR with this minor fix.

**Comment by Michael1993** [comment]
Sounds great! If you'd like to do this, go ahead!
