### ISSUE TITLE
Provide a @FailAt annotation

### ISSUE THREAD

**Issue by helpermethod** [junit-pioneer/junit-pioneer#549]
Inspired by https://twitter.com/mikeveerman/status/1464162014444638258

It would be nice to provide an annotation that fails at a specified date, with on optional reason. Something like this:

```java
@FailAt(date = "2022-01-01", reason = "An optional reason")
@Test
void should_fail_at_the_provided_date() {
    // ...
}
```

This could be a great way to remind oneself of unpaid technical debt but could probably also be used in other contexts.

**Comment by Michael1993** [comment]
What's the upside of the annotation over this one-liner:
```java
assumeTrue(LocalDate.now().isBefore(2022,1,1), "An optional reason"); // or assertTrue if you want the test to fail, not abort
```

**Comment by Michael1993** [comment]
Hm, I guess, you could say that this assumption/assertion is meta - it's not really an assertion or assumption that is part of the test and therefore should be moved out from the method body? 🤔

**Comment by helpermethod** [comment]
@Michael1993 Exactly, IMHO it should be separate from the actual assertions.

An annotation would also give you a visual clue that this is something you need to be aware of, and makes searching for the existence of such tests simpler (e.g. by grepping for the annotation).

But maybe the annotation is too esoteric to be included in JUnit Pioneer 😄 .

**Comment by Michael1993** [comment]
> But maybe the annotation is too esoteric to be included in JUnit Pioneer 😄 .

Not at all! Our `@ReportEntry` annotation uses the same reasoning (report entries are meta and not part of the test), so this would be a great fit for Pioneer.
Let me know if you want to implement this yourself or if we should go ahead and make it ourselves.

**Comment by helpermethod** [comment]
Hi @Michael1993,

I can take a stab at it 🙂!

**Comment by Bukama** [comment]
Hm I see this is the same as `DisableUntil` annotation #366

**Comment by Bukama** [comment]
We talked about this at our last team meeting and want you to invite to take part in a discussion to think about this and similar use cases in a more global view.

Feel free to write down your thoughts and ideas in #550 - thank you!

**Comment by nipafx** [comment]
Since this seems to overlap a lot with #366 and #550, I'll close this as a duplicate. Feel free to comment of you disagree.

**Comment by nipafx** [comment]
Ooops, not so much of a duplicate after all. 😊 Still, let's first discuss in #550.
