### ISSUE TITLE
Cleanup merged branches

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#555]
We have a ton of already merged branches that were not removed after being merged, building up a constantly growing mess.

![pioneer](https://user-images.githubusercontent.com/4354359/145714139-b53bc8a5-d3aa-4e81-8567-2c4333a52e39.png)

**Comment by beatngu13** [comment]
To prevent this in the future, I suggest to check "Automatically delete head branches " under [settings](https://github.com/junit-pioneer/junit-pioneer/settings) (I can't because I don't have the corresponding priviliges).

**Comment by nipafx** [comment]
That's outdated info, [the list of branches](https://github.com/junit-pioneer/junit-pioneer/branches/all) is much smaller and all of them are ok to exist. You need to run `git fetch upstream --prune` (I think) to remove the branches from your local repo.

@Bukama 

> To prevent this in the future, I suggest to check "Automatically delete head branches " under settings 

Done.
