### ISSUE TITLE
`org.junitpioneer.jupiter.params.RangeClass` should be package-private

### ISSUE THREAD

**Issue by Marcono1234** [junit-pioneer/junit-pioneer#564]
It appears `org.junitpioneer.jupiter.params.RangeClass` is only used internally as meta-annotation, however currently it is `public`.

This leads to the inconvenient situation where `RangeClass` refers to the internal `Range`, which might be confusing for users, see:
https://javadoc.io/doc/org.junit-pioneer/junit-pioneer/latest/org/junitpioneer/jupiter/params/RangeClass.html
![Javadoc screenshot](https://user-images.githubusercontent.com/11685886/147387591-efb55458-8957-4c41-9bbc-43106d456bfd.png)

Therefore the annotation type should probably be made package-private and its `@Documented` annotation should be removed.

A similar issue exists for `org.junitpioneer.jupiter.params.RangeSourceArgumentsProvider` which is visible through the documented annotation `ArgumentsSource` on the <code><i>NumericType</i>RangeSource</code> classes (e.g. `ShortRangeSource`). However, there it cannot be easily solved without making `RangeSourceArgumentsProvider` public, which might not be desired, so maybe there this broken reference is acceptable.

**Comment by Michael1993** [comment]
If I remember correctly, it's public so people can make their own range sources. Does the documentation have anything on that? 🤔

**Comment by Marcono1234** [comment]
The [documentation](https://junit-pioneer.org/docs/range-sources/) does not seem to mention that, and in its current form users cannot create their own range sources because neither `RangeSourceArgumentsProvider` nor `Range` or its subclasses are public.

**Comment by Michael1993** [comment]
I recently did a review of our classes and it seems some of them were unnecessarily `public` instead of package-private... This is probably the case with `RangeClass` as well. It has some Javadoc and that kind of threw me off. 😓
