### ISSUE TITLE
Make EnvironmentVariableUtils public

### ISSUE THREAD

**Issue by renannprado** [junit-pioneer/junit-pioneer#573]
Sometimes one might need to set the environment variables programmatically instead of via the `@SetEnvironmentVariable` annotation, as there may be values that are not known before the test is run.
 
Therefore IMHO it makes sense that `EnvironmentVariableUtils` is public as well as its methods (if not all, at least some if that makes sense).

**Comment by beatngu13** [comment]
Hey @renannprado,

you are right, and we already have an issue for that:

#381

Feel free to join the discussion.
