### ISSUE TITLE
Review all Javadoc of the project

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#576]
It seems that there are several javadocs outdated and should be reviews.

@Michael1993 please fill in some examples

**Comment by Michael1993** [comment]
Here are some examples:
Outdated package description:

org.junitpioneer.jupiter.params | Disable @ParameterizedTest executions based on conditions.
-- | --

`DisableIfNameExtension` shows up - either make it not `public` or update it to have a proper Javadoc.

**Comment by Michael1993** [comment]
This is just after a minute - so I think a review is in order.
