### ISSUE TITLE
Environment variables and system properties not resetting after tests

### ISSUE THREAD

**Issue by Michael1993** [junit-pioneer/junit-pioneer#579]
Opened retroactively for #578.

As seen in the PR, some tests do not reset the system property/environment variable they modified.
Is this unintended or intended behaviour?

**Comment by beatngu13** [comment]
I guess this is my "fault".

The system property and environment variable test keys/values are completely made up, so when I wrote the tests for the system property extension — which I believe acted as a template for the environment variable tests — I thought resetting them is not necessary.

But yes, in the end the tests leave a dirty state behind.

**Comment by Bukama** [comment]
So what's the solution @beatngu13 ?

**Comment by beatngu13** [comment]
Besides making the tests a bit more verbose, #578 doesn't cause any harm and makes our tests less error-prone. So merging the PR is probably a good idea.

**Comment by beatngu13** [comment]
Fixed via #587.
