### ISSUE TITLE
Add CLA-Bot

### ISSUE THREAD

**Issue by aepfli** [junit-pioneer/junit-pioneer#591]
Currently our CLA is just a text within the Pull Request. So far I (in me aka @aepfli) can not remember that i really checked when merging if the user agreed upon it.

Therefore i suggest to use https://github.com/apps/cla-bot which can automate this with an additional check. (as suggested by @beatngu13 )

As this is a change/application which needs certain permissions, we should discuss it, and decide upon feasibility - also i am not sure if somebody else besides @nipafx can do it.

**Comment by beatngu13** [comment]
Regarding yesterday's discussion during the maintainer meeting, whether we need a CLA at all, I found [this](https://ben.balter.com/2018/01/02/why-you-probably-shouldnt-add-a-cla-to-your-open-source-project/) interesting blog post. [Here](https://ben.balter.com/2018/01/02/why-you-probably-shouldnt-add-a-cla-to-your-open-source-project/#if-a-license-isnt-good-enough-for-maintainers-you-shouldnt-subject-users-to-it) it says:

>[GitHub made that relationship explicit by incorporating an `inbound = outbound clause` into its Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license), meaning if a pull request is submitted via GitHub, it is submitted under the project’s open source license.

From the linked GitHub terms of service:

>Whenever you add Content to a repository containing notice of a license, you license that Content under the same terms, and you agree that you have the right to license that Content under those terms. If you have a separate agreement to license that Content under different terms, such as a contributor license agreement, that agreement will supersede.

So currently our CLA supersedes our license. But our [license](https://github.com/junit-pioneer/junit-pioneer/blob/main/LICENSE.md) (section 2 "GRANT OF RIGHTS") already says:

>Subject to the terms of this Agreement, each Contributor hereby grants Recipient a non-exclusive, worldwide, royalty-free copyright license to reproduce, prepare Derivative Works of, publicly display, publicly perform, Distribute and sublicense the Contribution of such Contributor, if any, and such Derivative Works.

Does that mean, at least in our case, the CLA is indeed unnecessary?

**Comment by nipafx** [comment]
That would be really great! That means, we'd not only avoid the CLA bot, we could even remove the CLA and instead explain what you described - mostly just copy/paste your comment. :D

**Comment by Bukama** [comment]
I'm not a lawyer, so I leave decision if we need/change this to others.
