### ISSUE TITLE
Migrate to AsciiDoc snippets

### ISSUE THREAD

**Issue by Michael1993** [junit-pioneer/junit-pioneer#595]
Once #334 gets merged, the rest of the documentation should be migrated to use the new approach.

**Comment by Bukama** [comment]
Shall I delete the docs of `TempDir`, as we removed the extension in 1.0 and want to completely recreate it in #348?

**Comment by nipafx** [comment]
Neither, so we don't break existing URLs. Will add a comment to #348 re existing docs, though.

**Comment by nipafx** [comment]
No need for a comment. #491 already updated the files as needed.
