### ISSUE TITLE
Set up modular integration tests

### ISSUE THREAD

**Issue by beatngu13** [junit-pioneer/junit-pioneer#596]
This issue stems from #539. To ensure Pioneer's compatability with JPMS, we have to set up modular integration tests and execute them during our build.

Open for discussion: should these tests be a separate module, a separate project, … ?

Helpful links:

* https://docs.gradle.org/7.3/userguide/java_testing.html#sec:java_testing_modular
* https://sormuras.github.io/blog/2018-09-11-testing-in-the-modular-world

**Comment by Bukama** [comment]
link to #617

**Comment by Bukama** [comment]
@beatngu13 Is this still relevant, when upgrading to Java 11 (in #627)

**Comment by nipafx** [comment]
@beatngu13 If you want, you can start a new branch based on #627 and start experimenting with the integration tests there.

**Comment by Bukama** [comment]
@beatngu13  wasn't that also done with #651 ?

**Comment by beatngu13** [comment]
@Bukama you are right, this should be done now. 🥳
