### ISSUE TITLE
Provide automatic-module-name in JAR manifest

### ISSUE THREAD

**Issue by sormuras** [junit-pioneer/junit-pioneer#60]
How about `org.junit-pioneer` ... is minus `-` a valid character in module names?!

Like
```groovy
jar {
	manifest {
		attributes(
			'Automatic-Module-Name': 'org.junit$pioneer'
		)
	}
}
```

**Comment by nicolaiparlog** [comment]
Good call about the name. No, `-` wont work (just like in packages), so we'll go with `$` (just like in packages :smiley:)

**Comment by sormuras** [comment]
Updated the initial snippet to include `$`.
