### ISSUE TITLE
Update JDK used for builds

### ISSUE THREAD

**Issue by nipafx** [junit-pioneer/junit-pioneer#606]
We currently build with JDK 8. This turned out to be a problem in #565 because that compiler version creates unsuppressible deprecation warnings, which that PR turns into errors - hence the build fails.

Building on JDK 11 should be straightforward. Right? 🧐

**Comment by Marcono1234** [comment]
Possibly related to #567 (depending on how far you want to go for solving this issue here)

**Comment by Michael1993** [comment]
Building on JDK 11, sure. It can be done in like 15 minutes. But I think we shouldn't stop there - let's update the whole codebase to Java 11!
