### ISSUE TITLE
Upgrade Pioneer to JDK 11 

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#617]
We think about to lift Pioneer require JDK 11, resulting in Pioneer 2.0 does not support Java 8 anymore.

In this issue we want to discuss pros and cons about that as well list things to be done, like improve module build. Check / update dependencies etc.

**Comment by nipafx** [comment]
Things we should do on update:

* move module declaration into source tree
* remove modular build flag (all builds will be modular)
* if we put module descriptor in in `META-INF/versions` right now, we can move it to root folder

More?

**Comment by filiphr** [comment]
My 2 cents regarding the bump to JDK 11. In my opinion of you are doing a bump of a major Java version then I would strongly suggest doing a bump to JDK 17. The number of users that you are going to lose with a bump to JDK 11 or JDK 17 is the same in my opinion.

I believe that the Java ecosystem will move faster to JDK 17 in the next year.

**Comment by beatngu13** [comment]
@filiphr hmmm, not sure about that:

* [Adoptium](https://dash.adoptium.net/): Java 11 6,570,025 vs. Java 17 4,742,938 (GitHub) Downloads.
* [InfoWorld](https://infoworld.com/article/3652408/java-8-still-dominates-but-java-17-wave-is-coming-survey.html): "[…] 37% of respondents in the Perforce-sponsored survey answered Java 8. The runner-up was Java 11, used by 29% of those surveyed. […] Following Java 8 and Java 11 in usage were Java 12 or newer (12%) […]"
* [Hibernate](https://hibernate.org/orm/releases/6.0/): for the new major version 6, the project decided to use Java 11 as its baseline.

This may (or hopefully) change over time, especially with frameworks like Spring 6 using Java 17. But it's already a big step for Pioneer to diverge from Jupiter's baseline. From a maintainer perspective, I would surely enjoy it a lot to do stuff with Java 17, OTOH I'm afraid this will cost us more users than moving a bit slower, i.e., to Java 11.

**Comment by filiphr** [comment]
Some of those numbers are actually showing that Java 17 has better adoption.

* Adoptium - Java 11 has been released on 25th of September 2018 and Java 17 on 14th of September of 2021. Which makes those Java 17 numbers quite impressive. In addition to that, the numbers from Adoptium are more towards what users are using to run their applications and not their baselines. The Java 8 numbers there are smaller than Java 11, and I seriously doubt that more people have Java 11 as a baseline, compared to Java 8.
* InfoWorld - It also says "Among survey respondents who knew of their organization’s upgrade plans, 37% planned to upgrade to JDK 17, within the next six months. Another 25% plan to upgrade to JDK 17 within the next six to 12 months." Those percentages are higher then the 29% of those that use Java 11. On top of all of that there were 876 people that answered the survey.
* Hibernate - Indeed, they decided to use Java 11 as Hibernate 6 baseline. I don't know why they did it.
* [Spring 6 / Spring Boot 3](https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6) will be baselined on Java 17 and will be released by the end of this year, they are skipping Java 11 entirely. This move in my opinion is what will drive the move to Java 17 in other frameworks and projects.
* [Micronaut 4](https://github.com/micronaut-projects/micronaut-core/issues/7006) also plans to baselin on Java 17 and thus drop Java 8 and 11 support.

**Comment by filiphr** [comment]
>From a maintainer perspective, I would surely enjoy it a lot to do stuff with Java 17, OTOH I'm afraid this will cost us more users than moving a bit slower, i.e., to Java 11.

In my opinion, as a maintainer of a different open source project. The amount of users that you will lose if you baseline to Java 11 or Java 17 will be the same.

**Comment by nipafx** [comment]
I'd love to follow your argument, @filiphr, but we know for a fact that we will lose at least 3 users when going to 17 instead of 11 and they're all maintainers. 😬  It may sound egoistic not to update just because we can then no longer use Pioneer ourselves, but it's not that clear cut:

* The detriment of not updating is borne by the same people (plus contributors) because they can't use all the fancy new features - I don't think Pioneer's API will suffer from sticking to 11 (if it does, we will reconsider).
* Pioneer is a hobby project and I think "work on a project that you can't use" is not a particularly fun proposition.

Let's see where we stand in a year or two. 🤞🏾

**Comment by Bukama** [comment]
Just wanted to post this announcement by @nipafx 

> As recently mentioned, we're working towards releasing 2.0, which will require Java 11. We've created a milestone for that (https://github.com/junit-pioneer/junit-pioneer/milestone/7), which focuses on closing currently open PRs, clean up, and organizational matters - I expect this to take a few more months. We will also fix bugs that are reported in the meantime, but won't tackle new feature PRs (or at least I won't - if others want to, that's ok, too). As bugs get fixed and open feature PRs are merged, we will release more 1.x versions.


Means we will update to Java 11 short before 2.0

**Comment by Bukama** [comment]
First part of this (updating the base Java version) has been merged into the `lab/2.0` branch. 
Second step now could be changing code, like using `var` or something.

**Comment by Bukama** [comment]
I had a look at the code and except some minor `var` usage (in test classes) I didn't find anything useful. That's why I close this issue.

If someone wants to make use of Java 9+ language features feel free to open PR referencing to this issue.
