### ISSUE TITLE
Update AssertJ to a newer version

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#618]
Our assertion library `AssertJ` should be updated to a newer version. But not to just bumping the version number, but make then proper / improving the use of generic `SELF` assertions.

**Comment by nipafx** [comment]
Thanks to the harsh compiler flags, the build fails after the update with raw types in one of our classes. I didn't investigate but it feels like we can improve the API by returning a more specific type, maybe `SELF`?

**Comment by Michael1993** [comment]
I'm not really sure what improvements could be made. Could you give me an example @Bukama ?

**Comment by scordio** [comment]
Gradle noob question: how to reproduce the offending warnings/errors? I did a few builds but didn't spot anything strange with the branch from #619.
