### ISSUE TITLE
JsonClassPathSource support generics type?

### ISSUE THREAD

**Issue by sherlockEix** [junit-pioneer/junit-pioneer#639]
Hello. I've tried the demo below but it doesn't work. I think `JsonClassPathSource` can't deserialize json array to java list. Is there any other way to implement it? Thanks.

Java code:
```java
@JsonClassPathSource("test.json")
void test(List<Person> persons){
  log.info("{}",persons)
}
```
Json file:
```json
[
  {
    "name": "a",
    "age": 23
  },
  {
    "name": "a",
    "age": 23
  }
]
```

**Comment by Michael1993** [comment]
Hi there @sherlockEix !

Just for the sake of completeness, could you also copy here your `Person` class and the exception message (I assume) you get when trying to execute the test above?

**Comment by sherlockEix** [comment]
yes. this is my demo. i hope that `jedisList` can be deserialized from `JEDIS` path

- java code
```
private static final String JEDIS = "org/junitpioneer/jupiter/json/jedis.json";
@ParameterizedTest
@JsonClasspathSource(JEDIS)
void listObject(List<Jedi> jedisList){
	System.out.println("jedisList = " + jedisList);
}
```
- jedis content
```
[
  {
    "name": "Luke",
    "height": 172
  },
  {
    "name": "Yoda",
    "height": 66
  }
]

```
- error
```
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<java.lang.Object>` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
```

**Comment by Michael1993** [comment]
Oh, yeah, I see where the problem is - you pass a list of objects to your test that expects a list of lists. See, when you execute a parameterized test, it expects an input (a list) which it converts to single parameters. In your example your parameter is a list, so the test tries to convert your input to a list but it can not do that because you supplied a simple list not a list of lists.

To demonstrate with an example, this should work:
```java
@ParameterizedTest
@JsonClasspathSource(JEDI_LIST)
void listObject(List<Jedi> jedisList){
	System.out.println("jedisList = " + jedisList);
}
```

Jedi list:
```json
[
  [
    {
      "name": "Luke",
      "height": 172
    },
    {
      "name": "Yoda",
      "height": 66
    }
  ]
]
```

**Comment by Michael1993** [comment]
This actually makes me wonder _why_ you would want to use a `List` as an input parameter. Do you want to test something on a collection of objects at the same time? Carefully examine your test - if you use a `for` loop or any other method to iterate and/or examine single objects in your passed `List` you might want to reconsider letting the `ParameterizedTest` do the iteration for you and just writing a test with a single object in mind.

**Comment by sherlockEix** [comment]
i want use `@JsonClasspathSource` to prepare my integrate test data. i would like to write data to json file. it's a complex struct. maybe single object or list. then. i will use injected object(list) to do test. my first idea is i write a utils to load data and deserialize to object. but i found `@JsonClasspathSource` so i use it to prepare my  complex test data.
