### ISSUE TITLE
Review README

### ISSUE THREAD

**Issue by nipafx** [junit-pioneer/junit-pioneer#642]
Give the README a general review to see if everything's still up to date. Things that are known to need fixing:

* remove Steve Moyer from list of maintainers
* sort all contribution lists lexicographically (there are some mistakes here and there)

**Comment by aepfli** [comment]
we could also increase our quality by using markdownlint to reduce issues with formatting and style - might be worth to add as a criteria :)

**Comment by nipafx** [comment]
`TooMuchToolingException`

**Comment by Michael1993** [comment]
Also remove JSR-305 from the README#dependencies section.
