### ISSUE TITLE
Introduce JUnit Jupiter variant of Guava's Collection Test Suite Builders

### ISSUE THREAD

**Issue by jbduncan** [junit-pioneer/junit-pioneer#65]
See https://github.com/google/guava/issues/3039 for more info, where I started the conversation. :)

**Comment by jbduncan** [comment]
I wonder if this would an area of interest to you @nicolaiparlog, considering that you've [blogged](https://blog.codefx.org/techniques/testing/test-collection-implementations-with-guava/) about Guava's collection suite builders in the past?

**Comment by jbduncan** [comment]
I've actually been starting to work on this in my own as-of-yet unpublished project, but I'm wondering now if it's worth trying to merge my efforts into junit-pioneer, as opposed to starting my own distinct open source project.

@nicolaiparlog WDYT?

**Comment by jbduncan** [comment]
@nicolaiparlog Thanks for getting back!

I actually went and semi-published my own project a few days ago (https://github.com/jbduncan/jupiter-collection-testers). It's not ready yet, for there's no documentation yet, and only `List#add(Object)` and `List#add(int, Object)` can be tested (or partially tested) so far. But I'd love to receive feedback!

**Comment by jbduncan** [comment]
...and issues and PRs, for that matter. :)

**Comment by smoyer64** [comment]
@jbduncan That's the first example of a kotlin build script I've seen in the wild.  I've read a bit about it but (being a Maven person) haven't actually tried it on anything.  What are you impressions?

**Comment by jbduncan** [comment]
@smoyer64 The first Kotlin build script example I personally saw in the wild was over at https://github.com/tbroyer/gradle-errorprone-plugin. :)

On one hand, I find it's a PITA to find documentation for the Gradle Kotlin DSL. The only good reference I've found so far is https://github.com/gradle/kotlin-dsl/tree/master/samples, and sadly it doesn't cover everything.

On the other hand, it's forced me to get to know Gradle a bit more deeply, and the reward is I get to use Kotlin and benefit from auto-completion when using IntelliJ IDEA. Not entirely sure if it's worth the trade-off, though. :)

**Comment by nicolaiparlog** [comment]
@jbduncan Does your work on your own project mean that you no longer consider adding this to Pioneer? That would be a little sad for us :cry:, but if so, this issue can be closed.

While I would love to take a closer look at your implementation, I'm afraid it would require a freak accident for an opening in my calendar that allows for that, so don't hold your breath. Sorry. :frowning_face:

**Comment by jbduncan** [comment]
@nicolaiparlog Yeah, sadly I'm no longer considering adding my own project to Pioneer, mainly because of the amount of effort I've put into it thus far, and also because I want to use it as a platform for experimenting with tools like Refaster. :(

I eventually intend to link it in https://github.com/junit-team/junit5/wiki/Third-party-Extensions, so it can stand side-by-side with JUnit Pioneer and other projects.

And if I have any other ideas for extensions in the future, I'd be more than happy to consider opening an issue on JUnit Pioneer again. :)

**Comment by nicolaiparlog** [comment]
Godspeed, then, and I hope to read from you again. :smiley:
