### ISSUE TITLE
Convert ArrayNode to List

### ISSUE THREAD

**Issue by bartsimp** [junit-pioneer/junit-pioneer#654]
I'd like to convert a json array into a java List, but I got this error:

```
Error converting parameter at index 0: No implicit conversion to convert object of type com.fasterxml.jackson.databind.node.ArrayNode to type java.util.List
org.junit.jupiter.api.extension.ParameterResolutionException: Error converting parameter at index 0: No implicit conversion to convert object of type com.fasterxml.jackson.databind.node.ArrayNode to type java.util.List

```
Here my test:
```
@ParameterizedTest
@JsonClasspathSource("items.json")
void test1(@Property("items") List<Integer> items) {
    assertFalse(items.isEmpty());
    assertEquals(2, items.size());
}

@ParameterizedTest
@JsonClasspathSource("items.json")
void test2(@Property("items") Integer[] items) {
    assertEquals(2, items.length);
}
```

items.json:

```
[
  {
    "items": [ 1, 3 ]
  },
  {
    "items": [ 2, 4 ]
  }
]
```

what am I missing?

**Comment by Michael1993** [comment]
Hi @bartsimp!

Unfortunately, I don't have a lot of time right now, but I wanted to call your attention to this issue:
https://github.com/junit-pioneer/junit-pioneer/issues/639

Your problem is in the JSON file.

**Comment by beatngu13** [comment]
Hey @bartsimp!

We use [Jackson](https://search.maven.org/artifact/com.fasterxml.jackson.core/jackson-databind) as our [JSON parser](https://junit-pioneer.org/docs/json-argument-source/#json-parser-integration). Jackson creates an [`ArrayNode`](https://fasterxml.github.io/jackson-databind/javadoc/2.13/com/fasterxml/jackson/databind/node/ArrayNode.html) from `items`, which implements [`Iterable`](https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/lang/Iterable.html):

```java
@ParameterizedTest
@JsonSource("""
		[
		  {
			"items": [ 1, 3 ]
		  },
		  {
			"items": [ 2, 4 ]
		  }
		]
		""")
void test1(@Property("items") Iterable<Integer> items) {
	assertThat(items).hasSize(2);
}
```

Alternatively, as suggested by @Michael1993, you can also modify your JSON:

```java
@ParameterizedTest
@JsonSource("""
		[
		  [ 1, 3 ],
		  [ 2, 4 ]
		]
		""")
void test2(List<Integer> items) {
	assertThat(items).hasSize(2);
}
```

Feel free to reopen this issue if that doesn't help you.

**Comment by bartsimp** [comment]
Thanks for suggestions but I'm afraid is not exactly what I'm looking for...
I'd like to test a method like
```
public Integer sum(List<Integer> items) {
    return items.stream().reduce(0, Integer::sum);
}
```

using a json parameterized test which contains also the expected response

```
@ParameterizedTest
    @JsonSource("""
          [
                {
                  "items": [1, 3],
                  "expectedResult": 4
                },
                {
                  "items": [2, 4],
                  "expectedResult": 6
                }
          ]
          """)
    void testSum(
            @Property("items") List<Integer> items,
            @Property("expectedResult") Integer expectedResult
    ) {
        assertThat(
                new Calculator().sum(items),
                equalTo(expectedResult)
        );
    }
```

do you think is possible?

**Comment by beatngu13** [comment]
@bartsimp I actually made a mistake, [my suggestion above](https://github.com/junit-pioneer/junit-pioneer/issues/654#issuecomment-1199799097) throws the following exception once you dig a little deeper:

```text
java.lang.ClassCastException: class com.fasterxml.jackson.databind.node.IntNode cannot be cast to class java.lang.Integer
```

A workaround (I don't like it though):

```java
@ParameterizedTest
@JsonSource("""
		[
			  {
				"items": [1, 3],
				"expectedResult": 4
			  },
			  {
				"items": [2, 4],
				"expectedResult": 6
			  }
		]
		"""
)
void testSum(
		@Property("items") Iterable<IntNode> items,
		@Property("expectedResult") int expectedResult
) {
	List<Integer> itemsList = StreamSupport.stream(items.spliterator(), false)
			.map(IntNode::intValue)
			.toList();
	Integer actualResult = new Calculator().sum(itemsList);
	assertEquals(expectedResult, actualResult);
}
```

---

The "problem" is this method:

https://github.com/junit-pioneer/junit-pioneer/blob/main/src/main/java/org/junitpioneer/jupiter/json/JacksonNode.java#L64-L88

No case matches, which is why we return `node` (`JsonNode` / `ArrayNode` with `IntNode`s).

I reopen this issue. I'm not that familiar with the Jackson API, and I'm not sure how type erasure will be a problem here, but I believe we can do better.
