### ISSUE TITLE
Disable Parameterized Test extensions not able to handle runtime input value(s) due to Java annotation attributemust be a constant expression

### ISSUE THREAD

**Issue by TimeInvestor** [junit-pioneer/junit-pioneer#655]
A practical use case for a Disable Parameterized Test extension e.g. DisableIfAnyArgument is to select test cases to run when a test case's target test env matches current test env which is provided via an environment variable or system property.

Sample code:
```java
class MyTestClass {

    static final String TEST_ENV = System.getProperty("testEnv");

    @DisableIfAnyArgument(contains = TEST_ENV)
    @ParameterizedTest
    @CsvSource(textBlock = """
                    TC1,    targetTestEnv1,    testDataForEnv1,
                    TC2,    targetTestEnv2,    testDataForEnv2,
            """)
    void myTest(String tcId, String targetTestEnv, String testData) {
        ....
    }
}
```

However, the line `@DisableIfAnyArgument(contains = TEST_ENV)` will throw error
`The value for annotation attribute DisableIfAnyArgument.contains must be a constant expression`

Is there any way to overcome this issue?
Any input/advice will be appreciated.
Thanks in advance.

**Comment by Michael1993** [comment]
Hi @TimeInvestor ! 👋 

Have you tried [DisableIfSystemProperty](https://junit.org/junit5/docs/5.2.0/api/org/junit/jupiter/api/condition/DisabledIfSystemProperty.html) and/or [DisableIfEnvironmentVariable](https://junit.org/junit5/docs/5.2.0/api/org/junit/jupiter/api/condition/DisabledIfEnvironmentVariable.html)?

**Comment by TimeInvestor** [comment]
> Hi @TimeInvestor ! 👋 
> 
> Have you tried [DisableIfSystemProperty](https://junit.org/junit5/docs/5.2.0/api/org/junit/jupiter/api/condition/DisabledIfSystemProperty.html) and/or [DisableIfEnvironmentVariable](https://junit.org/junit5/docs/5.2.0/api/org/junit/jupiter/api/condition/DisabledIfEnvironmentVariable.html)?

Not work for my case as I need to match current test env with target test env of a test case, not simply checking current test env value.

**Comment by beatngu13** [comment]
Hey @TimeInvestor,

as you correctly noticed, the value of an annotation attribute must be a constant expression (see [JLS, Java SE 18 Edition, 9.7.1. Normal Annotations](https://docs.oracle.com/javase/specs/jls/se18/html/jls-9.html#jls-9.7.1)).

Would a method source be feasible for you?

```java
static final String TEST_ENV = System.getProperty("testEnv");

@ParameterizedTest
@MethodSource
void myTest(String tcId, String targetTestEnv, String testData) {
	// ...
}

static Stream<Arguments> myTest() {
	return Stream.of(
			Arguments.of("TC1", "targetTestEnv1", "testDataForEnv1"),
			Arguments.of("TC1", "targetTestEnv2", "testDataForEnv2")
	).filter(args -> args.get()[1].equals(TEST_ENV));
}
```

Note that this more of a "poor man's version". Arguments, i.e. test cases, aren't disabled but disappear completely. That is, you will basically "lose" the filtered test cases from, e.g., reports.

If you want an implementation that actually _disables_ test cases based on a dynamic runtime value (like an environment variable or system property), you would have to come up with your own extension; something like a `EnableIfTestEnvironmentExtension`. This is probably a good starting point:

https://github.com/junit-pioneer/junit-pioneer/blob/main/src/main/java/org/junitpioneer/jupiter/params/DisableIfArgumentExtension.java

Feel free to reopen this issue if you have further questions. Or if you have a good idea for a more general version you would like to contribute to Pioneer. ✌️

**Comment by Michael1993** [comment]
Hi (again) @TimeInvestor!

Just a side-note, you might find this a good approach as well: host your own extension. It's a fairly trivial exercise to copy-paste the [`DisableIfArgumentExtension`](https://github.com/junit-pioneer/junit-pioneer/blob/0a8d9fc5308c0f69ce0110461bb95fd9e61e551b/src/main/java/org/junitpioneer/jupiter/params/DisableIfArgumentExtension.java) from our code base (including annotations) and re-write the annotations/extensions to support environment variables/system properties.

In fact, I just spent 10 minutes and made [a new branch you can pull to copy-paste from just for you.](https://github.com/junit-pioneer/junit-pioneer/tree/lab/timeinvestor)

**Comment by TimeInvestor** [comment]
> Hi (again) @TimeInvestor!
> 
> Just a side-note, you might find this a good approach as well: host your own extension. It's a fairly trivial exercise to copy-paste the [`DisableIfArgumentExtension`](https://github.com/junit-pioneer/junit-pioneer/blob/0a8d9fc5308c0f69ce0110461bb95fd9e61e551b/src/main/java/org/junitpioneer/jupiter/params/DisableIfArgumentExtension.java) from our code base (including annotations) and re-write the annotations/extensions to support environment variables/system properties.
> 
> In fact, I just spent 10 minutes and made [a new branch you can pull to copy-paste from just for you.](https://github.com/junit-pioneer/junit-pioneer/tree/lab/timeinvestor)


That's really super nice of you @Michael1993 👍

It surprises me how responsive and supportive this extension community is!

Thank you for all of your help ❤️

**Comment by Michael1993** [comment]
Sure, just let me know when you no longer need the branch so I can delete it - the maintainers like everything nice and tidy 😅

**Comment by Michael1993** [comment]
I just realised I made an error initially with the branch. I went back to verify the behaviour and realised I forgot to update the input verification step. 😭

Sorry! But it's fixed now!

**Comment by TimeInvestor** [comment]
Thanks @Michael1993 
I made a clone of the code and am studying it.

**Comment by TimeInvestor** [comment]
Hi @Michael1993 
I am done with the code and solved my issue.
You could remove the branch.
Thanks again.
