### ISSUE TITLE
Convert Markdown files to AsciiDoc

### ISSUE THREAD

**Issue by Michael1993** [junit-pioneer/junit-pioneer#656]
GitHub supports the .adoc format. I propose we move all our `.md` files to `.adoc`.

**Comment by Bukama** [comment]
I'm fine with both :)

**Comment by nipafx** [comment]
Sure, go for it! 😃

(That's addressed at anybody who's interested to do this, not just Michael. 😉)

**Comment by fischer1983** [comment]
Hello! Do you want this change yet? I can do this, or any work what do you'll want.

**Comment by Bukama** [comment]
@fischer1983 If you wanna do it, feel free to do so :)

**Comment by DhirajSardar** [comment]
I am new to open source can anybody help me out to contribute ?

**Comment by beatngu13** [comment]
@DhirajSardar check out our [contributing guide](https://github.com/junit-pioneer/junit-pioneer/blob/main/CONTRIBUTING.md). And if you have further questions, feel free to open a separate issue.

**Comment by DhirajSardar** [comment]
> Hi @DhirajSardar, I read the guides and a started writing this documentation. But fell free to do, or if you prefer we can do this together, you can contact me through my email.

I will be great to collaborate.

**Comment by DhirajSardar** [comment]
> 



> Hi @DhirajSardar, I readed the guides and a started writing this documentation. But fell free to do, or if you prefer we can do this together, you can contact me through my email.

We can do it together.

**Comment by DhirajSardar** [comment]
There are 3 markdown files which one is supposed to be converted into ascii docs?

**Comment by beatngu13** [comment]
As [Michael said](https://github.com/junit-pioneer/junit-pioneer/issues/656#issue-1336274053):

>I propose we move **all** our `.md` files to `.adoc`.

We actually have four Markdown files:

1. `CODE_OF_CONDUCT.md`
2. `CONTRIBUTING.md`
3. `LICENSE.md`
4. `README.md`

When you look at e.g. the [asciidoctor repo](https://github.com/asciidoctor/asciidoctor), they have multiple AsciiDoc files, which are all rendered properly.

**Comment by Bukama** [comment]
> HI. Is anyone working on this _issue_ ?

No. Do you want to do it?

**Comment by DhirajSardar** [comment]
Sure, I will @Bukama.

**Comment by DhirajSardar** [comment]
Can anyone please tell how to run this project in my System?

**Comment by DhirajSardar** [comment]
Hey! 
Is anyone working on this   issue ?

**Comment by Bukama** [comment]
> Hey! Is anyone working on this issue ?

According to your past comments I assigned you on June 22
