### ISSUE TITLE
Review 3rd-party application access

### ISSUE THREAD

**Issue by Michael1993** [junit-pioneer/junit-pioneer#663]
> Aepfli: We should evaluate which 3rd party applications still have access to junit pioneer, and maybe remove those which we do not need anymore, like travisCI or Appveyor

**Comment by Bukama** [comment]
I assign this to @nipafx as he has access to security tokens, but I think he removed all unneeded ones in the past.

**Comment by aepfli** [comment]
- Travis CI
- bintray
- AppVeyor CI
- AppVeyor

definitely not anymore, about the other two I am not sure if anybody is using them, they look like convenience tools to me

**Comment by nipafx** [comment]
I denied all access. If something breaks, somebody will notice and we can allow access again. 😁
