### ISSUE TITLE
Merge lab/2.0 branch before releasing Pioneer 2.0 

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#669]
We are preparing the Pioneer 2.0 release on the `lab/2.0` branch to give us the possibility to still merge non-breaking changes into the 1.x main branch and maybe do 1.x releases.

When we ready to release 2.0, meaning all 2.0 tickets are done, we need to merge the branch and do the release.

**Comment by Bukama** [comment]
@nipafx suggested in Discord that we could release a 2.0.0-RC1 as soon as all issues from the milestone are done and merged. On today's team meeting @beatngu13 and I agreed that this is good idea to show people that there is a new major release coming. Biggest concerns we had was that people won't try the RC because the RC shows that it might not be stable. So feedback may not be as much as we hope to get.

Current state of 2.0 milestone: Freeport extension needs to be refactored, author of the current PR said three days ago, that he wants to to this in the upcoming days.

**Comment by nipafx** [comment]
Unblocked! Fuck yeah! 🥳
