### ISSUE TITLE
Include and maintain `junit5-jupiter-extension` samples

### ISSUE THREAD

**Issue by sormuras** [junit-pioneer/junit-pioneer#67]
The @junit-team is show-casing some simple Jupiter extension samples at https://github.com/junit-team/junit5-samples/tree/master/junit5-jupiter-extensions Sometimes people ask for binary distributions of these examples to use them in their projects. Offering such binaries contradicts the purpose of the `junit5-samples` project: it shows simple and basic extension examples in source format.

I propose to "copy & paste" the source from `junit5-samples/junit5-jupiter-extensions` into an appropriate package of `junit-pioneer`. Document, complete and polish the implementation and have the extension sail with pioneer.

What do you think?

**Comment by nicolaiparlog** [comment]
> What do you think?

Yes. :wink:

Can you create a separate issue for each feature and give me two days to comment on them? I also had some ideas regarding randomization and would like to discuss them.

**Comment by nicolaiparlog** [comment]
Oh, look at #49.

**Comment by sormuras** [comment]
Yay, one done. Will create a new issue for the `@CartesianProductTest` building on the `@TestTemplate` feature.

**Comment by nicolaiparlog** [comment]
Can you add a list of features to the issue description and check them off as soon as you created an issue? That makes it easier to track how far this issue here progressed.

**Comment by sormuras** [comment]
Sure.

Closing this "umbrella" issue as all (two) `junit5-jupiter-extensions` samples are covered by their own issues now. #49 and #68. The latter one will receive some bullet points soon.
