### ISSUE TITLE
Build pipeline workflow does not trigger

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#673]
The build pipeline does not trigger.
According to @aepfli we introduced a bug in the branches section

> // EDIT: looks like we do have a bug in the yml and it should be actually `**`

**Comment by Bukama** [comment]
I don't think it has to be a double star as @aepfli thought. Git history shows that we have used a single star for pull request since ages.

**Comment by aepfli** [comment]
Yeah but `*` matches simple paths like `main` - be aware for pull requests it is the target branch ;) - but not branches with "nested paths" like `lab/name`

**Comment by Michael1993** [comment]
I like just removing the `branches` line - as far as I understood it's a filtering option where we don't want to do filtering.

**Comment by aepfli** [comment]
Should we do a separate pr, or is it acceptable that we fix this with #670?

**Comment by Michael1993** [comment]
For me it's acceptable - it's really minor, does not affect anyone outside the project and we (kind of) already agreed on the solution.

**Comment by Bukama** [comment]
I vote for a separate PR to identify the commit with the fix easier in the future (I would not assume that it's in a commit name "update range sources").
