### ISSUE TITLE
Rename "merge-ready" label to "full-build"

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#679]
The wording "merge-ready" label is misleading since we restructured our build scripts as it's only there to trigger the full build (e.g. for testing purposes), regardless if the PR is ready to merge or not. 

In Discord @nipafx suggested to rename it to "full-build". This issue is to discuss it here on Github

**Comment by Michael1993** [comment]
Doesn't need a discussion IMO. Let's rename it!

**Comment by nipafx** [comment]
I agree, we should rename it. But lets wait for the build crew to hear their opinion. 😉 

cc @beatngu13 @aepfli

**Comment by aepfli** [comment]
Not strong opinion regarding that ;) I do agree it makes more sense ;)
