### ISSUE TITLE
Knock Nicolai down a peg

### ISSUE THREAD

**Issue by nipafx** [junit-pioneer/junit-pioneer#683]
CONTRIBUTING.md contains lines like:

> As such, I [Nicolai] have the right to overrule any decision

And:

> On [sic] other words, the buck stops with me

What an ego! I think it's time to take this dipshit down - once 2.0 gets released, we depose him. All with me post ✊🏾!

**Comment by Bukama** [comment]
You know I'm an offical of the government - so no ⛔

**Comment by nipafx** [comment]
Fixed by c379221.
