### ISSUE TITLE
Docs for resources extension has broken links and a typo

### ISSUE THREAD

**Issue by jbduncan** [junit-pioneer/junit-pioneer#691]
Specifically:
- On the [top-level docs page](https://junit-pioneer.org/docs/), it says, "[Creating and Sharing Resourced](https://junit-pioneer.org/docs/resources/)". (Typo at the end of "Resourced".)
- On the [resources page](https://junit-pioneer.org/docs/resources/), the link with text "[Temporary directory](https://junit-pioneer.org/docs/resources/docs/temp-directory)" accidentally points to "/docs/resources/docs/temp-directory", but it should point to "/docs/temp-directory".
- On the [temp directory page](https://junit-pioneer.org/docs/temp-directory/), the link with text "[the article covering resources in general](https://junit-pioneer.org/docs/temp-directory/docs/resources)" should point to "/docs/resources".

I'm unsure how to correct the docs, as I can't find references to "Resourced" in the source code here, and I'm not so sure what caused the link changes. So would you mind pointing me in the right direction, team?

**Comment by Bukama** [comment]
Thank you for the report!

**Comment by nipafx** [comment]
Most of those errors were fixed by #690 - we just didn't trigger a website build, yet, and that's why the changes weren't reflected. I've done that now. The only one that remains is the broken link that I've just fixed in a7a639a together with a bunch of others.

**Comment by nipafx** [comment]
FFS, I missed the one @jbduncan pointed out. How did that happen?! 🤬
