### ISSUE TITLE
Upgrade to Gradle 7.6

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#693]
Gradle 7.6 with support for Java 19 was released on 2022-11-25. so we could upgrade our build pipeline

**Comment by beatngu13** [comment]
Only one the `lab/2.0` branch I guess? Probably not worth the effort to do it on `main` too, given we are relatively close to 2.0. When we went from 7.4 to 7.5. in #651, this required quite some changes.

**Comment by Bukama** [comment]
I'm fine with only upgrading the lab branch for 2.0
