### ISSUE TITLE
Add support for composed annotations to all annotations

### ISSUE THREAD

**Issue by eeverman** [junit-pioneer/junit-pioneer#696]
Looking through the source code of the annotations used to register extensions, it looks like none of them (or none that I could find) support [composed annotations](https://junit.org/junit5/docs/current/user-guide/#writing-tests-meta-annotations), that is, reusing the annotation in another annotation.

JUnit's user manual has a few examples of this in the [declarative extension registration section](https://junit.org/junit5/docs/current/user-guide/#extensions-registration-declarative).  It would allow users who repeatedly use several extensions together to bundle those into a single annotation like this:
```java
@Retention(RetentionPolicy.RUNTIME)
@Target({ TYPE, METHOD, ANNOTATION_TYPE })
@Stopwatch  @DefaultLocal("Local.UK") @SetSystemProperty(key="BROILER" value="ON")
public @interface StandardTestSetup { }
```

To enable that, two things would be needed:
1. The `ANNOTATION_TYPE` would need to be added to the `@Target` of the annotations
2. The `PioneerAnnotationUtils` would need to be able to find them.

Currently the PioneerAnnotationUtils class only looks for the specified annotation - It doesn't check to see what meta-annotations an annotation might have.  I think that happens (or doesn't happen) [right here](https://github.com/junit-pioneer/junit-pioneer/blob/1330e8bd50a5088c1ebe833967d045fcd2d9ee74/src/main/java/org/junitpioneer/internal/PioneerAnnotationUtils.java#L210).

**Comment by Michael1993** [comment]
Hi @eeverman! Thank you for opening the issue.

I've looked through our annotations and it seems we do have some of them that do not support composed annotations (namely `@StdIo` and `@ReportEntry`). All our other annotations types either have `ANNOTATION_TYPE` or `TYPE` in their `@Target`.

I also looked at `PioneerAnnotationUtils` and I can _kind of_ see your issue? The line you are pointing out is a naïve approach and if we are trying to find _only the first meta-annotation_ it wouldn't work. I would like to point out that the method would **still work** (but could take a bit longer), I'm only referring to the approach taken in the specific line you mentioned.

**Comment by eeverman** [comment]
Nice fix - Thank you!

I had been looking at StdIo when I reported the issue.... and I guess forgot that `TYPE` included the annotation type.  I also had a test that was trying to verify that composed annotation worked, but I see now that it included some other assumptions.

Thanks again!
