### ISSUE TITLE
Allow user to provide Jackson ObjectMapper

### ISSUE THREAD

**Issue by nipafx** [junit-pioneer/junit-pioneer#705]
When #704 (and the potential follow-up mentioned therein) is implemented, the user can globally configure a selection of modules but it's foreseeable that some users may have more detailed configuration wishes. While it's be feasible to slowly expand the configuration parameters, so this can all happen through Pioneer, an escape hatch would help until then. So I propose to create an SPI that lets the user provide a fully configured `ObjectMapper` instance that we then use.Specifically:

* add configuration parameter `junitpioneer.jackson.mapper`
* interpret the value as the name of a class that implements the new interface `ObjectMapperSupplier` (not `Supplier<ObjectMapper>` - maybe we need more control in the future, so better to have our own type)
* create an instance of that class, call `create` (or similar) and use the created mapper in `JacksonJsonConverter`

(This issue was spawned by #624 and #629.)

**Comment by Michael1993** [comment]
New SPI (`ObjectMapperProvider`) added in #741.
