### ISSUE TITLE
Update code to Java 11

### ISSUE THREAD

**Issue by nipafx** [junit-pioneer/junit-pioneer#706]
Now that we baseline against Java 11, we can use newer language features and APIs. In some places, the improvements are marginal (e.g. most `var`s), but in others the code becomes noticeably more readable (e.g. handling of `InaccessibleObjectException` in `EnvironmentVariableUtils`). Making a dedicated effort to find the latter pieces of code and refactoring them will improve the code base.

**Comment by talios** [comment]
If the target bytecode is now 11 - can we have a major version bump?

**Comment by Michael1993** [comment]
> If the target bytecode is now 11 - can we have a major version bump?

You mean to, like, 2.0.0?

**Comment by talios** [comment]
> You mean to, like, 2.0.0?

Ewps *hangs head in shame and hides* - um, yes - Just noticed that bump's been made already.  Move along - nothing to see here :)

**Comment by beatngu13** [comment]
Closed via #707.
