### ISSUE TITLE
@SetEnvironmentVariable annotation works only on class target in kotlin project.

### ISSUE THREAD

**Issue by evgromva** [junit-pioneer/junit-pioneer#708]
Unable to use ```@SetEnvironmentVariable``` annotation with methods, it works only on class target

_JDK_ version 11
_junit-pioneer_ version 1.9.1 or 2.0.0-RC1

**Comment by jbduncan** [comment]
@evgromva Did you mean to close this issue so soon, or have you managed to fix your problem already? :)

**Comment by evgromva** [comment]
@jbduncan It worked very weird and annotation didn't have effect on method target. But then somehow started to work idk )
