### ISSUE TITLE
Release log feedback

### ISSUE THREAD

**Issue by TWiStErRob** [junit-pioneer/junit-pioneer#711]
Hi, I just got an update for the latest 2.0 stable release:
![image](https://user-images.githubusercontent.com/2906988/216678679-ae2e6c46-01bc-4055-a397-da539024d490.png)

it looks really funny that the changes between stables is not recorded in the GitHub release tags, one could easily read that the only "prominent changes" in this 2.x release is me fixing a typo 😅 and that CI uses the latest Java Action.

It's just an FYI, I'm not sure how you would action it. I would probably at least list the reason for the major release, rather than linking another milestone release. There's no problem with duplication in GH releases. You could list all the alpha/beta/milestone releases that happened between stables, and also copy-paste all the changes that were involved in all of these.

**Comment by beatngu13** [comment]
Thanks for the heads up! I have manually updated the changelog (the one generated was really awful).

BTW we have #622 for our changelog issues. Feel free comment there. ✌️
