### ISSUE TITLE
Run method before rerun test 

### ISSUE THREAD

**Issue by perkele99** [junit-pioneer/junit-pioneer#712]
I am running the test using @RetryingTest(2), is it possible to call a method where I will clear the application data after the test fails, before running the test again?

**Comment by beatngu13** [comment]
Hi @perkele99,

you can use, e.g., `@BeforeEach` to start with a clean application state:

```java
class PioneerRetryingTest {

	static int executionCount = 1;

	@BeforeEach
	void setUp() {
		System.out.println("@BeforeEach execution no. " + executionCount);
	}

	@RetryingTest(2)
	void test() {
		System.out.println("@RetryingTest execution no. " + executionCount);
		if (executionCount++ < 2) {
			throw new AssertionError();
		}
	}

}
```

Output:

```text
@BeforeEach execution no. 1
@RetryingTest exeuction no. 1

[...]

@BeforeEach execution no. 2
@RetryingTest exeuction no. 2
```

Does this help?

**Comment by perkele99** [comment]
data cleaning takes a long time and I would prefer to do it only when the tests fail

but if there is no other way, the idea from @BeforeEach could also be

**Comment by beatngu13** [comment]
Jupiter's [`@RepeatedTest`](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/RepeatedTest.html) has [`RepetitionInfo`](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/RepetitionInfo.html), which allows to query, e.g., the current repetition.

Unfortunately, `@RetryingTest` doesn't have a comparable `ParameterResolver`, so I'm afraid you have to do this on your own. For example:

```java
class PioneerRetryingTest {

	static int executionCount = 1;

	@RetryingTest(3)
	void test() {
		if (executionCount > 1) {
			// Clean data only when an execution fails.
			cleanData();
		}
		if (executionCount++ < 2) {
			// Let first execution fail for demo purposes.
			throw new AssertionError();
		}
	}

```

**Comment by Michael1993** [comment]
We _could_ invoke a method between retries via reflection. Would that be something you are interested in @perkele99 ?

**Comment by Bukama** [comment]
> I think both of these are worth being explored. If so, I think we should create separate issues for them.

I agree and that's why I close this issue to enforce usage of the separate ones.
