### ISSUE TITLE
Change license to EPL v2.0

### ISSUE THREAD

**Issue by marcphilipp** [junit-pioneer/junit-pioneer#72]
The JUnit team has released JUnit 5 under EPL v2.0 which came out just in time for the first GA release (cf. https://github.com/junit-team/junit5/issues/1045).

AFAIK Pioneer picked EPL v1.0 because of JUnit. Thus, it would make sense to follow JUnit's lead and "upgrade" to EPL v2.0. That would make it a no brainer to move code between the two projects.

@smoyer64 @nicolaiparlog If you agree, I can submit a PR in the next few days.

**Comment by sbrannen** [comment]
> That would make it a no brainer to move code between the two projects.

I'd say that is actually essential to allow us to move code between the two projects.

In other words, having different licenses is in some ways a blocker for the success of Pioneer.

**Comment by smoyer64** [comment]
> That would make it a no brainer to move code between the two projects.

Yes ... I think that's the intent.  Provide a place where community contributions could live and (possibly) mature into parts of the core JUnit 5 project.

**Comment by nicolaiparlog** [comment]
I agree that the license should be upgraded. Does that change need explicit agreement by all committers? If so, judging by the fact that the opened the issue, I guess @marcphilipp is fine with it and I am, too. I will just assume @smoyer64 agrees as well (can you tell us explicitly, though?) and will prepare a PR soon.

**Comment by smoyer64** [comment]
@nicolaiparlog I agree

**Comment by nicolaiparlog** [comment]
> Does Spotless take care of putting the license at the top of each file? Or is there a Gradle equivalent to the Maven RAT plugin?

Yes, Spotless does that.

**Comment by marcphilipp** [comment]
Done in #80.
