### ISSUE TITLE
Support RetryingTest at class level

### ISSUE THREAD

**Issue by Avinm** [junit-pioneer/junit-pioneer#720]
Would it be possible to support RetryingTest at a class level?
This would enable developers reduce boilerplate by having top level annotations like:

`@RetryingTest(value = 3, onExceptions = BaseRetryableException.class)`

**Comment by beatngu13** [comment]
Hi @Avinm,

[`@RetryingTest`](https://github.com/junit-pioneer/junit-pioneer/blob/bfb2d02188b77009c2958a9035345b3d081e214a/src/main/java/org/junitpioneer/jupiter/RetryingTest.java#L76) is a [`@TestTemplate`](https://junit.org/junit5/docs/5.9.2/api/org.junit.jupiter.api/org/junit/jupiter/api/TestTemplate.html):

>`@TestTemplate` is used to signal that the annotated method is a _test template_ method.

Similar to [`@Test`](https://junit.org/junit5/docs/5.9.2/api/org.junit.jupiter.api/org/junit/jupiter/api/Test.html), it is designed to target only `ANNOTATION_TYPE` and `METHOD`. Jupiter had a similar request back in 2019 and they decided against a class-level `@Test` annotation:

>There are many ways to declare tests in Jupiter: `@Test`, `@TestFactory`, `@TestTemplate` (`@RepeatedTest`, `@ParameterizedTest`) -- we want them to be explicitly visible and not rely on a pattern that matches a method signature.

https://github.com/junit-team/junit5/issues/1761#issuecomment-466149986

Therefore, I tend to follow this decision.

**Comment by Avinm** [comment]
Makes sense.
However, would it then be possible to decouple the retry annotation from the notion of a test?
```
@Retry(on=..., attempts=...}
@Test
```

**Comment by beatngu13** [comment]
I think future development of `@RetryingTest` is (more or less) coupled to https://github.com/junit-team/junit5/issues/1558. There, [Marc Philipp said](https://github.com/junit-team/junit5/issues/1558#issuecomment-419401030):

>**Team Decision:** As a first step, we think this should be maintained externally as an extension based on `@TestTemplate`. We might potentially introduce support for rerunning flaky tests in core, but then it should support all kinds of testable methods, including `@ParameterizedTests`. We'd be happy to provide guidance and review such an extension, whether in the rerunner project, junit-pioneer or another project.

Note that you can also configure retries on the build level:

* Gradle: https://github.com/gradle/test-retry-gradle-plugin#retry-on-class-level
* Maven (only globally): https://maven.apache.org/surefire/maven-surefire-plugin/examples/rerun-failing-tests.html

But I would like to here what the other maintainers have to say?

**Comment by Avinm** [comment]
Unfortunately we are not in a gradle or maven environment so the above 2 solutions wouldn't work for us :(

**Comment by Avinm** [comment]
I have left a comment on  https://github.com/junit-team/junit5/issues/1558  to see if any progress can be made in this regard.

**Comment by Avinm** [comment]
> Not with the way JUnit Jupiter is currently operating
> In summary, with Jupiter working the way it does now, I don't think it would make a lot of sense to implement the extension this way.

I agree with both of these, so I tried to follow up with junit repo, but no luck yet.

In case you haven't seen it, testng seems to have a nice solution with
`IRetryAnalyzer` : https://testng.org/doc/documentation-main.html#rerunning

**Comment by nipafx** [comment]
That's pretty neat, but I don't think Pioneer is in a good position to implement such a feature. It seems more suitable for the level of test runner, i.e. [JUnit Platform Launcher](https://junit.org/junit5/docs/current/user-guide/#launcher-api), IDEs, or build tools. I'll close this issue for now, but feel free to reopen if things change and you think it could be implemented here after all.
