### ISSUE TITLE
Update Java, plugins, and dependencies

### ISSUE THREAD

**Issue by nipafx** [junit-pioneer/junit-pioneer#726]
Update the build matrix from Java 19 ~> 20 for the regular build and 20 ~> 21 for the experimental build. While at it, update all plugins and dependencies (keep in mind to stick to the same minor JUnit version).

**Comment by Bukama** [comment]
Note: In #718 we do the major upgrade to Gradle 8, for another update to 8.1 I opened #729. Maybe we need more / another dependencies.
