### ISSUE TITLE
Upgrade to JUnit 5.1.1

### ISSUE THREAD

**Issue by marcphilipp** [junit-pioneer/junit-pioneer#73]
Among other things, 5.1.1 contains crucial improvements for extension authors:

- New methods to query annotations on constructor/method parameters (to workaround a JDK bug) to `ExtensionContext`
- Introduction of `CloseableResource` which makes implementing extensions like `TempDirectory` (#39) a lot simpler.

Thus, we should upgrade to 5.1.1 as the minimum required version.

**Comment by sbrannen** [comment]
I vote that we skip 5.1.x and go straight to 5.2.

**Comment by nicolaiparlog** [comment]
Over in #64 we seem to agree that depending on the oldest release that supports all extensions is the way to go. With that in mind, I prefer 5.1.1.

**Comment by sormuras** [comment]
+1 for 5.2

The bug-fixes and improvements are worth it. https://junit.org/junit5/docs/snapshot/release-notes/index.html#release-notes-5.2.0

**Comment by marcphilipp** [comment]
I went ahead and created a PR for 5.1.1 as we can always update to 5.2 later.
