### ISSUE TITLE
Argument converter for converting integral numbers to byte arrays

### ISSUE THREAD

**Issue by scordio** [junit-pioneer/junit-pioneer#734]
In some projects related to cryptography, I'm often dealing with bitwise operations and I would like to write tests like the following:

```java
@ParameterizedTest
@ValueSource(ints = {Integer.MIN_VALUE, 0, 0xFF, 0xFFFF, 0xFFFFFF, Integer.MAX_VALUE})
void test(byte[] byteArray) {
  assertThat(byteArray).hasSize(4);
  // do some real stuff
}
```

where I can leverage binary and hexadecimal literals which would be automatically converted to a byte array using under the hood a [`ByteBuffer`](https://docs.oracle.com/javase/8/docs/api/java/nio/ByteBuffer.html) with [`BIG_ENDIAN`](https://docs.oracle.com/javase/8/docs/api/java/nio/ByteOrder.html#BIG_ENDIAN) order.

However, JUnit doesn't offer an implicit conversion for this combination of types. I originally raised junit-team/junit5#2702 but the team [prefers not to support it](https://github.com/junit-team/junit5/issues/2702#issuecomment-955676577) and would rather suggest an opt-in annotation, similar to [`@JavaTimeConversionPattern`](https://junit.org/junit5/docs/current/api/org.junit.jupiter.params/org/junit/jupiter/params/converter/JavaTimeConversionPattern.html).

Also, they suggested JUnit Pioneer could host it 🙂 

AFAIK, JUnit Pioneer doesn't have standalone argument converters. Is it an addition you would accept?

Written in a style similar to the [official JUnit docs](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-argument-conversion-implicit), this is what I'd like to have from the custom converter:

| Source            | Target      | Example                                                                            |
|-------------------|-------------|------------------------------------------------------------------------------------|
| `byte` / `Byte`   | `byte[]`    | `0xF` &#8594; `ByteBuffer.allocate(Byte.BYTES).put((byte) 0xF).array()`                     |
| `short` / `Short` | `byte[]`    | `0xFFF` &#8594; `ByteBuffer.allocate(Short.BYTES).putShort((short) 0xFFF).array()`           |
| `int` / `Integer` | `byte[]`    | `0xFFFFFFF` &#8594; `ByteBuffer.allocate(Integer.BYTES).putInt(0xFFFFFFF).array()`       |
| `long` / `Long`   | `byte[]`    | `0xFFFFFFFFL` &#8594; `ByteBuffer.allocate(Long.BYTES).putLong(0xFFFFFFFFL).array()` |

Two proposals came out from the discussion with the JUnit team about the annotation naming:
* `@IntegralToBytesConversion`
* `@IntegralToByteArrayConversion`

(happy to receive any other proposals, of course)

The original test could become:

```java
@ParameterizedTest
@ValueSource(ints = {Integer.MIN_VALUE, 0, 0xFF, 0xFFFF, 0xFFFFFF, Integer.MAX_VALUE})
void test(@IntegralToByteArrayConversion byte[] byteArray) {
  assertThat(byteArray).hasSize(4);
  // do some real stuff
}
```

As an additional point, the order/endianness could be configurable with an optional attribute of the annotation.

Any thoughts?

Happy to prepare a PR if the idea is accepted.

**Comment by Michael1993** [comment]
Hi @scordio !

I have nothing to add other than: Sounds great! Go ahead with a PR if you have the time. If not, let me know and I'll put together something. 😄

**Comment by scordio** [comment]
Thanks, @Michael1993! I'll try to prepare a PR in the next few days 🙂

**Comment by Michael1993** [comment]
Hi @scordio !

I have a small branch ready for review - unless you want to work on this yourself? Let me know. 😄

**Comment by scordio** [comment]
Thanks a lot, @Michael1993!

I was on the topic last weekend but had some weird compile error related to the module descriptor in the test scope and I couldn't figure out if it's only my local issue... need to check it further.

Anyway, highly appreciated that you are spending time on this topic 🙂 

I'll have a look at #742 and share my thoughts!
