### ISSUE TITLE
Suggest adding `Feature.ALLOW_TRAILING_COMMA` to the lenient Jackson object mapper

### ISSUE THREAD

**Issue by david-bakin-sl** [junit-pioneer/junit-pioneer#740]
Allowing trailing commas would make it (slightly) easier to add/remove test cases from the end of the JSON specification of a JSON parameterized test.

At [JacksonJsonConverter's constructor](https://github.com/junit-pioneer/junit-pioneer/blob/15013fcd9100891f708124cc947e8215096b94fa/src/main/java/org/junitpioneer/jupiter/json/JacksonJsonConverter.java#L33).

**Comment by beatngu13** [comment]
Hi @david-bakin-sl,

thx for the suggestions – makes sense to me as our default mapper shall be "lenient". Other opinions?

Side note: [`JsonParser.Feature.ALLOW_TRAILING_COMMA`](https://javadoc.io/static/com.fasterxml.jackson.core/jackson-core/2.15.2/com/fasterxml/jackson/core/JsonParser.Feature.html#ALLOW_TRAILING_COMMA) is deprecated as of Jackson 2.10, we should use [`JsonReadFeature.ALLOW_TRAILING_COMMA`](https://javadoc.io/static/com.fasterxml.jackson.core/jackson-core/2.15.2/com/fasterxml/jackson/core/json/JsonReadFeature.html#ALLOW_TRAILING_COMMA) instead.

**Comment by david-bakin-sl** [comment]
Nothing else for me.  The only other one I really like is allowing comments and that's already set.

**Comment by beatngu13** [comment]
@david-bakin-sl feel free to create a PR. Otherwise, I will mark it as "up for grabs". ✌️

**Comment by Michael1993** [comment]
Tentatively added to #741

**Comment by Michael1993** [comment]
Added in #741
