### ISSUE TITLE
Create simple aggregator

### ISSUE THREAD

**Issue by Michael1993** [junit-pioneer/junit-pioneer#745]
While working on #742, I had an idea for a simple [ArgumentAggregator](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-argument-aggregation). Imagine if you could write the following test:

```java
@ParameterizedTest
@CsvSource({
    "Jane Doe, 51, F",
    "John Doe, 50, M"
})
void testPeople(@Aggregate Person person) {
    // some assertions
}
```

So I created #744, which does exactly that. 😊 It comes with a couple stipulations but it covers the basic use case: you have an object with a constructor and some arguments (same order) and you want to create an object from them.

I'm not sure this has any merit as it's very simple to either use `ArgumentAccessor` or write your own `ParameterResolver` or even `ArgumentsAggregator` instead. Thoughts?

// P.S.: This is a rather trivial thing both to think of and to write so let me know if this already exists somewhere - I did not look.

**Comment by Bukama** [comment]
I like really like the idea as it's makes writing tests more maintainable when you don't have to call the constructor in every test. 

What I can't see or understand is how you decide which constructor do you choose, meaning how do you decide what types the values are. When I understand you draft correctly you treat them all as Strings and then maybe try to turn them into primitives (like the age here). But I do not (yet) understand where you transform the gender into the `Gender` class in your draft or how you would transform the birthday into a `LocalDate` (if we have a look at the JUnit example, where the class is passed to the `ArgumentsAccessor`). To nail down the question I still have in mind: (How) Can (Do) we support non primitive/non Strings constructors?

Second quests would be: Does the same thing works with records? We are on 11 but many apps, which use Pioneer are on newer versions. I imagine it works out of the box as with data projection with JPA, but we might want to test that (at least once, not with a current test due Java version - and if it fails maybe file a ticket for when we upgrade to Java 17+)

**Comment by Michael1993** [comment]
`enum`, `LocalDate`, `LocalTime` and `LocalDateTime` mapping works out of the box because we use [`ArgumentsAccessor::get(int, Class)`](https://junit.org/junit5/docs/5.2.0/api/org/junit/jupiter/params/aggregator/ArgumentsAccessor.html#get(int,java.lang.Class)).

> [...] In such cases, an [ArgumentsAccessor](https://junit.org/junit5/docs/current/api/org.junit.jupiter.params/org/junit/jupiter/params/aggregator/ArgumentsAccessor.html) can be used instead of multiple parameters. Using this API, you can access the provided arguments through a single argument passed to your test method. In addition, type conversion is supported as discussed in [Implicit Conversion](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-argument-conversion-implicit).

This solution does not work for more complex types (i.e.: you have another object as a field in your parameter) but we already have JSON source supporting that use-case (and maybe we should consider adding YAML? ¯\\\_(ツ)_/¯ ).
