### ISSUE TITLE
1.9.1: Update Jackson-Databind compile dependency due CVE

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#747]
As you can see in [Maven central, Pioneer version 1.9.1 ](https://mvnrepository.com/artifact/org.junit-pioneer/junit-pioneer/1.9.1)lists two CVE for the compile dependency of 

`com.fasterxml.jackson.core » jackson-databind`

I suggest so release an Update for 1.9 branch to update the dependency and to provide our users a version where Maven central does not shows CVEs

**Comment by beatngu13** [comment]
Hmmm, not sure about that. Do we consider 1.x as still maintained? (Personally, I don't.) No CVEs for [2.0.1](https://mvnrepository.com/artifact/org.junit-pioneer/junit-pioneer/2.0.1).

**Comment by Bukama** [comment]
I'm not sure, we said no new features for 1.9 / Java 8. But I'm okay with that we don't.
