### ISSUE TITLE
RetryingTest doesn't work well with false AssertJ assumptions

### ISSUE THREAD

**Issue by Thesoftpreneur** [junit-pioneer/junit-pioneer#766]
I'm writing some tests using the template design pattern and some tests are skipped intentionally if the assumption is not met.

Unfortunately some tests are flaky so I tried to add the `@RetryingTest` annotation. Everything works well until the assumption returns false (the test should be skipped). In that case the following exception is thrown 
```
PreconditionViolationException: Illegal state: required test method is not present in the current ExtensionContext
```

In the below repo I extracted the following issue.

https://github.com/Thesoftpreneur/RepeatedTestsAnnotationIssueForJunitPioneerExtensions

**Comment by Michael1993** [comment]
`@RetryingTest(n)` is used instead of `@Test` or other such annotations (e.g. `@RepeatedTest`).

If you remove the `@Test` annotation from your test it should work.
