### ISSUE TITLE
AssumptionViolatedException is not handled properly for RetryingTests

### ISSUE THREAD

**Issue by Thesoftpreneur** [junit-pioneer/junit-pioneer#767]
With given tests:
```java
public class HandlingSkippedTests {

    /**
     * Works well !
     */
    @RetryingTest(maxAttempts = 7, name = "[{index}] {displayName}")
    void handlingTestAbortedException() {
        throw new TestAbortedException();
    }

    /**
     * Should behave the same way as the {@link #handlingTestAbortedException()}
     * but unfortunately the {@link AssumptionViolatedException} is interpreted the same way as assertion
     */
    @RetryingTest(maxAttempts = 7, name = "[{index}] {displayName}")
    void handlingAssumptionViolatedException() {
        throw new AssumptionViolatedException("assumption is not met");
    }
}
```

I expect that the `AssumptionViolatedException` from the `org.junit.platform:junit-platform-runner:1.8.2` dependency to have the same result like `TestAbortedException`. This exception is thrown from assertJ assumptions that are ran by Junit platform runner. eg

```java

import static org.assertj.core.api.Assumptions.assumeThat;

// ...

assumeThat(false).isTrue();
```

**Current result:**
The `TestAbortedException` aborts the test as soon it is thrown while the `AssumptionViolatedException` is treated like any other exception despite both relates to the failed test assumptions.

Below I provided a working example to run.

https://github.com/Thesoftpreneur/RepeatedTestsAnnotationIssueForJunitPioneerExtensions/blob/main/src/test/java/org/example/HandlingSkippedTests.java

**Comment by Thesoftpreneur** [comment]
+ 1 notice regarding to the javadoc of the `AssumptionViolatedException` class

An exception class used to implement assumptions (state in which a given test is meaningful and should or should not be executed). **A test for which an assumption fails should not generate a test case failure.**

**Comment by Michael1993** [comment]
Thank you for opening this issue. Please give us some time to investigate and discuss.

As far as I can see `AssumptionViolatedException` actually comes from JUnit 4.

![image](https://github.com/junit-pioneer/junit-pioneer/assets/4085611/770c3cde-bf6b-4fea-89e9-ac8a3d663ac0)

JUnit 5 relies on `opentest4j` (an initiative by the JUnit team) for exceptions, see here: https://github.com/ota4j-team/opentest4j/tree/main/src/main/java/org/opentest4j

`org.assertj.core.api.Assumptions.assumeThat` and `org.junit.jupiter.api.Assumptions.assumeTrue` both throw `org.opentest4j.TestAbortedException`. Are you by chance using the JUnit 4 `Assume` class? JUnit 5.4 introduced special support for that.

**Comment by Thesoftpreneur** [comment]
The project, where issue was found, is written in Junit5 (Jupiter), but the runner comes from the `junit-platform-runner` (running classes) , that it unfortunately related to Junit4. I threw the exception explicitly only in order to extract the issue. In practice the excpetion is thrown by the test runner while that failed assumption is triggered.

**Comment by Michael1993** [comment]
Could you tell me why you are using `junit-platform-runner`? As far as I can see the only thing there is a (deprecated) `Runner` that explicitly runs tests in a JUnit 4 context?

**Comment by Thesoftpreneur** [comment]
That runner was already in the project and suprisingly was working with the junit5 annotations. I already discussed with the team and would we would have to fix that deprecations on our side anyways despite that would require some refactoring in the core framework.

**Comment by Michael1993** [comment]
I'm not entirely sure I understand your last message.

Do you need any additional help? Is it okay if I close this ticket?

**Comment by Thesoftpreneur** [comment]
Yes, it would ok. At the time of reporting the issue I wasn't aware that the framework, that  I'm working on, have still some deprecated artefacts from JUnit4
