### ISSUE TITLE
Make SonarCloud job use Java 17

### ISSUE THREAD

**Issue by beatngu13** [junit-pioneer/junit-pioneer#782]
Via [Sonar Commmunity](https://community.sonarsource.com/t/java-11-is-deprecated-as-a-runtime-env-to-scan-your-projects/96597):

>We wanted to give you a heads-up that we’re moving away from supporting Java 11 as a runtime environment for the Scanners. We’re encouraging everyone to migrate their scan pipelines to Java 17 as soon as possible. The documentation has been updated accordingly for SonarCloud. For SonarQube, Java 11 will be deprecated starting from SonarQube 10.2, and SonarQube 9.9 LTS is not impacted.
We do this move because Java 21 is arriving soon on the 19th of September 2023 and our policy is to only support the two latest Java LTS.
>
>We plan to drop support for Java 11 as a runtime environment on **November 15th, 2023**.

Currently, we run our SonarCloud analysis as part of our `basic` job:

https://github.com/junit-pioneer/junit-pioneer/blob/13c2c4d5ebc0f13382b1a5607fb697e87d0e5ce0/.github/workflows/build.yml#L81-L86

I see two options:

1. Let the `basic` job use Java 17 (still targeting 11 with `--release`, as we already do).
2. Introduce a separate (possibly parallel) analysis job, similar to e.g. `code-format-check`, using Java 17.

**Comment by Bukama** [comment]
I would vote for the second solution (or extend the `code-format-check` one) as the `--release` parameter on a higher JDK can still bring up other results as far as I know, e.g. with the `SecurityManager` things.

**Comment by nipafx** [comment]
Related to #785: When we build an MR-JAR that contains, e.g., JDK 21 bytecode, it would probably be easiest to move the entire build to 21.
