### ISSUE TITLE
Feature Request: Publish PioneerTestKit

### ISSUE THREAD

**Issue by nrllewellyn** [junit-pioneer/junit-pioneer#786]
As a developer who maintains several internal JUnit extensions and (hopefully soon) an open-source one, it would be extremely useful to have access to `PioneerTestKit`. Theoretically this could be accomplished by moving it to `main`, or by publishing `test` as a JAR (although I'm sure there are other options as well!).

**Comment by Michael1993** [comment]
I asked the other maintainers and we voted to not do this for two reasons:
1.) It would limit our options in the future.
2.) The code is publicly available under what is basically the most permissible license - you can freely copy-paste, modify and use the code. If you have some improvement ideas, feel free to propose them and we might add them anyways. 😄 
3.) ~~We don't want to.~~

If you wish, you could easily create a fork and make an "as-is" repo of just the test kit (that you can publish as well if you want to use it in your work)?

**Comment by nrllewellyn** [comment]
Makes sense. Thank you for the info! :-)
