### ISSUE TITLE
No longer mention issue and PR numbers in commit title

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-pioneer/junit-pioneer#79]
The [current contribution guidelines](https://github.com/junit-pioneer/junit-pioneer/blob/master/CONTRIBUTING.md#merging) define the following outline for commit messages, where the first line (let's call it "title") has an ideal length of 50 characters, with a maximum of 70:

```
${action} (${issues} / ${pull-request})

${body}
```

Mentioning issue and pull request numbers in the title has the advantage of making them very visible, for example in `git log --oneline` and GitHub's UI, but has the downside of severely reducing the number of available characters for the title itself. Once we cross into three digit issue/PR numbers `(#abc / #xyz)` eats up at least 14 characters - that's not good.

As an alternative, issues and pull requests could be added as a last line to the message:

```
${action}

${body}

${issues} / ${pull-request}
```

Opinions?

**Comment by sormuras** [comment]
70? [**2 8 0 !**](https://blog.twitter.com/official/en_us/topics/product/2017/tweetingmadeeasier.html)

Your proposal looks good to me.

**Comment by sbrannen** [comment]
I agree, but let's also use prefixes for the issue and PR numbers -- for example:

```
${action}

${body}

Issue: ${issues} / ${pull-request}
```

Where "Issue" can be:

- Issue
- Issues
- Fixes
- Closes

**Comment by nicolaiparlog** [comment]
@sbrannen Are the replacements for "Issue" meant to be GitHub keywords? If so, we have to get rid of the colon, don't we?

**Comment by nicolaiparlog** [comment]
I just looked over the [list of commits](https://github.com/junit-pioneer/junit-pioneer/commits/master) and I have to say, I really like what I see: the issue and PR numbers out in the open. Are we sure we want to give that up?

Since I seem to be the only one thinking "No" and ... team ... democracy ... yadda yadda yadda :wink: ... check #86.

**Comment by sbrannen** [comment]
> Are the replacements for "Issue" meant to be GitHub keywords?

Jein ("yes & no" for non-German speakers). 😉 

It's a mix. See explanation here: https://github.com/junit-pioneer/junit-pioneer/pull/86#issuecomment-390488419

> If so, we have to get rid of the colon, don't we?

Nope. GitHub has no problem with the colon.
