### ISSUE TITLE
Introduce DisplayNameGenerator to support CamelCase, underscores, and numbers

### ISSUE THREAD

**Issue by Michael1993** [junit-pioneer/junit-pioneer#793]
See the JUnit 5 issues: [#3569](https://github.com/junit-team/junit5/issues/3569) and [#1595](https://github.com/junit-team/junit5/issues/1595).

If JUnit 5 decides not to host/support this, I think we should - let's wait for their team decision. 😄

**Comment by Bukama** [comment]
Added label "blocked" for now, until JUnit team decided

**Comment by Michael1993** [comment]
We are Pioneers! We bravely go where no man has gone before!

I say let's integrate this into Pioneer and if JUnit decides to officially support this we can still remove/deprecate it.

**Comment by Bukama** [comment]
> We are Pioneers! We bravely go where no man has gone before!
> 
> I say let's integrate this into Pioneer and if JUnit decides to officially support this we can still remove/deprecate it. (Me, impatient? Never!)

Convinced :) Do you start the countdown? 🚀

**Comment by Bukama** [comment]
> Added label "blocked" for now, until JUnit team decided

Well they have decicded on #1595 already in 2020 to not implement it, cause of edge cases. I thin that opens the door for pioneering it even more

**Comment by FanJups** [comment]
> > Added label "blocked" for now, until JUnit team decided
> 
> Well they have decicded on #1595 already in 2020 to not implement it, cause of edge cases. I thin that opens the door for pioneering it even more

Great, lets go 😊

**Comment by FanJups** [comment]
So, can I PR ?

**Comment by FanJups** [comment]
@Bukama , please assign me this issue.

**Comment by Bukama** [comment]
> @Bukama , please assign me this issue.

Hey @FanJups On our yesterdays team meeting we talked about this issue and as you have not responded to @Michael1993 comment in any kind of form (comment, question or PR) we assumed that you abandoned the topic and @Michael1993 volunteered to give it a shot.

I will assign the issue to you now, but assuming you will present any progress on it (e.g. a draft PR) in the near future.

**Comment by FanJups** [comment]
Thanks

> > @Bukama , please assign me this issue.
> 
> Hey @FanJups On our yesterdays team meeting we talked about this issue and as you have not responded to @Michael1993 comment in any kind of form (comment, question or PR) we assumed that you abandoned the topic and @Michael1993 volunteered to give it a shot.
> 
> I will assign the issue to you now, but assuming you will present any progress on it (e.g. a draft PR) in the near future.

Thanks @Bukama , it will be ready for review no later than May 19.

**Comment by FanJups** [comment]
I created a new PR. Before moving forward with documentation, please I want your feedback on what is already done. I faced an issue regarding one of my test classes.
