### ISSUE TITLE
Update build pipeline to EA of Java 23

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#795]
@sormuras just tooted that Java 23 EA is available to use  in Github actions

https://github.com/marketplace/actions/setup-java-development-kits-built-by-oracle

**Comment by beatngu13** [comment]
We already use Java 22 EA builds:

https://github.com/junit-pioneer/junit-pioneer/blob/35e8d0522450e023d02cb907c6ae2d65bcaa7702/.github/workflows/build.yml#L4

Do we really want/need to test two versions ahead of the current Java release? If yes, do want a (new) matrix build using 22 _and_ 23 or just the latter?

**Comment by Bukama** [comment]
To be honest: I'm not sure what we decided about the experimental version. And I'm even less sure if we ever were in a situation that there are Github actions for two experimental versions. 

For me it's fine when we agree to build only the EA of the next regular release (would be 22 at the moment) as the EA after that might be quite vague and probably flaky.

**Comment by Bukama** [comment]
No further comments, so I close this as won't do.
