### ISSUE TITLE
Update copyright line to 2024

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#801]
The copyright line must be updated to 2024

>  * Copyright 2016-2023 the original author or authors.

**Comment by Bukama** [comment]
@d1vofficial has created a PR (now I need to fine a way to assign the ticket to him, strange Github..)

**Comment by Michael1993** [comment]
The LICENSE file has `$YEAR`, it should update automatically. I just checked and if you create a new file, spotless will put this as the license:
![image](https://github.com/junit-pioneer/junit-pioneer/assets/4085611/ca862e3a-2b83-4a3f-bff1-bdb85ceea84f)

I think the project is fine as-is but I'm like the opposite of an expert on legal things.

**Comment by Bukama** [comment]
> We can add the following option to `spotless`:
> 
> ```kotlin
> licenseHeaderFile(headerFile, "(package|import) ")
> 	.updateYearWithLatest(true)
> ```
> 
> This would make it a violation if the year is not up to date (as well as automatically updating the year, of course). Is this something that we want?

I think this is a great idea. Do you want to hijack this PR and finish it?

**Comment by beatngu13** [comment]
Back in 2016, the Eclipse project itself was annoyed by the modification year (see [bug 485257](https://bugs.eclipse.org/bugs/show_bug.cgi?id=485257)), so they abandoned the requirement for updating it (see [PMC meeting from May 24, 2016](https://wiki.eclipse.org/Eclipse/PMC/Minutes_2016)). Their EPL header now looks as follows (see [Eclipse Project Handbook](https://www.eclipse.org/projects/handbook/#ip-copyright-headers)):

```text
/********************************************************************************
 * Copyright (c) {year} {owner}[ and others] 1
 *
 * This program and the accompanying materials are made available under the 2
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0 3
 *
 * Contributors: 4
 *   {name} - initial API and implementation
 ********************************************************************************/
```

Where "`{year}` is the year in which the content was created (e.g. “2004”)".

So, if we want, we could also get rid of it.

**Comment by Michael1993** [comment]
I think this is essentially what we do now - except we include the starting year (2016) as well, so it's `2016-{year created}`.

**Comment by beatngu13** [comment]
Hmmm, I understand it differently. We have Pioneer's creation date and the current year, which is why we update it every year – as this issue says, "The copyright line must be updated to 2024".  The Eclipse project got rid of that requirement.

**Comment by Michael1993** [comment]
Both me and @beatngu13 vote for not doing anything and just letting spotless use the latest year whenever we create a new file. This is essentially the current behaviour - we added the `$YEAR` placeholder to our license in 2023, so going forward we can just skip updating it.

I vote to close the issue and the corresponding PR.

**Comment by beatngu13** [comment]
@Michael1993 via Discord:

>But I think it'd make sense if we migrated to just $YEAR moving forward...

💯

**Comment by Bukama** [comment]
So we need a PR to update to `$YEAR`.

**Comment by Bukama** [comment]
Closing

**Comment by Michael1993** [comment]
Sorry, actually, I would like to migrate to $YEAR moving forward.
