### ISSUE TITLE
Discussion: Support test management tools - new extension or add more parameters to @Issue-Extension

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#829]
Many companies use test management tools, e.g. HP ALM, to design, plan and document their QA tests and the results of executed tests runs. While this is obviously for manual testing, it's not limited to this. Therefore such tools often provide a REST API so automation frameworks can store e.g. the result of a test run.

At the moment my team and I think about storing the results of our Selenium tests (but you could extend this to all kind of tests, including unit tests if you want) automatically in HP ALM. With my knowledge gathered in Pioneer I instantly thought about an test management extension to annotate a test with the name of the corespondending test name in the test management tool (or ID, depending of the tool) and then store the result of a run. To reduce traffic I was thinking about the same way as the issue extension. This means: Run all the tests, collect the results, and then call the REST service instead of individual calls. To be flexible in terms of the extension I think a split into a an extension with a service provider interface and the actual service implementation (maybe exactly for a specific tool, but this should not be part of the topic here) makes sense.

To come to the point I want to discuss:

With the [Issue-Extension](https://junit-pioneer.org/docs/issue/) it's possible to create relation between a test case and its underlying requirement or bug. The extension then allows to collect an aggregated list of all tests grouped by their issue together with the test result via a service provider interface.

This means the extension does more or less everything I would need/want for the test management extension. So you could think about adding an optional attribute to the issue extension for the test name/id.

```
@Issue(issue="bug-123" test="oneOfTheTestFor123")
void myTest() {};

@Issue(issue="bug-123" test="SecondTestFor123")
void myOtherTest() {};
```

I argue that from a semantically POV this would work in terms of "that's the issue and that's one test to proof the solution", but you could also argue against this. Technically the issue extension is not designed for additional (and then named) parameters, so an extension could (will?) break existing usages. You could also argue that requirement management tool, issue/defect tracker and test management tools might be three different tools (yes I know such setups), but I think this would more be a problem of the service implementation.

So the points I want to hear your opinions to are

* Do we want to provide some kind of test management extension?
* If yes: Do we want to do this by adding more parameters to the issue extension or create a new extension with more or less "copied code"

If there are any question about the scenario, feel free to ask me here or in the Discord.

**Comment by Michael1993** [comment]
I think this issue still has potential, even if we ultimately decide against going this way.
