### ISSUE TITLE
Simplify Gradle publishing configuration

### ISSUE THREAD

**Issue by marcphilipp** [junit-pioneer/junit-pioneer#83]
Currently, the build script defines two Maven repositories in the `publishing` block which leads to Gradle creating two publishing tasks:

https://github.com/junit-pioneer/junit-pioneer/blob/9ada30b5ce06d5dd9fc1793a11dd665aa80f8268/build.gradle#L260-L277

The build script then takes extra care to disable the `publish` lifecycle task (because it would attempt to publish to both) and only enable the snapshot publishing tasks for snapshots and the release publishing one for releases:

https://github.com/junit-pioneer/junit-pioneer/blob/9ada30b5ce06d5dd9fc1793a11dd665aa80f8268/build.gradle#L167-L194

Those decisions are entirely based on the `isReleaseVersion` property:

https://github.com/junit-pioneer/junit-pioneer/blob/9ada30b5ce06d5dd9fc1793a11dd665aa80f8268/build.gradle#L17

## Proposal

Instead, it would be much simpler if we only configured a single Maven repository and used `isReleaseVersion` to determine it's URL:

```gradle
publishing {
    repositories {
        maven {
            def releasesRepoUrl = 'https://oss.sonatype.org/service/local/staging/deploy/maven2/'
            def snapshotsRepoUrl = 'https://oss.sonatype.org/content/repositories/snapshots/'
            url isReleaseVersion ? releasesRepoUrl : snapshotsRepoUrl
            credentials {
                username mavenUserName
                password mavenPassword
            }
        }
    }
}
```

As a matter of fact, a very similar example has just been published as part of the [Gradle 4.8 RC1 User Guide chapter on the Maven Publish Plugin](https://docs.gradle.org/4.8-rc-1/userguide/publishing_maven.html#publishing_maven:snapshot_and_release_repositories). Disclaimer: I wrote it. 😉

**Comment by nicolaiparlog** [comment]
Yes, please!

Btw, I love your work on `build.gradle`. It's my first Gradle build file and I think it shows. :wink: If you're done with this, maybe you can tackle [this obscenity](https://github.com/junit-pioneer/junit-pioneer/blob/master/build.gradle#L223-L257). :blush:

**Comment by marcphilipp** [comment]
> If you're done with the repos, maybe you can tackle [this obscenity](https://github.com/junit-pioneer/junit-pioneer/blob/master/build.gradle#L223-L257).

I gladly will but that requires Gradle 4.8 which introduces a new [DSL to customize the POM](https://docs.gradle.org/4.8-rc-1/userguide/publishing_maven.html#sec:modifying_the_generated_pom) which I also have been working on. 😉

**Comment by nicolaiparlog** [comment]
That would be awesome. In the meantime, feel free to work on this. :)
