### ISSUE TITLE
Use ShipKit to release continuously

### ISSUE THREAD

**Issue by marcphilipp** [junit-pioneer/junit-pioneer#87]
The Mockito project has written [Shipkit](https://github.com/mockito/shipkit), a Gradle plugin to release with every commit to `master`.

From the readme:

> You will be more productive if your releases are fully automated and happen on every change. You will build great product if you can focus on code & features, but not on the release overhead. Shipkit will make it happen. Shipkit is a toolkit for shipping it.

I think we should seriously consider using it.

It looks like it currently only supports Bintray, though. @mockitoguy Is that correct?

Thoughts?

**Comment by nicolaiparlog** [comment]
That sounds great (and would fix #53), but releasing every commit? Phew, I'm not sure whether I'm up to that. I mean, are we sure our code (and tests) are good enough, that every merged PR hits home? I know they technically _should_, but _will_ they?

We're still before `1.0`, so stability requirements are lower - we could just give it a try and observe. Although without users (that I know of), we will hardly know if we screw up.

**Comment by mockitoguy** [comment]
>It looks like it currently only supports Bintray, though. @mockitoguy Is that correct?

Yes, correct. Is this a problem? Bintray is a great repo, very easy to use. We release to Maven Central via Bintray.

In Shipkit we want to support releasing directly to Sonatype. We haven't implemented it yet due to other priorities. It would be great if you tried out Shipkit!

>I mean, are we sure our code (and tests) are good enough, that every merged PR hits home? I know they technically should, but will they?

It's a great forcing function. Your tests will have to be great. I absolutely recommend this model.

**Comment by nicolaiparlog** [comment]
I can see up- and downsides and end up with not having a strong opinion either way. Everybody else (who chimed in) seems to think this is worth a try, so if nobody speaks up against this soon, we should do it.

**Comment by marcphilipp** [comment]
First step:
https://github.com/junit-pioneer/junit-pioneer/commit/64afd4fd50c9f26019f5d3f881d1c31720668b4f

### Next steps:

- [ ] [Setup Bintray](https://blog.bintray.com/2014/02/11/bintray-as-pain-free-gateway-to-maven-central/)
- [ ] [Resolve TODOs in `gradle/shipkit.gradle`](https://github.com/mockito/shipkit/blob/master/docs/getting-started.md#shipkitgradle-configuration-file)
- [ ] [Setup Travis to use Bintray](https://github.com/mockito/shipkit/blob/master/docs/getting-started.md#production-configuration)

**Comment by nicolaiparlog** [comment]
Thanks @marcphilipp, for the lazy-friendly guide. :smiley: Of course, I'm not giving anybody my private GPG key, so I'll configure it to use Bintray's keypair (see **Update** in [this post](https://blog.bintray.com/2013/08/06/fight-crime-with-gpg/)). Could that be a problem?

**Comment by nicolaiparlog** [comment]
I think, I've set everything up. Couple of things:

* It's not clear to me how Travis signs into Bintray - do we have to add credentials as environment variables?
* If anybody wants to become a member of the JUnit Pioneer organization on Bintray, tell me your Bintray username.
* @marcphilipp: Please have a look at [`CONTRIBUTING.md`](https://github.com/junit-pioneer/junit-pioneer/blob/master/CONTRIBUTING.md#publishing) and update it to match the Shipkit/Bintray approach

**Comment by sormuras** [comment]
> It's not clear to me how Travis signs into Bintray - do we have to add credentials as environment variables?

Yes. Generate user and pass/key tokens at Bintray and use them like:  
https://github.com/sormuras/bartholdy/blob/master/gradle/shipkit.gradle#L12-L13

**Comment by sormuras** [comment]
Caveat: before activating Shipkit we should wait until https://github.com/mockito/shipkit/issues/727 is fixed -- as we are running on Gradle 4.8

**Comment by nicolaiparlog** [comment]
Thanks @sormuras, I just made my user name and API key available as environment variables `BINTRAY_USER_NAME` and `BINTRAY_API_KEY`.

**Comment by marcphilipp** [comment]
I've updated `CONTRIBUTING.md` in the branch.

@sormuras Since you've set it up successfully for [bartholdy](https://github.com/sormuras/bartholdy), could you take it from here?

**Comment by sormuras** [comment]
**Add to JCenter** is missing: https://bintray.com/junit-pioneer/junit-pioneer/junit-pioneer

![image](https://user-images.githubusercontent.com/2319838/42216896-a779d1e0-7ec3-11e8-886d-8cce1f0f53f1.png)

**Comment by nicolaiparlog** [comment]
Mmh, I'm sure I've tried that but got an error because we don't have any versions yet. Just tried it again, this time checking the box that we want to host snapshot build artifacts at https://oss.jfrog.org, and the request went out.

Re trying this out, I'm fine with you force pushing "the same commit" to master over and over while trying to get this to work as long as you use `--force-with-lease`. I'd much prefer that over a series of commits.

**Comment by nicolaiparlog** [comment]
My request "to include [my] package /junit-pioneer/junit-pioneer/junit-pioneer in Bintray's JCenter has been approved."

**Comment by sormuras** [comment]
Fine. Almost clear to go. Will look into the branch tonight.

**Comment by sormuras** [comment]
The CI enviroment (Travis CI, I guess) needs similar secret tokens:

https://travis-ci.com/sormuras/bartholdy/jobs/132547102#L429
```
Setting environment variables from repository settings
$ export GH_WRITE_TOKEN=[secure]
$ export BINTRAY_USER=[secure]
$ export BINTRAY_KEY=[secure]
$ export NEXUS_USER=[secure]
$ export NEXUS_PASS=[secure]
```

See https://github.com/mockito/shipkit/blob/master/docs/getting-started.md#shipkitgradle-configuration-file

**Comment by sormuras** [comment]
_in progress_...

**Comment by sormuras** [comment]
Proposed commit message:

```
Introduce Shipkit-based continuous delivery

Starting with this commit, all changes made to the project that
result in a different binary artifact to the last published one
will lead to new release of this project.

To achieve this continuous delivery behavior, Shipkit is introduced:

  You will be more productive if your releases are fully automated
  and happen on every change. You will build great product if you
  can focus on code & features, but not on the release overhead.

For details see: https://github.com/mockito/shipkit


Closes: #87
```

**Comment by sormuras** [comment]
`[performRelease] > Could not sync 'junit-pioneer/junit-pioneer/junit-pioneer/0.1.0' to Maven Central: HTTP/1.1 400 Bad Request [status:Sync Failed, messages:[Authentication failed.]]`

Needs some token love.

**Comment by sormuras** [comment]
### Bintray

https://dl.bintray.com/junit-pioneer/junit-pioneer/org/junit-pioneer/junit-pioneer/ `0.1.2` ✔️ 

### JCenter

https://jcenter.bintray.com/org/junit-pioneer/junit-pioneer/ `0.1.2` ✔️ 

### Maven Central

_Sync in progress..._

http://central.maven.org/maven2/org/junit-pioneer/ *[404 Not Found]*

**Comment by sormuras** [comment]
Sync completed.

Now every commit to `master` is released and published.

**Comment by mockitoguy** [comment]
Fantastic!!! Thank you for using Shipkit!
