### ISSUE TITLE
Confusing snapshots old 1.0.0.-Snapshot from 2017 vs 0.1-Snapshot from 2018

### ISSUE THREAD

**Issue by Siedlerchr** [junit-pioneer/junit-pioneer#89]
Hi,

I noticed that the current Sonatype repository is confusing.
https://oss.sonatype.org/content/repositories/snapshots/org/junit-pioneer/junit-pioneer/

There is a version 1.0.0-Snapshot avaiable, which obviously has a greater version number as 0.1-Snapshot but an older date.  And there's even an older 0.001 version.
This is confusing for a lot of dependency update checker tools. I would propose to delete the old versions. 

In our project we use  the [gradle verison plugin](https://github.com/ben-manes/gradle-versions-plugin) which reports the version 1.0.0. as newer

**Comment by nicolaiparlog** [comment]
Thanks for pointing that out. :+1: Done.
