### ISSUE TITLE
Publish non SNAPSHOT release

### ISSUE THREAD

**Issue by JLLeitschuh** [junit-pioneer/junit-pioneer#95]
I'm totally happy if you make API breaking changes in the future. But I'd love to be able to utilize the `@TempDirectory` annotation in my tests and I can't do that if this project keeps re-publishing over the same snapshot version.

**Comment by nicolaiparlog** [comment]
Hi Jonathan, thanks for reporting. We're currently working on our release setup (see #87) and plan to have a first non-snapshot release soon. I will close this issue, but in the unlikely case that we didn't deliver, feel free to reopen it.

**Comment by JLLeitschuh** [comment]
For now, hard coding the snapshot version works for me:
```
testImplementation(group = "org.junit-pioneer", name = "junit-pioneer", version = "0.1-20180709.104155-29")
```

**Comment by sormuras** [comment]
Try version `0.1.2` now. It's available from `central.maven`.

**Comment by JLLeitschuh** [comment]
Seems to work. Thanks @sormuras !!
