### ISSUE TITLE
Publish release notes

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-pioneer/junit-pioneer#97]
Shipkit generates release notes in `./docs/release-notes.md`. We should look into publishing them, maybe after manual editing, on junit-pioneer.org. This could be non-trivial because we're currently working with Asciidoc files and I have no idea how Jekyll reacts to mixing Markdown and Asciidoc and neither do I know whether it would be possible to have Shipkit generate Asciidoc.

**Comment by nicolaiparlog** [comment]
Turns out we're already mixing Markdown with Asciidoc (because Liquid tags only seem to be processed in Markdown files), so that's not a problem.

A problem is that Shipkit adds the release notes in a commit that does not trigger a build and so these information are not actually available when the page is built. It would make sense to have only Shipkit builds trigger a page rebuilt because only than something actually changed.

**Comment by Bukama** [comment]
We decided to move the issues related to the web site to the junit-pioneer.github.io repo. So I moved the issue there. Link is: [junit-pioneer/junit-pioneer.github.io#10](https://github.com/junit-pioneer/junit-pioneer.github.io/issues/10)
