### ISSUE TITLE
Show current version on junit-pioneer.org

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-pioneer/junit-pioneer#98]
It should be easy for visitors to immediately see the latest version they can download.

A possible implementation would be to query the [Maven Central API](http://search.maven.org/#api) for the most recent version. Another would be to have Shipkit trigger a specific "publication" build that presents the version determined by Shipkit. The latter might be necessary anyway to publish release notes (see #97), which are also only available after Shipkit's commit.

**Comment by nicolaiparlog** [comment]
Heroku badge: <img src="https://maven-badges.herokuapp.com/maven-central/org.junit-pioneer/junit-pioneer/badge.svg?style=flat" alt="Latest Junit Pioneer on Maven Central">

Shields.io: <img src="https://img.shields.io/maven-central/v/org.junit-pioneer/junit-pioneer.svg" alt="Latest JUnit Pioneer on Maven Central">

**Comment by sormuras** [comment]
Do the colors have a meaning? What controls it?

**Comment by nicolaiparlog** [comment]
No. Can't be changed. (Both are guesses.)

**Comment by Bukama** [comment]
We decided to move the issues related to the web site to the junit-pioneer.github.io repo. So I moved the issue there. Link is: [junit-pioneer/junit-pioneer.github.io#9](https://github.com/junit-pioneer/junit-pioneer.github.io/issues/9)
